// Code generated by ent, DO NOT EDIT.

package enttest

import (
	"context"

	"github.com/frostgrove/vv/test/ent"
	// required by schema hooks.
	_ "github.com/frostgrove/vv/test/ent/runtime"

	"entgo.io/ent/dialect/sql/schema"
	"github.com/frostgrove/vv/test/ent/migrate"
)

type (
	// TestingT is the interface that is shared between
	// testing.T and testing.B and used by enttest.
	TestingT interface {
		FailNow()
		Error(...any)
	}

	// Option configures client creation.
	Option func(*options)

	options struct {
		options     []ent.Option
		migrateOpts []schema.MigrateOption
	}
)

// WithOptions forwards options to client creation.
func WithOptions(optionList ...ent.Option) Option {
	return func(o *options) {
		o.options = append(o.options, optionList...)
	}
}

// WithMigrateOptions forwards options to auto migration.
func WithMigrateOptions(optionList ...schema.MigrateOption) Option {
	return func(o *options) {
		o.migrateOpts = append(o.migrateOpts, optionList...)
	}
}

func newOptions(optionList []Option) *options {
	o := &options{}
	for _, opt := range optionList {
		opt(o)
	}
	return o
}

// Open calls ent.Open and auto-run migration.
func Open(t TestingT, driverName, dataSourceName string, optionList ...Option) *ent.Client {
	o := newOptions(optionList)
	c, err := ent.Open(driverName, dataSourceName, o.options...)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	migrateSchema(t, c, o)
	return c
}

// NewClient calls ent.NewClient and auto-run migration.
func NewClient(t TestingT, optionList ...Option) *ent.Client {
	o := newOptions(optionList)
	c := ent.NewClient(o.options...)
	migrateSchema(t, c, o)
	return c
}
func migrateSchema(t TestingT, c *ent.Client, o *options) {
	tables, err := schema.CopyTables(migrate.Tables)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	if err := migrate.Create(context.Background(), c.Schema, tables, o.migrateOpts...); err != nil {
		t.Error(err)
		t.FailNow()
	}
}
