package codegen

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	_ "github.com/frostgrove/vv/test/entstore"
	_ "github.com/frostgrove/vv/test/gormstore"
	_ "github.com/frostgrove/vv/test/versionstore"
)

func TestTheGeneratedStoresAreUpToDate(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no go toolchain")
	}
	root := repoRoot(t)

	for _, tc := range []struct {
		name string
		pkg  string

		directive string

		regen func(t *testing.T, pkg, dir string)
	}{
		{
			name:      "ent",
			pkg:       filepath.Join(root, "test", "entstore"),
			directive: "//go:generate go run github.com/frostgrove/vv/cmd/vv -dir ../ent -types User -readonly CreatedAt -import github.com/frostgrove/vv/test/ent -into .",
			regen: func(t *testing.T, pkg, dir string) {
				run(t, pkg, "-dir", "../ent", "-types", "User",
					"-readonly", "CreatedAt", "-import", "github.com/frostgrove/vv/test/ent", "-into", dir)
			},
		},
		{
			name:      "version",
			pkg:       filepath.Join(root, "test", "versionstore"),
			directive: "//go:generate go run github.com/frostgrove/vv/cmd/vv -adapter -readonly ArchivedAt",
			regen: func(t *testing.T, pkg, dir string) {
				copyGoSources(t, pkg, dir)
				run(t, root, "-dir", dir, "-adapter", "-readonly", "ArchivedAt")
			},
		},
		{
			name:      "gorm",
			pkg:       filepath.Join(root, "test", "gormstore"),
			directive: "//go:generate go run github.com/frostgrove/vv/cmd/vv -readonly UpdatedAt,DeletedAt",
			regen: func(t *testing.T, pkg, dir string) {
				copyGoSources(t, pkg, dir)
				run(t, root, "-dir", dir, "-readonly", "UpdatedAt,DeletedAt")
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			assertDirective(t, tc.pkg, tc.directive)

			dir := filepath.Join(t.TempDir(), filepath.Base(tc.pkg))
			if err := os.MkdirAll(dir, 0o755); err != nil {
				t.Fatal(err)
			}
			tc.regen(t, tc.pkg, dir)

			fresh, err := os.ReadFile(filepath.Join(dir, "vv_gen.go"))
			if err != nil {
				t.Fatal(err)
			}
			current, err := os.ReadFile(filepath.Join(tc.pkg, "vv_gen.go"))
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Contains(fresh, []byte("Code generated by vv")) {
				t.Fatalf("the regenerated file is not generator output at all:\n%s", fresh)
			}
			if string(fresh) != string(current) {
				t.Fatalf("%s/vv_gen.go is stale; run `go generate ./test/%s/...`",
					filepath.Base(tc.pkg), filepath.Base(tc.pkg))
			}

			tampered := bytes.Replace(fresh, []byte("package "), []byte("package drifted"), 1)
			if string(tampered) == string(current) {
				t.Fatal("the comparison cannot tell a changed file from the checked-in one")
			}
		})
	}
}

func run(t *testing.T, wd string, args ...string) {
	t.Helper()
	cmd := exec.Command("go", append([]string{"run", "github.com/frostgrove/vv/cmd/vv"}, args...)...)
	cmd.Dir = wd
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerating: %v\n%s", err, out)
	}
}

func copyGoSources(t *testing.T, from, to string) {
	t.Helper()
	entries, err := os.ReadDir(from)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || e.Name() == "vv_gen.go" {
			continue
		}
		source, err := os.ReadFile(filepath.Join(from, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(to, e.Name()), source, 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func assertDirective(t *testing.T, pkg, want string) {
	t.Helper()
	entries, err := os.ReadDir(pkg)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		source, err := os.ReadFile(filepath.Join(pkg, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		for _, line := range strings.Split(string(source), "\n") {
			if !strings.HasPrefix(line, "//go:generate") {
				continue
			}
			if strings.TrimSpace(line) == want {
				return
			}
			t.Fatalf("%s carries\n  %s\nbut this test regenerates with\n  %s", e.Name(), strings.TrimSpace(line), want)
		}
	}
	t.Fatalf("no //go:generate line found in %s", pkg)
}

func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	return dir
}
