// Code generated by vv. DO NOT EDIT.

package main

import (
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/port"
	"github.com/frostgrove/vv/utils"
	"time"
)

type ProductUpdate struct {
	Sku    *string        `json:"sku,omitempty"`
	Name   *string        `json:"name,omitempty"`
	Price  *int           `json:"price,omitempty"`
	Stock  utils.Opt[int] `json:"stock,omitzero"`
	Active *bool          `json:"active,omitempty"`
}

type ProductAttrs struct {
	ID        specs.Ord[Product, int64]
	Sku       specs.Str[Product]
	Name      specs.Str[Product]
	Price     specs.Ord[Product, int]
	Stock     specs.Ord[Product, int]
	Active    specs.Attr[Product, bool]
	CreatedAt specs.Cmp[Product, time.Time]
}

var Product_ = specs.Metamodel[Product, ProductAttrs]()

type ProductRepo = crud.Repo[Product, int64, ProductUpdate]

var ProductRepository = sqlrepo.Define[Product, int64, ProductUpdate]("")

func NewProductRepository(src crud.Source) *ProductRepo {
	return ProductRepository.Bind(src)
}

func init() {
	port.MustCoverUpdate[Product, ProductUpdate]()
}
