// Code generated by vv. DO NOT EDIT.

package entstore

import (
	entmodel "github.com/frostgrove/vv/_examples/entmodel"
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/port"
	"github.com/frostgrove/vv/utils"
	"time"
)

type ProductUpdate struct {
	Sku    *string        `json:"sku,omitempty"`
	Name   *string        `json:"name,omitempty"`
	Price  *int           `json:"price,omitempty"`
	Stock  utils.Opt[int] `json:"stock,omitzero"`
	Active *bool          `json:"active,omitempty"`
}

type ProductAttrs struct {
	ID        specs.Ord[entmodel.Product, int64]
	Sku       specs.Str[entmodel.Product]
	Name      specs.Str[entmodel.Product]
	Price     specs.Ord[entmodel.Product, int]
	Stock     specs.Ord[entmodel.Product, int]
	Active    specs.Attr[entmodel.Product, bool]
	CreatedAt specs.Cmp[entmodel.Product, time.Time]
}

var Product_ = specs.Metamodel[entmodel.Product, ProductAttrs]()

type ProductRepo = crud.Repo[entmodel.Product, int64, ProductUpdate]

var ProductRepository = sqlrepo.Define[entmodel.Product, int64, ProductUpdate]("")

func NewProductRepository(src crud.Source) *ProductRepo {
	return ProductRepository.Bind(src)
}

func init() {
	port.MustCoverUpdate[entmodel.Product, ProductUpdate]("CreatedAt")
}
