// Code generated by rxcrud. DO NOT EDIT.

package gormstore

import (
	"gorm.io/gorm"
	"rx-crud/crud"
	"rx-crud/repo/decorators/specs"
	"time"
)

// LabelUpdate is the partial-update DTO for Label.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type LabelUpdate struct {
	Slug *string `json:"slug,omitempty"`
}

// LabelAttrs is the generated metamodel shape for Label.
type LabelAttrs struct {
	ID        specs.Ord[Label, uint]
	CreatedAt specs.Cmp[Label, time.Time]
	UpdatedAt specs.Cmp[Label, time.Time]
	DeletedAt specs.Attr[Label, gorm.DeletedAt]
	Slug      specs.Str[Label]
}

// Label_ is the metamodel of Label: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Label_ = specs.Metamodel[Label, LabelAttrs]()

// MemberUpdate is the partial-update DTO for Member.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type MemberUpdate struct {
	TeamID *uint         `json:"teamID,omitempty"`
	Name   *string       `json:"name,omitempty"`
	Age    crud.Opt[int] `json:"age,omitzero"`
}

// MemberTeamAttrs reaches Member through Team.
type MemberTeamAttrs struct {
	ID        specs.Ord[Member, uint]
	CreatedAt specs.Cmp[Member, time.Time]
	UpdatedAt specs.Cmp[Member, time.Time]
	DeletedAt specs.Attr[Member, gorm.DeletedAt]
	Name      specs.Str[Member]
}

// MemberAttrs is the generated metamodel shape for Member.
type MemberAttrs struct {
	ID        specs.Ord[Member, uint]
	CreatedAt specs.Cmp[Member, time.Time]
	UpdatedAt specs.Cmp[Member, time.Time]
	DeletedAt specs.Attr[Member, gorm.DeletedAt]
	TeamID    specs.Ord[Member, uint]
	Name      specs.Str[Member]
	Age       specs.Ord[Member, int]
	Team      MemberTeamAttrs
}

// Member_ is the metamodel of Member: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Member_ = specs.Metamodel[Member, MemberAttrs]()

// TeamUpdate is the partial-update DTO for Team.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type TeamUpdate struct {
	Name *string `json:"name,omitempty"`
}

// TeamMembersAttrs reaches Team through Members.
type TeamMembersAttrs struct {
	ID        specs.Ord[Team, uint]
	CreatedAt specs.Cmp[Team, time.Time]
	UpdatedAt specs.Cmp[Team, time.Time]
	DeletedAt specs.Attr[Team, gorm.DeletedAt]
	TeamID    specs.Ord[Team, uint]
	Name      specs.Str[Team]
	Age       specs.Ord[Team, int]
}

// TeamLabelsAttrs reaches Team through Labels.
type TeamLabelsAttrs struct {
	ID        specs.Ord[Team, uint]
	CreatedAt specs.Cmp[Team, time.Time]
	UpdatedAt specs.Cmp[Team, time.Time]
	DeletedAt specs.Attr[Team, gorm.DeletedAt]
	Slug      specs.Str[Team]
}

// TeamAttrs is the generated metamodel shape for Team.
type TeamAttrs struct {
	ID        specs.Ord[Team, uint]
	CreatedAt specs.Cmp[Team, time.Time]
	UpdatedAt specs.Cmp[Team, time.Time]
	DeletedAt specs.Attr[Team, gorm.DeletedAt]
	Name      specs.Str[Team]
	Members   TeamMembersAttrs
	Labels    TeamLabelsAttrs
}

// Team_ is the metamodel of Team: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Team_ = specs.Metamodel[Team, TeamAttrs]()
