// Code generated by vv. DO NOT EDIT.

package access

import (
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/port"
	"github.com/frostgrove/vv/utils"
	uuid "github.com/google/uuid"
	"time"
)

type CredentialUpdate struct {
	SubjectType *string    `json:"subjectType,omitempty"`
	SubjectID   *uuid.UUID `json:"subjectID,omitempty"`
	Provider    *string    `json:"provider,omitempty"`
	Identifier  *string    `json:"identifier,omitempty"`
	SecretHash  *string    `json:"secretHash,omitempty"`
}

type CredentialAttrs struct {
	ID          specs.Attr[Credential, uuid.UUID]
	SubjectType specs.Str[Credential]
	SubjectID   specs.Attr[Credential, uuid.UUID]
	Provider    specs.Str[Credential]
	Identifier  specs.Str[Credential]
	SecretHash  specs.Str[Credential]
	CreatedAt   specs.Cmp[Credential, time.Time]
	UpdatedAt   specs.Cmp[Credential, time.Time]
}

var Credential_ = specs.Metamodel[Credential, CredentialAttrs]()

type CredentialRepo = crud.Repo[Credential, uuid.UUID, CredentialUpdate]

var CredentialRepository = sqlrepo.Define[Credential, uuid.UUID, CredentialUpdate]("")

func NewCredentialRepository(src crud.Source) *CredentialRepo {
	return CredentialRepository.Bind(src)
}

type PermissionUpdate struct {
	Code   *string `json:"code,omitempty"`
	Name   *string `json:"name,omitempty"`
	Module *string `json:"module,omitempty"`
}

type PermissionAttrs struct {
	ID        specs.Attr[Permission, uuid.UUID]
	Code      specs.Str[Permission]
	Name      specs.Str[Permission]
	Module    specs.Str[Permission]
	CreatedAt specs.Cmp[Permission, time.Time]
}

var Permission_ = specs.Metamodel[Permission, PermissionAttrs]()

type PermissionRepo = crud.Repo[Permission, uuid.UUID, PermissionUpdate]

var PermissionRepository = sqlrepo.Define[Permission, uuid.UUID, PermissionUpdate]("")

func NewPermissionRepository(src crud.Source) *PermissionRepo {
	return PermissionRepository.Bind(src)
}

type RoleUpdate struct {
	Slug *string `json:"slug,omitempty"`
	Name *string `json:"name,omitempty"`
}

type RolePermissionsAttrs struct {
	specs.Rel[Role, Permission]
	ID        specs.Attr[Role, uuid.UUID]
	Code      specs.Str[Role]
	Name      specs.Str[Role]
	Module    specs.Str[Role]
	CreatedAt specs.Cmp[Role, time.Time]
}

type RoleAttrs struct {
	ID          specs.Attr[Role, uuid.UUID]
	Slug        specs.Str[Role]
	Name        specs.Str[Role]
	IsSystem    specs.Attr[Role, bool]
	CreatedAt   specs.Cmp[Role, time.Time]
	Permissions RolePermissionsAttrs
}

var Role_ = specs.Metamodel[Role, RoleAttrs]()

type RoleRepo = crud.Repo[Role, uuid.UUID, RoleUpdate]

var RoleRepository = sqlrepo.Define[Role, uuid.UUID, RoleUpdate]("")

func NewRoleRepository(src crud.Source) *RoleRepo {
	return RoleRepository.Bind(src)
}

type RolePermissionUpdate struct {
	RoleID       *uuid.UUID `json:"roleID,omitempty"`
	PermissionID *uuid.UUID `json:"permissionID,omitempty"`
}

type RolePermissionAttrs struct {
	ID           specs.Attr[RolePermission, uuid.UUID]
	RoleID       specs.Attr[RolePermission, uuid.UUID]
	PermissionID specs.Attr[RolePermission, uuid.UUID]
}

var RolePermission_ = specs.Metamodel[RolePermission, RolePermissionAttrs]()

type RolePermissionRepo = crud.Repo[RolePermission, uuid.UUID, RolePermissionUpdate]

var RolePermissionRepository = sqlrepo.Define[RolePermission, uuid.UUID, RolePermissionUpdate]("")

func NewRolePermissionRepository(src crud.Source) *RolePermissionRepo {
	return RolePermissionRepository.Bind(src)
}

type SessionUpdate struct {
	SubjectType   *string              `json:"subjectType,omitempty"`
	SubjectID     *uuid.UUID           `json:"subjectID,omitempty"`
	TokenHash     *string              `json:"tokenHash,omitempty"`
	UserAgent     *string              `json:"userAgent,omitempty"`
	IP            *string              `json:"ip,omitempty"`
	LastUsedAt    *time.Time           `json:"lastUsedAt,omitempty"`
	ExpiresAt     *time.Time           `json:"expiresAt,omitempty"`
	RevokedAt     utils.Opt[time.Time] `json:"revokedAt,omitzero"`
	RevokedReason *string              `json:"revokedReason,omitempty"`
}

type SessionAttrs struct {
	ID            specs.Attr[Session, uuid.UUID]
	SubjectType   specs.Str[Session]
	SubjectID     specs.Attr[Session, uuid.UUID]
	TokenHash     specs.Str[Session]
	UserAgent     specs.Str[Session]
	IP            specs.Str[Session]
	CreatedAt     specs.Cmp[Session, time.Time]
	LastUsedAt    specs.Cmp[Session, time.Time]
	ExpiresAt     specs.Cmp[Session, time.Time]
	RevokedAt     specs.Cmp[Session, time.Time]
	RevokedReason specs.Str[Session]
}

var Session_ = specs.Metamodel[Session, SessionAttrs]()

type SessionRepo = crud.Repo[Session, uuid.UUID, SessionUpdate]

var SessionRepository = sqlrepo.Define[Session, uuid.UUID, SessionUpdate]("")

func NewSessionRepository(src crud.Source) *SessionRepo {
	return SessionRepository.Bind(src)
}

type SubjectDefaultRoleUpdate struct {
	SubjectType *string    `json:"subjectType,omitempty"`
	RoleID      *uuid.UUID `json:"roleID,omitempty"`
}

type SubjectDefaultRoleRoleAttrs struct {
	specs.Rel[SubjectDefaultRole, Role]
	ID        specs.Attr[SubjectDefaultRole, uuid.UUID]
	Slug      specs.Str[SubjectDefaultRole]
	Name      specs.Str[SubjectDefaultRole]
	IsSystem  specs.Attr[SubjectDefaultRole, bool]
	CreatedAt specs.Cmp[SubjectDefaultRole, time.Time]
}

type SubjectDefaultRoleAttrs struct {
	ID          specs.Attr[SubjectDefaultRole, uuid.UUID]
	SubjectType specs.Str[SubjectDefaultRole]
	RoleID      specs.Attr[SubjectDefaultRole, uuid.UUID]
	UpdatedAt   specs.Cmp[SubjectDefaultRole, time.Time]
	Role        SubjectDefaultRoleRoleAttrs
}

var SubjectDefaultRole_ = specs.Metamodel[SubjectDefaultRole, SubjectDefaultRoleAttrs]()

type SubjectDefaultRoleRepo = crud.Repo[SubjectDefaultRole, uuid.UUID, SubjectDefaultRoleUpdate]

var SubjectDefaultRoleRepository = sqlrepo.Define[SubjectDefaultRole, uuid.UUID, SubjectDefaultRoleUpdate]("")

func NewSubjectDefaultRoleRepository(src crud.Source) *SubjectDefaultRoleRepo {
	return SubjectDefaultRoleRepository.Bind(src)
}

type SubjectPermissionUpdate struct {
	SubjectType  *string    `json:"subjectType,omitempty"`
	SubjectID    *uuid.UUID `json:"subjectID,omitempty"`
	PermissionID *uuid.UUID `json:"permissionID,omitempty"`
}

type SubjectPermissionPermissionAttrs struct {
	specs.Rel[SubjectPermission, Permission]
	ID        specs.Attr[SubjectPermission, uuid.UUID]
	Code      specs.Str[SubjectPermission]
	Name      specs.Str[SubjectPermission]
	Module    specs.Str[SubjectPermission]
	CreatedAt specs.Cmp[SubjectPermission, time.Time]
}

type SubjectPermissionAttrs struct {
	ID           specs.Attr[SubjectPermission, uuid.UUID]
	SubjectType  specs.Str[SubjectPermission]
	SubjectID    specs.Attr[SubjectPermission, uuid.UUID]
	PermissionID specs.Attr[SubjectPermission, uuid.UUID]
	GrantedAt    specs.Cmp[SubjectPermission, time.Time]
	Permission   SubjectPermissionPermissionAttrs
}

var SubjectPermission_ = specs.Metamodel[SubjectPermission, SubjectPermissionAttrs]()

type SubjectPermissionRepo = crud.Repo[SubjectPermission, uuid.UUID, SubjectPermissionUpdate]

var SubjectPermissionRepository = sqlrepo.Define[SubjectPermission, uuid.UUID, SubjectPermissionUpdate]("")

func NewSubjectPermissionRepository(src crud.Source) *SubjectPermissionRepo {
	return SubjectPermissionRepository.Bind(src)
}

type SubjectRoleUpdate struct {
	SubjectType *string    `json:"subjectType,omitempty"`
	SubjectID   *uuid.UUID `json:"subjectID,omitempty"`
	RoleID      *uuid.UUID `json:"roleID,omitempty"`
}

type SubjectRoleRoleAttrs struct {
	specs.Rel[SubjectRole, Role]
	ID        specs.Attr[SubjectRole, uuid.UUID]
	Slug      specs.Str[SubjectRole]
	Name      specs.Str[SubjectRole]
	IsSystem  specs.Attr[SubjectRole, bool]
	CreatedAt specs.Cmp[SubjectRole, time.Time]
}

type SubjectRoleAttrs struct {
	ID          specs.Attr[SubjectRole, uuid.UUID]
	SubjectType specs.Str[SubjectRole]
	SubjectID   specs.Attr[SubjectRole, uuid.UUID]
	RoleID      specs.Attr[SubjectRole, uuid.UUID]
	GrantedAt   specs.Cmp[SubjectRole, time.Time]
	Role        SubjectRoleRoleAttrs
}

var SubjectRole_ = specs.Metamodel[SubjectRole, SubjectRoleAttrs]()

type SubjectRoleRepo = crud.Repo[SubjectRole, uuid.UUID, SubjectRoleUpdate]

var SubjectRoleRepository = sqlrepo.Define[SubjectRole, uuid.UUID, SubjectRoleUpdate]("")

func NewSubjectRoleRepository(src crud.Source) *SubjectRoleRepo {
	return SubjectRoleRepository.Bind(src)
}

func init() {
	port.MustCoverUpdate[Credential, CredentialUpdate]()
	port.MustCoverUpdate[Permission, PermissionUpdate]()
	port.MustCoverUpdate[Role, RoleUpdate]()
	port.MustCoverUpdate[RolePermission, RolePermissionUpdate]()
	port.MustCoverUpdate[Session, SessionUpdate]()
	port.MustCoverUpdate[SubjectDefaultRole, SubjectDefaultRoleUpdate]()
	port.MustCoverUpdate[SubjectPermission, SubjectPermissionUpdate]()
	port.MustCoverUpdate[SubjectRole, SubjectRoleUpdate]()
}
