// Code generated by vv. DO NOT EDIT.

package access

import (
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/port"
	"github.com/frostgrove/vv/utils"
	"github.com/google/uuid"
	"time"
)

// CredentialUpdate is the partial-update DTO for Credential.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type CredentialUpdate struct {
	SubjectType *string    `json:"subjectType,omitempty"`
	SubjectID   *uuid.UUID `json:"subjectID,omitempty"`
	Provider    *string    `json:"provider,omitempty"`
	Identifier  *string    `json:"identifier,omitempty"`
	SecretHash  *string    `json:"secretHash,omitempty"`
}

// CredentialAttrs is the generated metamodel shape for Credential.
type CredentialAttrs struct {
	ID          specs.Attr[Credential, uuid.UUID]
	SubjectType specs.Str[Credential]
	SubjectID   specs.Attr[Credential, uuid.UUID]
	Provider    specs.Str[Credential]
	Identifier  specs.Str[Credential]
	SecretHash  specs.Str[Credential]
	CreatedAt   specs.Cmp[Credential, time.Time]
	UpdatedAt   specs.Cmp[Credential, time.Time]
}

// Credential_ is the metamodel of Credential: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Credential_ = specs.Metamodel[Credential, CredentialAttrs]()

// CredentialRepo is the typed repository for Credential.
type CredentialRepo = crud.Repo[Credential, uuid.UUID, CredentialUpdate]

// CredentialRepository describes Credential independently of a database driver.
// Bind it through NewCredentialRepository with the application's datasource.
var CredentialRepository = sqlrepo.Define[Credential, uuid.UUID, CredentialUpdate]("")

// NewCredentialRepository binds CredentialRepository to src.
func NewCredentialRepository(src crud.Source) *CredentialRepo {
	return CredentialRepository.Bind(src)
}

// PermissionUpdate is the partial-update DTO for Permission.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type PermissionUpdate struct {
	Code   *string `json:"code,omitempty"`
	Name   *string `json:"name,omitempty"`
	Module *string `json:"module,omitempty"`
}

// PermissionAttrs is the generated metamodel shape for Permission.
type PermissionAttrs struct {
	ID        specs.Attr[Permission, uuid.UUID]
	Code      specs.Str[Permission]
	Name      specs.Str[Permission]
	Module    specs.Str[Permission]
	CreatedAt specs.Cmp[Permission, time.Time]
}

// Permission_ is the metamodel of Permission: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Permission_ = specs.Metamodel[Permission, PermissionAttrs]()

// PermissionRepo is the typed repository for Permission.
type PermissionRepo = crud.Repo[Permission, uuid.UUID, PermissionUpdate]

// PermissionRepository describes Permission independently of a database driver.
// Bind it through NewPermissionRepository with the application's datasource.
var PermissionRepository = sqlrepo.Define[Permission, uuid.UUID, PermissionUpdate]("")

// NewPermissionRepository binds PermissionRepository to src.
func NewPermissionRepository(src crud.Source) *PermissionRepo {
	return PermissionRepository.Bind(src)
}

// RoleUpdate is the partial-update DTO for Role.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type RoleUpdate struct {
	Slug *string `json:"slug,omitempty"`
	Name *string `json:"name,omitempty"`
}

// RolePermissionsAttrs reaches Role through Permissions.
type RolePermissionsAttrs struct {
	specs.Rel[Role, Permission]
	ID        specs.Attr[Role, uuid.UUID]
	Code      specs.Str[Role]
	Name      specs.Str[Role]
	Module    specs.Str[Role]
	CreatedAt specs.Cmp[Role, time.Time]
}

// RoleAttrs is the generated metamodel shape for Role.
type RoleAttrs struct {
	ID          specs.Attr[Role, uuid.UUID]
	Slug        specs.Str[Role]
	Name        specs.Str[Role]
	IsSystem    specs.Attr[Role, bool]
	CreatedAt   specs.Cmp[Role, time.Time]
	Permissions RolePermissionsAttrs
}

// Role_ is the metamodel of Role: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Role_ = specs.Metamodel[Role, RoleAttrs]()

// RoleRepo is the typed repository for Role.
type RoleRepo = crud.Repo[Role, uuid.UUID, RoleUpdate]

// RoleRepository describes Role independently of a database driver.
// Bind it through NewRoleRepository with the application's datasource.
var RoleRepository = sqlrepo.Define[Role, uuid.UUID, RoleUpdate]("")

// NewRoleRepository binds RoleRepository to src.
func NewRoleRepository(src crud.Source) *RoleRepo {
	return RoleRepository.Bind(src)
}

// RolePermissionUpdate is the partial-update DTO for RolePermission.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type RolePermissionUpdate struct {
	RoleID       *uuid.UUID `json:"roleID,omitempty"`
	PermissionID *uuid.UUID `json:"permissionID,omitempty"`
}

// RolePermissionAttrs is the generated metamodel shape for RolePermission.
type RolePermissionAttrs struct {
	ID           specs.Attr[RolePermission, uuid.UUID]
	RoleID       specs.Attr[RolePermission, uuid.UUID]
	PermissionID specs.Attr[RolePermission, uuid.UUID]
}

// RolePermission_ is the metamodel of RolePermission: typed, path-aware field references.
// It is validated against the model at package initialisation.
var RolePermission_ = specs.Metamodel[RolePermission, RolePermissionAttrs]()

// RolePermissionRepo is the typed repository for RolePermission.
type RolePermissionRepo = crud.Repo[RolePermission, uuid.UUID, RolePermissionUpdate]

// RolePermissionRepository describes RolePermission independently of a database driver.
// Bind it through NewRolePermissionRepository with the application's datasource.
var RolePermissionRepository = sqlrepo.Define[RolePermission, uuid.UUID, RolePermissionUpdate]("")

// NewRolePermissionRepository binds RolePermissionRepository to src.
func NewRolePermissionRepository(src crud.Source) *RolePermissionRepo {
	return RolePermissionRepository.Bind(src)
}

// SessionUpdate is the partial-update DTO for Session.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type SessionUpdate struct {
	SubjectType   *string              `json:"subjectType,omitempty"`
	SubjectID     *uuid.UUID           `json:"subjectID,omitempty"`
	TokenHash     *string              `json:"tokenHash,omitempty"`
	UserAgent     *string              `json:"userAgent,omitempty"`
	IP            *string              `json:"ip,omitempty"`
	LastUsedAt    *time.Time           `json:"lastUsedAt,omitempty"`
	ExpiresAt     *time.Time           `json:"expiresAt,omitempty"`
	RevokedAt     utils.Opt[time.Time] `json:"revokedAt,omitzero"`
	RevokedReason *string              `json:"revokedReason,omitempty"`
}

// SessionAttrs is the generated metamodel shape for Session.
type SessionAttrs struct {
	ID            specs.Attr[Session, uuid.UUID]
	SubjectType   specs.Str[Session]
	SubjectID     specs.Attr[Session, uuid.UUID]
	TokenHash     specs.Str[Session]
	UserAgent     specs.Str[Session]
	IP            specs.Str[Session]
	CreatedAt     specs.Cmp[Session, time.Time]
	LastUsedAt    specs.Cmp[Session, time.Time]
	ExpiresAt     specs.Cmp[Session, time.Time]
	RevokedAt     specs.Cmp[Session, time.Time]
	RevokedReason specs.Str[Session]
}

// Session_ is the metamodel of Session: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Session_ = specs.Metamodel[Session, SessionAttrs]()

// SessionRepo is the typed repository for Session.
type SessionRepo = crud.Repo[Session, uuid.UUID, SessionUpdate]

// SessionRepository describes Session independently of a database driver.
// Bind it through NewSessionRepository with the application's datasource.
var SessionRepository = sqlrepo.Define[Session, uuid.UUID, SessionUpdate]("")

// NewSessionRepository binds SessionRepository to src.
func NewSessionRepository(src crud.Source) *SessionRepo {
	return SessionRepository.Bind(src)
}

// SubjectDefaultRoleUpdate is the partial-update DTO for SubjectDefaultRole.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type SubjectDefaultRoleUpdate struct {
	SubjectType *string    `json:"subjectType,omitempty"`
	RoleID      *uuid.UUID `json:"roleID,omitempty"`
}

// SubjectDefaultRoleRoleAttrs reaches SubjectDefaultRole through Role.
type SubjectDefaultRoleRoleAttrs struct {
	specs.Rel[SubjectDefaultRole, Role]
	ID        specs.Attr[SubjectDefaultRole, uuid.UUID]
	Slug      specs.Str[SubjectDefaultRole]
	Name      specs.Str[SubjectDefaultRole]
	IsSystem  specs.Attr[SubjectDefaultRole, bool]
	CreatedAt specs.Cmp[SubjectDefaultRole, time.Time]
}

// SubjectDefaultRoleAttrs is the generated metamodel shape for SubjectDefaultRole.
type SubjectDefaultRoleAttrs struct {
	ID          specs.Attr[SubjectDefaultRole, uuid.UUID]
	SubjectType specs.Str[SubjectDefaultRole]
	RoleID      specs.Attr[SubjectDefaultRole, uuid.UUID]
	UpdatedAt   specs.Cmp[SubjectDefaultRole, time.Time]
	Role        SubjectDefaultRoleRoleAttrs
}

// SubjectDefaultRole_ is the metamodel of SubjectDefaultRole: typed, path-aware field references.
// It is validated against the model at package initialisation.
var SubjectDefaultRole_ = specs.Metamodel[SubjectDefaultRole, SubjectDefaultRoleAttrs]()

// SubjectDefaultRoleRepo is the typed repository for SubjectDefaultRole.
type SubjectDefaultRoleRepo = crud.Repo[SubjectDefaultRole, uuid.UUID, SubjectDefaultRoleUpdate]

// SubjectDefaultRoleRepository describes SubjectDefaultRole independently of a database driver.
// Bind it through NewSubjectDefaultRoleRepository with the application's datasource.
var SubjectDefaultRoleRepository = sqlrepo.Define[SubjectDefaultRole, uuid.UUID, SubjectDefaultRoleUpdate]("")

// NewSubjectDefaultRoleRepository binds SubjectDefaultRoleRepository to src.
func NewSubjectDefaultRoleRepository(src crud.Source) *SubjectDefaultRoleRepo {
	return SubjectDefaultRoleRepository.Bind(src)
}

// SubjectPermissionUpdate is the partial-update DTO for SubjectPermission.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type SubjectPermissionUpdate struct {
	SubjectType  *string    `json:"subjectType,omitempty"`
	SubjectID    *uuid.UUID `json:"subjectID,omitempty"`
	PermissionID *uuid.UUID `json:"permissionID,omitempty"`
}

// SubjectPermissionPermissionAttrs reaches SubjectPermission through Permission.
type SubjectPermissionPermissionAttrs struct {
	specs.Rel[SubjectPermission, Permission]
	ID        specs.Attr[SubjectPermission, uuid.UUID]
	Code      specs.Str[SubjectPermission]
	Name      specs.Str[SubjectPermission]
	Module    specs.Str[SubjectPermission]
	CreatedAt specs.Cmp[SubjectPermission, time.Time]
}

// SubjectPermissionAttrs is the generated metamodel shape for SubjectPermission.
type SubjectPermissionAttrs struct {
	ID           specs.Attr[SubjectPermission, uuid.UUID]
	SubjectType  specs.Str[SubjectPermission]
	SubjectID    specs.Attr[SubjectPermission, uuid.UUID]
	PermissionID specs.Attr[SubjectPermission, uuid.UUID]
	GrantedAt    specs.Cmp[SubjectPermission, time.Time]
	Permission   SubjectPermissionPermissionAttrs
}

// SubjectPermission_ is the metamodel of SubjectPermission: typed, path-aware field references.
// It is validated against the model at package initialisation.
var SubjectPermission_ = specs.Metamodel[SubjectPermission, SubjectPermissionAttrs]()

// SubjectPermissionRepo is the typed repository for SubjectPermission.
type SubjectPermissionRepo = crud.Repo[SubjectPermission, uuid.UUID, SubjectPermissionUpdate]

// SubjectPermissionRepository describes SubjectPermission independently of a database driver.
// Bind it through NewSubjectPermissionRepository with the application's datasource.
var SubjectPermissionRepository = sqlrepo.Define[SubjectPermission, uuid.UUID, SubjectPermissionUpdate]("")

// NewSubjectPermissionRepository binds SubjectPermissionRepository to src.
func NewSubjectPermissionRepository(src crud.Source) *SubjectPermissionRepo {
	return SubjectPermissionRepository.Bind(src)
}

// SubjectRoleUpdate is the partial-update DTO for SubjectRole.
// A pointer field is optional; a utils.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type SubjectRoleUpdate struct {
	SubjectType *string    `json:"subjectType,omitempty"`
	SubjectID   *uuid.UUID `json:"subjectID,omitempty"`
	RoleID      *uuid.UUID `json:"roleID,omitempty"`
}

// SubjectRoleRoleAttrs reaches SubjectRole through Role.
type SubjectRoleRoleAttrs struct {
	specs.Rel[SubjectRole, Role]
	ID        specs.Attr[SubjectRole, uuid.UUID]
	Slug      specs.Str[SubjectRole]
	Name      specs.Str[SubjectRole]
	IsSystem  specs.Attr[SubjectRole, bool]
	CreatedAt specs.Cmp[SubjectRole, time.Time]
}

// SubjectRoleAttrs is the generated metamodel shape for SubjectRole.
type SubjectRoleAttrs struct {
	ID          specs.Attr[SubjectRole, uuid.UUID]
	SubjectType specs.Str[SubjectRole]
	SubjectID   specs.Attr[SubjectRole, uuid.UUID]
	RoleID      specs.Attr[SubjectRole, uuid.UUID]
	GrantedAt   specs.Cmp[SubjectRole, time.Time]
	Role        SubjectRoleRoleAttrs
}

// SubjectRole_ is the metamodel of SubjectRole: typed, path-aware field references.
// It is validated against the model at package initialisation.
var SubjectRole_ = specs.Metamodel[SubjectRole, SubjectRoleAttrs]()

// SubjectRoleRepo is the typed repository for SubjectRole.
type SubjectRoleRepo = crud.Repo[SubjectRole, uuid.UUID, SubjectRoleUpdate]

// SubjectRoleRepository describes SubjectRole independently of a database driver.
// Bind it through NewSubjectRoleRepository with the application's datasource.
var SubjectRoleRepository = sqlrepo.Define[SubjectRole, uuid.UUID, SubjectRoleUpdate]("")

// NewSubjectRoleRepository binds SubjectRoleRepository to src.
func NewSubjectRoleRepository(src crud.Source) *SubjectRoleRepo {
	return SubjectRoleRepository.Bind(src)
}

// A writable column the update DTO does not name refuses to start, rather than
// becoming a column updates silently cannot reach ([[D-050]]). The generator
// read the model's source text and this reads the compiled struct, so the two
// can drift apart — and this is what says so when they do, with nothing
// regenerated.
func init() {
	port.MustCoverUpdate[Credential, CredentialUpdate]()
	port.MustCoverUpdate[Permission, PermissionUpdate]()
	port.MustCoverUpdate[Role, RoleUpdate]()
	port.MustCoverUpdate[RolePermission, RolePermissionUpdate]()
	port.MustCoverUpdate[Session, SessionUpdate]()
	port.MustCoverUpdate[SubjectDefaultRole, SubjectDefaultRoleUpdate]()
	port.MustCoverUpdate[SubjectPermission, SubjectPermissionUpdate]()
	port.MustCoverUpdate[SubjectRole, SubjectRoleUpdate]()
}
