package codegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by vv. DO NOT EDIT."

func (this *generator) render() ([]byte, error) {
	var body bytes.Buffer
	var u used

	for _, name := range this.order {
		m := this.models[name]
		if this.withDTO {
			s, mu := this.renderDTO(m)
			body.WriteString(s)
			u.also(mu)
		}
		if this.withMeta {
			s, mu := this.renderMetamodel(m)
			body.WriteString(s)
			u.also(mu)
		}
		if this.withRepo {
			s, mu, err := this.renderRepository(m)
			if err != nil {
				return nil, err
			}
			body.WriteString(s)
			u.also(mu)
		}
		if this.adapter {
			s, mu, err := this.renderAdapter(m)
			if err != nil {
				return nil, err
			}
			body.WriteString(s)
			u.also(mu)
		}
	}
	if this.withDTO {
		body.WriteString(this.renderCoverage())
		u.port = true
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n\npackage %s\n\n", generatedHeader, this.pkg)

	type generatedImport struct {
		alias string
		path  string
		bare  bool
	}
	byPath := map[string]generatedImport{}
	addImport := func(alias, path string, bare bool) error {
		if path == "" {
			return fmt.Errorf("generated import %s has an empty path", alias)
		}
		if previous, exists := byPath[path]; exists {
			if previous.alias != alias {
				return fmt.Errorf("generated import %q needs incompatible aliases %q and %q", path, previous.alias, alias)
			}
			return nil
		}
		byPath[path] = generatedImport{alias: alias, path: path, bare: bare}
		return nil
	}
	if u.context {
		if err := addImport("context", "context", true); err != nil {
			return nil, err
		}
	}
	if u.http {
		if err := addImport("http", "net/http", true); err != nil {
			return nil, err
		}
	}
	if u.time {
		if err := addImport("time", "time", true); err != nil {
			return nil, err
		}
	}
	if u.crud {
		if err := addImport("crud", this.crudPkg, this.crudPkg == DefaultCrudPkg); err != nil {
			return nil, err
		}
	}
	if u.utils {
		pkg := this.utilsPkg
		if pkg == "" {
			pkg = DefaultUtilsPkg
		}
		if err := addImport("utils", pkg, pkg == DefaultUtilsPkg); err != nil {
			return nil, err
		}
	}
	if u.errs {
		if err := addImport("errs", this.errsPkg, this.errsPkg == DefaultErrsPkg); err != nil {
			return nil, err
		}
	}
	if u.net {
		if err := addImport("crudnet", this.netPkg, this.netPkg == DefaultNetPkg); err != nil {
			return nil, err
		}
	}
	if u.port {
		if err := addImport("port", this.portPkg, this.portPkg == DefaultPortPkg); err != nil {
			return nil, err
		}
	}
	if u.specs {
		if err := addImport("specs", this.specsPkg, this.specsPkg == DefaultSpecsPkg); err != nil {
			return nil, err
		}
	}
	if u.sqlrepo {
		if err := addImport("sqlrepo", "github.com/frostgrove/vv/crud/sqlrepo", true); err != nil {
			return nil, err
		}
	}
	if this.modelImport != "" {
		if err := addImport(this.modelAlias, this.modelImport, false); err != nil {
			return nil, err
		}
	}
	// Anything else the model types reference has to come along too.
	for alias, path := range this.extraImports(body.String()) {
		if err := addImport(alias, path, false); err != nil {
			return nil, err
		}
	}
	imports := make([]string, 0, len(byPath))
	for _, item := range byPath {
		if item.bare {
			imports = append(imports, fmt.Sprintf("%q", item.path))
		} else {
			imports = append(imports, fmt.Sprintf("%s %q", item.alias, item.path))
		}
	}
	if len(imports) > 0 {
		sort.Strings(imports)
		out.WriteString("import (\n")
		for _, imp := range imports {
			fmt.Fprintf(&out, "\t%s\n", imp)
		}
		out.WriteString(")\n\n")
	}
	out.Write(body.Bytes())

	source, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated code does not parse: %w\n%s", err, out.String())
	}
	return source, nil
}

// used says which imports the rendered body needs. A flag per package rather
// than a scan of the output: the output is what the flags produce, so reading
// it back to decide would be one derivation checking itself.
type used struct{ crud, utils, specs, sqlrepo, time, port, errs, context, http, net bool }

func (this *used) also(o used) {
	this.crud = this.crud || o.crud
	this.utils = this.utils || o.utils
	this.specs = this.specs || o.specs
	this.sqlrepo = this.sqlrepo || o.sqlrepo
	this.time = this.time || o.time
	this.port = this.port || o.port
	this.errs = this.errs || o.errs
	this.context = this.context || o.context
	this.http = this.http || o.http
	this.net = this.net || o.net
}

// ---------------------------------------------------------------------------
// repository

// renderRepository emits the declaration every vv model needs, but deliberately
// does not choose a driver. The application binds it to database/sql, pgx,
// a test source, or any other vv Source at composition time.
func (this *generator) renderRepository(m *model) (string, used, error) {
	pk, ok := m.pk()
	if !ok {
		return "", used{}, fmt.Errorf("%s has no primary key: name it ID/Id or use db:\",pk\" for a non-conventional key", m.Name)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// %sRepo is the typed repository for %s.\n", m.Name, this.qual(m.Name))
	fmt.Fprintf(&b, "type %sRepo = crud.Repo[%s, %s, %sUpdate]\n\n", m.Name, this.qual(m.Name), pk.Type, m.Name)
	fmt.Fprintf(&b, "// %sRepository describes %s independently of a database driver.\n", m.Name, this.qual(m.Name))
	fmt.Fprintf(&b, "// Bind it through New%sRepository with the application's datasource.\n", m.Name)
	fmt.Fprintf(&b, "var %sRepository = sqlrepo.Define[%s, %s, %sUpdate](\"\")\n\n",
		m.Name, this.qual(m.Name), pk.Type, m.Name)
	fmt.Fprintf(&b, "// New%sRepository binds %sRepository to src.\n", m.Name, m.Name)
	fmt.Fprintf(&b, "func New%sRepository(src crud.Source) *%sRepo {\n", m.Name, m.Name)
	fmt.Fprintf(&b, "\treturn %sRepository.Bind(src)\n}\n\n", m.Name)
	return b.String(), used{crud: true, sqlrepo: true}, nil
}

// extraImports finds selectors that survived into the rendered declarations.
// Looking at the body rather than the source field's first token matters twice:
// wrappers such as crud.Opt are transformed away, while composite/generic types
// may carry several package qualifiers below their first node.
func (this *generator) extraImports(body string) map[string]string {
	need := map[string]string{}
	file, err := parser.ParseFile(token.NewFileSet(), "generated-body.go", "package generated\n"+body, 0)
	if err != nil {
		return need // the final format.Source call reports the full broken output.
	}
	ast.Inspect(file, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		pkg, ok := selector.X.(*ast.Ident)
		if !ok {
			return true
		}
		// parser object resolution links variables, parameters, fields and other
		// declarations to their identifiers. A package qualifier has no object in
		// this import-less synthetic file. This distinction matters for generated
		// adapter locals such as out.ID: a source import once called `out` must not
		// be resurrected merely because that local selector survived rendering.
		if pkg.Obj != nil {
			return true
		}
		if path, known := this.imports[pkg.Name]; known {
			need[pkg.Name] = path
		}
		return true
	})
	return need
}

// ---------------------------------------------------------------------------
// update DTO

func (this *generator) renderDTO(m *model) (string, used) {
	var b strings.Builder
	var u used

	fmt.Fprintf(&b, "// %sUpdate is the partial-update DTO for %s.\n", m.Name, this.qual(m.Name))
	fmt.Fprintf(&b, "// A pointer field is optional; a utils.Opt field is optional and nullable,\n")
	fmt.Fprintf(&b, "// so an absent key, an explicit null and a value stay three different things.\n")
	fmt.Fprintf(&b, "type %sUpdate struct {\n", m.Name)

	for _, f := range m.Fields {
		// The version column is left out for the same reason the primary key is:
		// the repository owns it. A DTO that names it is refused at Define time,
		// so emitting it would hand the caller a package that panics at start-up.
		if f.Skip || f.isRelation() || f.PK || f.Generated || f.Immutable || f.Version {
			continue
		}
		typ := dtoType(f.Type)
		json := lowerFirst(f.Name)
		omit := "omitempty"
		if strings.HasPrefix(typ, "utils.Opt[") {
			omit = "omitzero"
			u.utils = true
		}
		if strings.Contains(typ, "time.Time") {
			u.time = true
		}
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", f.Name, typ, json+","+omit)
	}
	b.WriteString("}\n\n")
	return b.String(), u
}

// ---------------------------------------------------------------------------
// metamodel

func (this *generator) renderMetamodel(m *model) (string, used) {
	var b strings.Builder
	var u used
	u.specs = true

	emitted := map[string]bool{}
	this.renderAttrs(&b, m, m, "", 0, []string{m.Name}, emitted, &u)

	fmt.Fprintf(&b, "// %s_ is the metamodel of %s: typed, path-aware field references.\n", m.Name, m.Name)
	fmt.Fprintf(&b, "// It is validated against the model at package initialisation.\n")
	fmt.Fprintf(&b, "var %s_ = specs.Metamodel[%s, %sAttrs]()\n\n", m.Name, this.qual(m.Name), m.Name)
	return b.String(), u
}

// renderAttrs writes the attribute struct for `on`, expressed as attributes of
// the root model, and recurses into relations up to the configured depth.
func (this *generator) renderAttrs(b *strings.Builder, root, on *model, suffix string, level int, path []string, emitted map[string]bool, u *used) {
	typeName := root.Name + suffix + "Attrs"
	if emitted[typeName] {
		return
	}
	emitted[typeName] = true

	var nested []struct {
		field  field
		target *model
		suffix string
	}

	var body strings.Builder
	if suffix != "" {
		// The group's own path, as an identifier. Embedded rather than named so
		// the call site reads Article_.Comments.Path().
		fmt.Fprintf(&body, "\tspecs.Rel[%s, %s]\n", this.qual(root.Name), this.qual(on.Name))
	}
	// A column of the target called Path or String sits at depth zero and
	// shadows the promoted method, so the doc comment has to say which spelling
	// still works here.
	var shadows []string
	for _, f := range on.Fields {
		if f.Skip {
			continue
		}
		if suffix != "" && !f.isRelation() && (f.Name == "Path" || f.Name == "String") {
			shadows = append(shadows, f.Name)
		}
		if f.isRelation() {
			if level+1 >= this.depth {
				continue
			}
			target := f.RelTarget
			if target == "" {
				target, _ = relElem(f.Type)
				if this.modelAlias != "" {
					target = strings.TrimPrefix(target, this.modelAlias+".")
				}
			}
			tm, ok := this.models[target]
			if !ok {
				continue // the related model lives in another package
			}
			// Do not walk back into a model already on this path: Article ->
			// Author -> Articles -> … has no end.
			cycle := false
			for _, seen := range path {
				if seen == target {
					cycle = true
					break
				}
			}
			if cycle {
				continue
			}
			sub := suffix + f.Name
			fmt.Fprintf(&body, "\t%s %s%sAttrs\n", f.Name, root.Name, sub)
			nested = append(nested, struct {
				field  field
				target *model
				suffix string
			}{f, tm, sub})
			continue
		}
		if strings.Contains(f.Type, "time.Time") {
			u.time = true
		}
		fmt.Fprintf(&body, "\t%s %s\n", f.Name, attrType("specs", this.qual(root.Name), f.Type))
	}

	// Emit the nested structs first so the file reads top-down.
	for _, n := range nested {
		this.renderAttrs(b, root, n.target, n.suffix, level+1, append(path, n.target.Name), emitted, u)
	}

	if suffix == "" {
		fmt.Fprintf(b, "// %sAttrs is the generated metamodel shape for %s.\n", root.Name, root.Name)
	} else {
		fmt.Fprintf(b, "// %s reaches %s through %s.\n", typeName, root.Name,
			strings.Join(splitCamelPath(suffix), "."))
		if len(shadows) > 0 {
			fmt.Fprintf(b, "// %s has a column called %s, which shadows the promoted method of\n",
				on.Name, strings.Join(shadows, " and one called "))
			fmt.Fprintf(b, "// that name: spell this relation's path RelPath() here.\n")
		}
	}
	fmt.Fprintf(b, "type %s struct {\n%s}\n\n", typeName, body.String())
}

// splitCamelPath turns the concatenated suffix back into a readable path for
// the doc comment: "CommentsAuthor" -> ["Comments", "Author"].
func splitCamelPath(s string) []string {
	var out []string
	start := 0
	for i := 1; i < len(s); i++ {
		if s[i] >= 'A' && s[i] <= 'Z' {
			out = append(out, s[start:i])
			start = i
		}
	}
	return append(out, s[start:])
}
