// Code generated by vv. DO NOT EDIT.

package auditdeployment

import (
	vvmodule "github.com/frostgrove/vv/app/module"
)

var VVModule = vvmodule.MustDefine(vvmodule.Spec{
	Name:  "audit-deployment",
	Order: 410,
	Provide: []any{
		NewCatalogAdmin,
	},
})
