// Code generated by vv. DO NOT EDIT.

package main

import (
	"github.com/shardit-io/vv/crud"
	"github.com/shardit-io/vv/port"
	"github.com/shardit-io/vv/repo/decorators/specs"
	"time"
)

// ProductUpdate is the partial-update DTO for Product.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type ProductUpdate struct {
	Sku    *string       `json:"sku,omitempty"`
	Name   *string       `json:"name,omitempty"`
	Price  *int          `json:"price,omitempty"`
	Stock  crud.Opt[int] `json:"stock,omitzero"`
	Active *bool         `json:"active,omitempty"`
}

// ProductAttrs is the generated metamodel shape for Product.
type ProductAttrs struct {
	ID        specs.Ord[Product, int64]
	Sku       specs.Str[Product]
	Name      specs.Str[Product]
	Price     specs.Ord[Product, int]
	Stock     specs.Ord[Product, int]
	Active    specs.Attr[Product, bool]
	CreatedAt specs.Cmp[Product, time.Time]
}

// Product_ is the metamodel of Product: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Product_ = specs.Metamodel[Product, ProductAttrs]()

// A writable column the update DTO does not name refuses to start, rather than
// becoming a column updates silently cannot reach ([[D-050]]). The generator
// read the model's source text and this reads the compiled struct, so the two
// can drift apart — and this is what says so when they do, with nothing
// regenerated.
func init() {
	port.MustCoverUpdate[Product, ProductUpdate]()
}
