// Code generated by vv. DO NOT EDIT.

package versionstore

import (
	"context"
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/http/crudnet"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/errs"
	"github.com/frostgrove/vv/port"
	"net/http"
	"time"
)

type DocumentUpdate struct {
	OwnerID *int64  `json:"ownerID,omitempty"`
	Title   *string `json:"title,omitempty"`
	Body    *string `json:"body,omitempty"`
}

type DocumentAttrs struct {
	ID         specs.Ord[Document, int64]
	OwnerID    specs.Ord[Document, int64]
	Title      specs.Str[Document]
	Body       specs.Str[Document]
	Revision   specs.Ord[Document, int]
	Origin     specs.Str[Document]
	ArchivedAt specs.Cmp[Document, time.Time]
	CreatedAt  specs.Cmp[Document, time.Time]
}

var Document_ = specs.Metamodel[Document, DocumentAttrs]()

type DocumentRepo = crud.Repo[Document, int64, DocumentUpdate]

var DocumentRepository = sqlrepo.Define[Document, int64, DocumentUpdate]("")

func NewDocumentRepository(src crud.Source) *DocumentRepo {
	return DocumentRepository.Bind(src)
}

type DocumentInput struct {
	OwnerID int64  `json:"ownerID"`
	Title   string `json:"title"`
	Body    string `json:"body"`
	Origin  string `json:"origin"`
}

type DocumentMapper struct{}

func (DocumentMapper) Model(_ context.Context, in DocumentInput) (Document, error) {
	out := Document{}
	out.OwnerID = in.OwnerID
	out.Title = in.Title
	out.Body = in.Body
	out.Origin = in.Origin
	return out, nil
}

func (DocumentMapper) Resolve(p errs.Path) (errs.Path, bool) { return DocumentPaths.Resolve(p) }

var DocumentPaths = port.MustPathMap[Document](port.PathMap{
	"OwnerID": port.At("ownerID"),
	"Title":   port.At("title"),
	"Body":    port.At("body"),
	"Origin":  port.At("origin"),
}, "ArchivedAt", "ID")

type DocumentService struct {
	*port.DefaultService[Document, int64, DocumentUpdate]
}

var _ port.Service[Document, int64, DocumentUpdate] = (*DocumentService)(nil)

func NewDocumentService(repo port.Repository[Document, int64, DocumentUpdate], opts ...port.ServiceOption) *DocumentService {
	return &DocumentService{DefaultService: port.NewService(repo, opts...)}
}

func MountDocument(mux *http.ServeMux, prefix string, svc port.Service[Document, int64, DocumentUpdate], opts ...crudnet.Option[Document, int64, DocumentUpdate]) {
	crudnet.ServingFor(svc, DocumentMapper{}, opts...).Mount(mux, prefix)
}

func init() {
	port.MustCoverUpdate[Document, DocumentUpdate]("ArchivedAt")
}
