//go:build integration

package auditpg

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/frostgrove/vv/audit"
	"github.com/frostgrove/vv/audit/auditcrud"
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/adapter/crudsql"
	"github.com/frostgrove/vv/crud/decorators/security"
	"github.com/frostgrove/vv/crud/sqlrepo"
)

type liveAuditedDocument struct {
	ID        int64      `db:"id,pk,auto"`
	TenantID  int64      `db:"tenant_id,immutable"`
	Name      string     `db:"name"`
	DeletedAt *time.Time `db:"deleted_at,serverowned,tombstone"`
}

type liveAuditedDocumentUpdate struct {
	Name *string
}

type liveAuditCRUDContextKey uint8

const (
	liveAuditCRUDTenant liveAuditCRUDContextKey = iota + 1
	liveAuditCRUDAllowed
)

func TestPostgresAuditCRUDLifecycleIsAtomicAndReadableAfterRestart(t *testing.T) {
	dsn := requiredLiveDSN(t)
	suffix := strconv.FormatInt(time.Now().UnixNano(), 36)
	schema := Schema{Name: "auditpg_crud_" + suffix}
	database := openLiveDB(t, dsnWithApplicationName(t, dsn, "auditpg_crud_"+suffix), 4)
	defer database.Close()
	defer dropLiveSchema(t, dsn, schema)
	ctx := context.Background()
	source := crudsql.Postgres(database)
	deployment, err := NewDeployment(DeploymentSpec{
		Runtime: Spec{DB: database, Source: source, Schema: schema}, SchemaManagement: ManageSchema,
	})
	if err != nil {
		t.Fatal(err)
	}
	defer deployment.Close()
	if err := deployment.Prepare(ctx); err != nil {
		t.Fatal(err)
	}
	tableName := "audited_documents"
	table := quoteIdentifier(schema.Name) + "." + quoteIdentifier(tableName)
	if _, err := database.ExecContext(ctx, `CREATE TABLE `+table+` (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tenant_id bigint NOT NULL,
name text NOT NULL,
deleted_at timestamp with time zone
)`); err != nil {
		t.Fatal(err)
	}

	blueprint := sqlrepo.DefineInSchema[liveAuditedDocument, int64, liveAuditedDocumentUpdate](
		schema.Name, tableName, sqlrepo.IndependentTable(),
	)
	semantic, err := audit.HMACSemanticDigester("auditpg-crud-semantic", bytes.Repeat([]byte{51}, 32))
	if err != nil {
		t.Fatal(err)
	}
	identities, err := audit.HMACIdentityKeyring(audit.HMACIdentityKey{
		KeyID: "auditpg-crud-identity", Key: bytes.Repeat([]byte{52}, 32), Active: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	operationContext := audit.ContextFacts(audit.GeneratedOperationFact(audit.Public, audit.AsPlaintext))
	resource := audit.Define(audit.Policy[liveAuditedDocument, int64]{
		Model: blueprint.Meta(), Semantics: audit.Semantics(1, audit.PolicyGolden("auditpg.crud.document", strings.Repeat("15", 32))),
		Descriptor: audit.Descriptor{
			Resource: "auditpg.document", Owner: "auditpg.team", Purpose: "business.audit",
			Retention: "business.forever", Consequence: audit.Required, Context: operationContext,
		},
		Subject: audit.PlaintextSubject(func(id int64) string { return fmt.Sprintf("document:%d", id) }, audit.Public),
		Actions: audit.Actions(
			audit.EntityCreated,
			audit.EntityChanged,
			audit.EntitySoftDeleted,
			audit.EntityRestored,
		),
		Fields: audit.Fields[liveAuditedDocument](
			audit.Value[liveAuditedDocument]("TenantID", "tenant_id", audit.Int64(), audit.Public),
			audit.Value[liveAuditedDocument]("Name", "name", audit.Text(), audit.Public),
		),
	})
	catalog, err := audit.Compile(audit.CatalogSpec{
		ID: "auditpg.crud", Owner: "auditpg.team", Generation: 1,
		Retention: audit.RetentionRules(audit.KeepForever("business.forever")),
		Semantics: semantic.Description(), Identities: identities.ActiveDescription(), Integrity: audit.IntegrityOnly(),
	}, resource)
	if err != nil {
		t.Fatal(err)
	}
	catalogs, err := audit.Lineage(catalog)
	if err != nil {
		t.Fatal(err)
	}
	installAndActivateLiveCatalog(t, ctx, deployment, catalog, "crud-lifecycle-"+suffix)
	if err := deployment.VerifyCatalogs(ctx, catalogs.Manifests()); err != nil {
		t.Fatal(err)
	}
	store, err := New(Spec{DB: database, Source: source, Schema: schema})
	if err != nil {
		t.Fatal(err)
	}
	if err := store.Check(ctx); err != nil {
		t.Fatal(err)
	}
	backingID, logID := store.BackingID(), store.LogID()
	recorder := newLiveAuditCRUDRecorder(t, store, catalogs, semantic, identities)
	policy := security.Combine(
		security.ScopeField[liveAuditedDocument, int64]("TenantID", func(ctx context.Context) (any, error) {
			tenant, ok := ctx.Value(liveAuditCRUDTenant).(int64)
			if !ok || tenant == 0 {
				return nil, security.Denied(security.Read, "tenant is absent")
			}
			return tenant, nil
		}),
		security.Policy[liveAuditedDocument, int64]{Authorize: func(ctx context.Context, action security.Action) error {
			if allowed, _ := ctx.Value(liveAuditCRUDAllowed).(bool); !allowed {
				return security.Denied(action, "principal is denied")
			}
			return nil
		}},
	)
	repository := blueprint.Bind(source, auditcrud.Secured(recorder, resource, policy))
	allowed := context.WithValue(context.WithValue(ctx, liveAuditCRUDTenant, int64(41)), liveAuditCRUDAllowed, true)

	created, err := repository.Save(allowed, &liveAuditedDocument{TenantID: 41, Name: "draft"})
	if err != nil {
		t.Fatalf("audited create: %v", err)
	}
	if created.ID == 0 || created.TenantID != 41 || created.Name != "draft" || created.DeletedAt != nil {
		t.Fatalf("audited create returned %+v", created)
	}
	assertLiveAuditCRUDTransaction(t, database, schema, table, created.ID, "draft", false, 1, audit.EntityCreated)

	name := "published"
	updated, err := repository.Update(allowed, created.ID, liveAuditedDocumentUpdate{Name: &name})
	if err != nil {
		t.Fatalf("audited update: %v", err)
	}
	if updated.Name != name || updated.TenantID != 41 || updated.DeletedAt != nil {
		t.Fatalf("audited update returned %+v", updated)
	}
	assertLiveAuditCRUDTransaction(t, database, schema, table, created.ID, name, false, 2, audit.EntityChanged)

	deleted, err := repository.Delete(allowed, created.ID)
	if err != nil || deleted != 1 {
		t.Fatalf("audited soft delete = (%d, %v)", deleted, err)
	}
	assertLiveAuditCRUDTransaction(t, database, schema, table, created.ID, name, true, 3, audit.EntitySoftDeleted)

	restored, err, supported := crud.RestoreOf(repository.Unwrap(), allowed, created.ID)
	if !supported || err != nil || restored != 1 {
		t.Fatalf("audited restore = (%d, %v, supported=%v)", restored, err, supported)
	}
	assertLiveAuditCRUDTransaction(t, database, schema, table, created.ID, name, false, 4, audit.EntityRestored)
	visible, err := repository.GetByID(allowed, created.ID)
	if err != nil || visible.Name != name || visible.TenantID != 41 || visible.DeletedAt != nil {
		t.Fatalf("restored row = (%+v, %v)", visible, err)
	}

	denied := context.WithValue(context.WithValue(ctx, liveAuditCRUDTenant, int64(41)), liveAuditCRUDAllowed, false)
	beforeBusiness, beforeRevisions := liveAuditCRUDCounts(t, database, schema, table)
	if _, err := repository.Save(denied, &liveAuditedDocument{TenantID: 41, Name: "denied"}); !errors.Is(err, security.ErrForbidden) {
		t.Fatalf("denied create = %v, want forbidden", err)
	}
	assertLiveAuditCRUDCounts(t, database, schema, table, beforeBusiness, beforeRevisions, "denied")

	wrongDigest := bytes.Repeat([]byte{99}, 32)
	if _, err := database.ExecContext(ctx, `UPDATE `+quoteIdentifier(schema.Name)+`.settings SET active_digest=$1 WHERE singleton`, wrongDigest); err != nil {
		t.Fatal(err)
	}
	if _, err := repository.Save(allowed, &liveAuditedDocument{TenantID: 41, Name: "audit-must-rollback"}); err == nil {
		t.Fatal("audit store failure committed the business mutation")
	}
	assertLiveAuditCRUDCounts(t, database, schema, table, beforeBusiness, beforeRevisions, "audit-must-rollback")
	active := catalog.Ref()
	if _, err := database.ExecContext(ctx, `UPDATE `+quoteIdentifier(schema.Name)+`.settings SET active_digest=$1 WHERE singleton`, active.Digest[:]); err != nil {
		t.Fatal(err)
	}
	if err := store.Check(ctx); err != nil {
		t.Fatal(err)
	}
	if err := store.Close(); err != nil {
		t.Fatal(err)
	}

	freshStore, err := New(Spec{DB: database, Source: source, Schema: schema})
	if err != nil {
		t.Fatal(err)
	}
	defer freshStore.Close()
	if err := freshStore.Check(ctx); err != nil {
		t.Fatal(err)
	}
	if freshStore.BackingID() != backingID || freshStore.LogID() != logID {
		t.Fatalf("restart changed store identity: backing=%x/%x log=%x/%x", backingID, freshStore.BackingID(), logID, freshStore.LogID())
	}
	freshRecorder := newLiveAuditCRUDRecorder(t, freshStore, catalogs, semantic, identities)
	history := newLiveAuditCRUDHistory(t, freshStore, freshRecorder)
	page, err := resource.History(history).Subject(ctx, created.ID, audit.Query{
		Purpose: "history.read", Role: "auditor", Fields: audit.AllFields(), Context: audit.NoContext(),
		Direction: audit.OldestFirst, Limit: 10,
	})
	if err != nil {
		t.Fatal(err)
	}
	assertLiveAuditCRUDHistory(t, page, created.ID)
}

func newLiveAuditCRUDRecorder(t *testing.T, store *Store, catalogs *audit.CatalogSet, semantic audit.SemanticDigester, identities audit.IdentityKeyring) *audit.Recorder {
	t.Helper()
	resolver, err := audit.StaticContext(audit.Context{})
	if err != nil {
		t.Fatal(err)
	}
	recorder, err := audit.New(audit.Config{
		Catalogs: catalogs, Writer: store, Context: resolver, Semantics: semantic, Identities: identities,
	})
	if err != nil {
		t.Fatal(err)
	}
	return recorder
}

func newLiveAuditCRUDHistory(t *testing.T, store *Store, recorder *audit.Recorder) *audit.History {
	t.Helper()
	authority := audit.AccessAuthorityFunc(func(_ context.Context, request audit.AccessRequest) (audit.AccessDecision, error) {
		view := request.View()
		return audit.AllowAccess(request, audit.AccessGrantSpec{
			Roles: []audit.Reference{view.Query.Role}, Catalogs: view.Catalogs,
			Resources: view.Target.Resources, Actions: view.Query.Actions,
			Fields: view.Query.Fields.Fields, Context: view.Query.Context.Facts,
			Classifications: []audit.Classification{audit.Public}, Direction: view.Query.Direction,
			ExpiresAt:    time.Date(2100, 1, 1, 0, 0, 0, 0, time.UTC),
			MaxRevisions: view.Query.Limit, MaxPages: 1, MaxBytes: 1 << 20,
		})
	})
	history, err := audit.NewHistory(audit.HistoryConfig{
		Profile: audit.PublicOnePageDevelopmentAlpha, Recorder: recorder, Log: store, Access: authority,
	})
	if err != nil {
		t.Fatal(err)
	}
	return history
}

func assertLiveAuditCRUDTransaction(t *testing.T, database *sql.DB, schema Schema, table string, id int64, name string, deleted bool, revisions int, action audit.EntityAction) {
	t.Helper()
	var businessXID, revisionXID, storedName string
	var deletedAt sql.NullTime
	if err := database.QueryRowContext(context.Background(), `SELECT xmin::text, name, deleted_at FROM `+table+` WHERE id=$1`, id).Scan(&businessXID, &storedName, &deletedAt); err != nil {
		t.Fatal(err)
	}
	var storedAction string
	if err := database.QueryRowContext(context.Background(), `SELECT r.xmin::text, t.action
FROM `+quoteIdentifier(schema.Name)+`.revisions r
JOIN `+quoteIdentifier(schema.Name)+`.entity_transitions t ON t.revision_id=r.revision_id
ORDER BY r.position DESC LIMIT 1`).Scan(&revisionXID, &storedAction); err != nil {
		t.Fatal(err)
	}
	if businessXID == "" || businessXID != revisionXID {
		t.Fatalf("business/audit transaction IDs = %q/%q", businessXID, revisionXID)
	}
	if storedName != name || deletedAt.Valid != deleted || storedAction != string(action) {
		t.Fatalf("stored lifecycle = name:%q deleted:%v action:%q", storedName, deletedAt.Valid, storedAction)
	}
	var revisionCount, transitionCount, chainCount int
	if err := database.QueryRowContext(context.Background(), `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.revisions`).Scan(&revisionCount); err != nil {
		t.Fatal(err)
	}
	if err := database.QueryRowContext(context.Background(), `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.entity_transitions`).Scan(&transitionCount); err != nil {
		t.Fatal(err)
	}
	if err := database.QueryRowContext(context.Background(), `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.entity_chains`).Scan(&chainCount); err != nil {
		t.Fatal(err)
	}
	if revisionCount != revisions || transitionCount != revisions || chainCount != 1 {
		t.Fatalf("audit lifecycle counts = revisions:%d transitions:%d chains:%d", revisionCount, transitionCount, chainCount)
	}
}

func liveAuditCRUDCounts(t *testing.T, database *sql.DB, schema Schema, table string) (int, int) {
	t.Helper()
	var business, revisions int
	if err := database.QueryRowContext(context.Background(), `SELECT count(*) FROM `+table).Scan(&business); err != nil {
		t.Fatal(err)
	}
	if err := database.QueryRowContext(context.Background(), `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.revisions`).Scan(&revisions); err != nil {
		t.Fatal(err)
	}
	return business, revisions
}

func assertLiveAuditCRUDCounts(t *testing.T, database *sql.DB, schema Schema, table string, wantBusiness, wantRevisions int, absentName string) {
	t.Helper()
	business, revisions := liveAuditCRUDCounts(t, database, schema, table)
	var leaked int
	if err := database.QueryRowContext(context.Background(), `SELECT count(*) FROM `+table+` WHERE name=$1`, absentName).Scan(&leaked); err != nil {
		t.Fatal(err)
	}
	if business != wantBusiness || revisions != wantRevisions || leaked != 0 {
		t.Fatalf("failed mutation leaked state: business=%d/%d revisions=%d/%d named=%d", business, wantBusiness, revisions, wantRevisions, leaked)
	}
}

func assertLiveAuditCRUDHistory(t *testing.T, page audit.Page, id int64) {
	t.Helper()
	revisions := page.Revisions()
	want := []audit.Action{
		audit.Action(audit.EntityCreated),
		audit.Action(audit.EntityChanged),
		audit.Action(audit.EntitySoftDeleted),
		audit.Action(audit.EntityRestored),
	}
	got := make([]audit.Action, len(revisions))
	subject := fmt.Sprintf("document:%d", id)
	for index, revision := range revisions {
		if len(revision.Items) != 1 {
			t.Fatalf("history revision %d has %d items", index, len(revision.Items))
		}
		item := revision.Items[0]
		got[index] = item.Action
		if item.Subject.Knowledge != audit.FieldKnown || string(item.Subject.Canonical) != subject {
			t.Fatalf("history revision %d subject = %+v", index, item.Subject)
		}
	}
	if !slices.Equal(got, want) || page.HasMore() {
		t.Fatalf("history actions = %v, want %v, hasMore=%v", got, want, page.HasMore())
	}
}
