//go:build integration

package auditpg

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/frostgrove/vv/audit"
	"github.com/frostgrove/vv/audit/auditcrud"
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/adapter/crudsql"
	"github.com/frostgrove/vv/crud/decorators/security"
	"github.com/frostgrove/vv/errs"
	_ "github.com/jackc/pgx/v5/stdlib"
)

type liveOccurrence struct {
	Number string
	At     time.Time
}

type liveEntity struct {
	ID   int64  `db:"id,pk,auto"`
	Name string `db:"name"`
}

type livePatch struct {
	Name string `db:"name"`
}

type liveCore struct {
	meta   *crud.Meta
	source crud.Source
	table  string
}

func TestPostgresAlphaLifecycleAndAtomicCRUD(t *testing.T) {
	dsn := os.Getenv("FROSTGROVE_AUDITPG_TEST_DSN")
	if dsn == "" {
		t.Fatal("FROSTGROVE_AUDITPG_TEST_DSN is required for the live auditpg suite")
	}
	ctx := context.Background()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err := db.PingContext(ctx); err != nil {
		t.Fatal(err)
	}
	suffix := strconv.FormatInt(time.Now().UnixNano(), 36)
	schema := Schema{Name: "auditpg_it_" + suffix}
	businessTable := quoteIdentifier(schema.Name) + `.business_entities`
	defer func() {
		if _, err := db.ExecContext(context.Background(), `DROP SCHEMA IF EXISTS `+quoteIdentifier(schema.Name)+` CASCADE`); err != nil {
			t.Errorf("drop scratch schema: %v", err)
		}
	}()
	source := crudsql.Postgres(db)
	deployment, err := NewDeployment(DeploymentSpec{Runtime: Spec{DB: db, Source: source, Schema: schema}, SchemaManagement: ManageSchema})
	if err != nil {
		t.Fatal(err)
	}
	if deployment.BackingID() != (audit.BackingID{}) || deployment.LogID() != (audit.LogID{}) {
		t.Fatal("unprepared deployment exposed persisted identity")
	}
	if err := deployment.Prepare(ctx); err != nil {
		t.Fatal(err)
	}
	if _, err := db.ExecContext(ctx, `CREATE TABLE `+businessTable+` (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL)`); err != nil {
		t.Fatal(err)
	}
	semantic, err := audit.HMACSemanticDigester("semantic-live", bytes.Repeat([]byte{1}, 32))
	if err != nil {
		t.Fatal(err)
	}
	identities, err := audit.HMACIdentityKeyring(audit.HMACIdentityKey{KeyID: "identity-live", Key: bytes.Repeat([]byte{2}, 32), Active: true})
	if err != nil {
		t.Fatal(err)
	}
	explicitContext := audit.ContextFacts(audit.OperationFact(audit.ContextRequired, audit.Provenances(audit.Verified), audit.Internal, audit.AsPlaintext))
	event := audit.Declare(audit.EventPolicy[liveOccurrence]{
		Semantics: audit.Semantics(1, audit.PolicyGolden("live.event", strings.Repeat("03", 32))),
		Descriptor: audit.Descriptor{
			Resource: "live.invoice", Action: "live.invoice.sent", Owner: "live.team", Purpose: "business.audit",
			Retention: "business.forever", Consequence: audit.Required, Context: explicitContext,
		},
		Target:     audit.NoEventTarget[liveOccurrence](),
		Outcome:    audit.EventOutcome(audit.Outcomes("sent"), func(liveOccurrence) audit.Outcome { return "sent" }),
		OccurredAt: audit.EventOccurredAt(func(value liveOccurrence) time.Time { return value.At }),
		Fields: audit.EventFields(
			audit.EventValue("invoice_number", func(value liveOccurrence) string { return value.Number }, audit.Text(), audit.Public),
		),
	})
	meta, err := crud.NewMetaInSchema[liveEntity](schema.Name, "business_entities")
	if err != nil {
		t.Fatal(err)
	}
	generatedContext := audit.ContextFacts(audit.GeneratedOperationFact(audit.Internal, audit.AsPlaintext))
	resource := audit.Define(audit.Policy[liveEntity, int64]{
		Model: meta, Semantics: audit.Semantics(1, audit.PolicyGolden("live.entity", strings.Repeat("04", 32))),
		Descriptor: audit.Descriptor{
			Resource: "live.entity", Owner: "live.team", Purpose: "business.audit",
			Retention: "business.forever", Consequence: audit.Required, Context: generatedContext,
		},
		Subject: audit.PlaintextSubject(func(id int64) string { return fmt.Sprintf("entity:%d", id) }, audit.Internal),
		Actions: audit.Actions(audit.EntityCreated, audit.EntityChanged, audit.EntityHardDeleted),
		Fields: audit.Fields[liveEntity](
			audit.Value[liveEntity]("Name", "name", audit.Text(), audit.Internal),
		),
	})
	resourceOperation := audit.DeclareOperation(audit.OperationPolicy{
		Name: "live.entity.mutate", Semantics: audit.Semantics(1), Retention: "business.forever",
		Consequence: audit.Required, Context: generatedContext,
		Members: audit.OperationMembers(
			resource.Action(audit.EntityCreated), resource.Action(audit.EntityChanged), resource.Action(audit.EntityHardDeleted),
		),
	})
	catalogSpec := audit.CatalogSpec{
		ID: "live.audit", Owner: "live.team", Generation: 1,
		Retention: audit.RetentionRules(audit.KeepForever("business.forever")),
		Semantics: semantic.Description(), Identities: identities.ActiveDescription(), Integrity: audit.IntegrityOnly(),
	}
	if _, eventErr := audit.Compile(catalogSpec, event); eventErr != nil {
		t.Fatalf("event-only catalog: %v", eventErr)
	}
	if _, resourceErr := audit.Compile(catalogSpec, resource, resourceOperation); resourceErr != nil {
		var fault *errs.Fault
		_ = errors.As(resourceErr, &fault)
		t.Fatalf("resource-only catalog: %v (%#v)", resourceErr, fault)
	}
	catalog, err := audit.Compile(catalogSpec, event, resource, resourceOperation)
	if err != nil {
		t.Fatal(err)
	}
	catalogs, err := audit.Lineage(catalog)
	if err != nil {
		t.Fatal(err)
	}
	change, err := audit.NewCatalogChangeRef("deploy.audit", audit.DeploymentChange("integration-"+suffix))
	if err != nil {
		t.Fatal(err)
	}
	if err := deployment.InstallCatalog(ctx, catalog.Manifest(), change); err != nil {
		t.Fatal(err)
	}
	proof, err := audit.NoAttemptCatalogActivation(audit.CatalogRef{}, catalog.Ref())
	if err != nil {
		t.Fatal(err)
	}
	if err := deployment.ActivateCatalog(ctx, audit.CatalogRef{}, catalog.Ref(), change, proof); err != nil {
		t.Fatal(err)
	}
	if err := deployment.VerifyCatalogs(ctx, catalogs.Manifests()); err != nil {
		t.Fatal(err)
	}
	store, err := New(Spec{DB: db, Source: source, Schema: schema})
	if err != nil {
		t.Fatal(err)
	}
	if err := store.Check(ctx); err != nil {
		t.Fatal(err)
	}
	operationID := audit.OperationID{7}
	operation, err := audit.NewContextValue(operationID, audit.Verified)
	if err != nil {
		t.Fatal(err)
	}
	explicitResolver, err := audit.StaticContext(audit.Context{Operation: operation})
	if err != nil {
		t.Fatal(err)
	}
	standalone, err := audit.New(audit.Config{Catalogs: catalogs, Writer: &failOnceWriter{Writer: store}, Context: explicitResolver, Semantics: semantic, Identities: identities})
	if err != nil {
		t.Fatal(err)
	}
	draft, err := event.New(liveOccurrence{Number: "INV-LIVE", At: time.Unix(1_790_000_100, 0).UTC()})
	if err != nil {
		t.Fatal(err)
	}
	failed, err := standalone.Record(ctx, draft, audit.WithIdempotencyKey("invoice-live"))
	if !errors.Is(err, audit.ErrNotWritten) {
		t.Fatalf("initial standalone append = %v, want not-written", err)
	}
	retry, ok := failed.RetryToken()
	if !ok {
		t.Fatal("certain pre-write failure has no retry token")
	}
	recorded, err := standalone.Retry(ctx, retry)
	if err != nil {
		t.Fatal(err)
	}
	receipt, ok := recorded.Receipt()
	if !ok || receipt.Disposition() != audit.Inserted {
		t.Fatalf("standalone receipt = (%#v, %v)", receipt, ok)
	}
	replayed, err := standalone.Retry(ctx, retry)
	if err != nil {
		t.Fatal(err)
	}
	replayReceipt, ok := replayed.Receipt()
	if !ok || replayReceipt.Disposition() != audit.Replayed || replayReceipt.RevisionID() != receipt.RevisionID() {
		t.Fatalf("standalone replay receipt = (%#v, %v)", replayReceipt, ok)
	}
	key, ok := receipt.ReconcileKey()
	if !ok {
		t.Fatal("standalone receipt has no reconcile key")
	}
	lookup, err := standalone.Lookup(ctx, key)
	if err != nil || lookup.State() != audit.Found {
		t.Fatalf("standalone lookup = (%v, %v)", lookup.State(), err)
	}
	generatedResolver, err := audit.StaticContext(audit.Context{})
	if err != nil {
		t.Fatal(err)
	}
	entityRecorder, err := audit.New(audit.Config{Catalogs: catalogs, Writer: store, Context: generatedResolver, Semantics: semantic, Identities: identities})
	if err != nil {
		t.Fatal(err)
	}
	core := &liveCore{meta: meta, source: source, table: businessTable}
	secured := auditcrud.Secured(entityRecorder, resource, security.Policy[liveEntity, int64]{Authorize: func(context.Context, security.Action) error { return nil }})(core)
	created, err := secured.Save(ctx, &liveEntity{Name: "created"})
	if err != nil || created.Name != "created" {
		var fault *errs.Fault
		_ = errors.As(err, &fault)
		t.Fatalf("audited create = (%+v, %v), cause=%v fault=%#v", created, err, audit.CauseOf(err), fault)
	}
	updated, err := secured.Update(ctx, 1, livePatch{Name: "updated"})
	if err != nil || updated.Name != "updated" {
		t.Fatalf("audited update = (%+v, %v)", updated, err)
	}
	var transitions, chains int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.entity_transitions`).Scan(&transitions); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.entity_chains WHERE leaf IS NOT NULL`).Scan(&chains); err != nil {
		t.Fatal(err)
	}
	if transitions != 2 || chains != 1 {
		t.Fatalf("entity CAS state = transitions:%d chains:%d, want 2/1", transitions, chains)
	}
	var before int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.revisions`).Scan(&before); err != nil {
		t.Fatal(err)
	}
	wrongDigest := bytes.Repeat([]byte{9}, 32)
	if _, err := db.ExecContext(ctx, `UPDATE `+quoteIdentifier(schema.Name)+`.settings SET active_digest=$1 WHERE singleton`, wrongDigest); err != nil {
		t.Fatal(err)
	}
	if _, err := secured.Save(ctx, &liveEntity{Name: "must-rollback"}); err == nil {
		t.Fatal("stale audit catalog did not fail the business transaction")
	}
	var businessRows, after int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+businessTable+` WHERE name='must-rollback'`).Scan(&businessRows); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+quoteIdentifier(schema.Name)+`.revisions`).Scan(&after); err != nil {
		t.Fatal(err)
	}
	if businessRows != 0 || after != before {
		t.Fatalf("failed audit leaked state: business=%d revisions before/after=%d/%d", businessRows, before, after)
	}
}

func (c *liveCore) Meta() *crud.Meta    { return c.meta }
func (c *liveCore) Source() crud.Source { return c.source }

func (c *liveCore) GetByID(ctx context.Context, id int64, _ ...crud.Option) (liveEntity, error) {
	rows, err := c.query(ctx, `SELECT id, name FROM `+c.table+` WHERE id=$1 FOR UPDATE`, id)
	if err != nil {
		return liveEntity{}, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return liveEntity{}, err
		}
		return liveEntity{}, crud.ErrNotFound
	}
	var value liveEntity
	if err := rows.Scan(&value.ID, &value.Name); err != nil {
		return liveEntity{}, err
	}
	return value, nil
}

func (c *liveCore) Get(context.Context, ...crud.Option) (crud.PaginatedResponse[liveEntity], error) {
	return crud.PaginatedResponse[liveEntity]{}, audit.ErrUnsupported
}

func (c *liveCore) GetAll(context.Context, ...crud.Option) ([]liveEntity, error) {
	return nil, audit.ErrUnsupported
}

func (c *liveCore) First(context.Context, ...crud.Option) (liveEntity, error) {
	return liveEntity{}, audit.ErrUnsupported
}

func (c *liveCore) Save(ctx context.Context, model *liveEntity) (liveEntity, error) {
	if model == nil {
		return liveEntity{}, crud.ErrBadRequest
	}
	if model.ID == 0 {
		rows, err := c.query(ctx, `INSERT INTO `+c.table+` (name) VALUES ($1) RETURNING id, name`, model.Name)
		if err != nil {
			return liveEntity{}, err
		}
		defer rows.Close()
		if !rows.Next() {
			if err := rows.Err(); err != nil {
				return liveEntity{}, err
			}
			return liveEntity{}, crud.ErrConflict
		}
		var stored liveEntity
		if err := rows.Scan(&stored.ID, &stored.Name); err != nil {
			return liveEntity{}, err
		}
		return stored, nil
	}
	if _, err := c.exec(ctx, `INSERT INTO `+c.table+` (id, name) VALUES ($1,$2)`, model.ID, model.Name); err != nil {
		return liveEntity{}, err
	}
	return *model, nil
}

func (c *liveCore) SaveOnly(ctx context.Context, model *liveEntity) error {
	_, err := c.Save(ctx, model)
	return err
}

func (c *liveCore) Update(ctx context.Context, id int64, value any, _ ...crud.Option) (liveEntity, error) {
	patch, ok := value.(livePatch)
	if !ok {
		return liveEntity{}, crud.ErrBadRequest
	}
	result, err := c.exec(ctx, `UPDATE `+c.table+` SET name=$1 WHERE id=$2`, patch.Name, id)
	if err != nil {
		return liveEntity{}, err
	}
	if result.RowsAffected != 1 {
		return liveEntity{}, crud.ErrNotFound
	}
	return liveEntity{ID: id, Name: patch.Name}, nil
}

func (*liveCore) UpdateAll(context.Context, any, ...crud.Option) (int64, error) {
	return 0, audit.ErrUnsupported
}

func (*liveCore) Aggregate(context.Context, ...crud.Option) ([]crud.AggregateRow, error) {
	return nil, audit.ErrUnsupported
}

func (*liveCore) SaveAll(context.Context, []*liveEntity) error { return audit.ErrUnsupported }

func (*liveCore) Delete(context.Context, ...int64) (int64, error) {
	return 0, audit.ErrUnsupported
}

func (*liveCore) DeleteAll(context.Context, ...crud.Option) (int64, error) {
	return 0, audit.ErrUnsupported
}

func (*liveCore) Count(context.Context, ...crud.Option) (int64, error) {
	return 0, audit.ErrUnsupported
}

func (*liveCore) Exists(context.Context, ...crud.Option) (bool, error) {
	return false, audit.ErrUnsupported
}

func (c *liveCore) Tx(ctx context.Context, fn func(context.Context) error) error {
	return crud.InTx(ctx, c.source, fn)
}

func (c *liveCore) SaveScoped(ctx context.Context, model *liveEntity, _ *crud.ScopedSave[liveEntity]) error {
	stored, err := c.Save(ctx, model)
	if err == nil {
		*model = stored
	}
	return err
}

func (*liveCore) DeleteScoped(context.Context, *crud.ScopedDelete[int64]) (int64, error) {
	return 0, audit.ErrUnsupported
}

func (*liveCore) ExistsUnscoped(context.Context, ...crud.Option) (bool, error) {
	return false, nil
}

func (c *liveCore) exec(ctx context.Context, query string, args ...any) (crud.Result, error) {
	if executor, ok := crud.ExecutorFor(ctx, c.source); ok {
		return executor.Exec(ctx, query, args...)
	}
	return c.source.Exec(ctx, query, args...)
}

func (c *liveCore) query(ctx context.Context, query string, args ...any) (crud.Rows, error) {
	if executor, ok := crud.ExecutorFor(ctx, c.source); ok {
		return executor.Query(ctx, query, args...)
	}
	return c.source.Query(ctx, query, args...)
}

var _ crud.Core[liveEntity, int64] = (*liveCore)(nil)
var _ crud.ScopedSaver[liveEntity, int64] = (*liveCore)(nil)
var _ crud.ScopedDeleter[liveEntity, int64] = (*liveCore)(nil)
var _ crud.UnscopedExister[liveEntity, int64] = (*liveCore)(nil)
