// Code generated by ent, DO NOT EDIT.

package entmodel

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/frostgrove/vv/_examples/entmodel/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/frostgrove/vv/_examples/entmodel/product"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Product is the client for interacting with the Product builders.
	Product *ProductClient
}

// NewClient creates a new client configured with the given options.
func NewClient(options ...Option) *Client {
	client := &Client{config: newConfig(options...)}
	client.init()
	return client
}

func (this *Client) init() {
	this.Schema = migrate.NewSchema(this.driver)
	this.Product = NewProductClient(this.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(options ...Option) config {
	config := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	config.options(options...)
	return config
}

// options applies the options on the config object.
func (this *config) options(options ...Option) {
	for _, opt := range options {
		opt(this)
	}
	if this.debug {
		this.driver = dialect.Debug(this.driver, this.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entmodel: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (this *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := this.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, this.driver)
	if err != nil {
		return nil, fmt.Errorf("entmodel: starting a transaction: %w", err)
	}
	config := this.config
	config.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  config,
		Product: NewProductClient(config),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (this *Client) BeginTx(ctx context.Context, options *sql.TxOptions) (*Tx, error) {
	if _, ok := this.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := this.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, options)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	config := this.config
	config.driver = &txDriver{tx: tx, drv: this.driver}
	return &Tx{
		ctx:     ctx,
		config:  config,
		Product: NewProductClient(config),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Product.
//		Query().
//		Count(ctx)
func (this *Client) Debug() *Client {
	if this.debug {
		return this
	}
	config := this.config
	config.driver = dialect.Debug(this.driver, this.log)
	client := &Client{config: config}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (this *Client) Close() error {
	return this.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (this *Client) Use(hooks ...Hook) {
	this.Product.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (this *Client) Intercept(interceptors ...Interceptor) {
	this.Product.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (this *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ProductMutation:
		return this.Product.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entmodel: unknown mutation type %T", m)
	}
}

// ProductClient is a client for the Product schema.
type ProductClient struct {
	config
}

// NewProductClient returns a client for the Product from the given config.
func NewProductClient(c config) *ProductClient {
	return &ProductClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `product.Hooks(f(g(h())))`.
func (this *ProductClient) Use(hooks ...Hook) {
	this.hooks.Product = append(this.hooks.Product, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `product.Intercept(f(g(h())))`.
func (this *ProductClient) Intercept(interceptors ...Interceptor) {
	this.inters.Product = append(this.inters.Product, interceptors...)
}

// Create returns a builder for creating a Product entity.
func (this *ProductClient) Create() *ProductCreate {
	mutation := newProductMutation(this.config, OpCreate)
	return &ProductCreate{config: this.config, hooks: this.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Product entities.
func (this *ProductClient) CreateBulk(builders ...*ProductCreate) *ProductCreateBulk {
	return &ProductCreateBulk{config: this.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (this *ProductClient) MapCreateBulk(slice any, setFunc func(*ProductCreate, int)) *ProductCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProductCreateBulk{err: fmt.Errorf("calling to ProductClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProductCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = this.Create()
		setFunc(builders[i], i)
	}
	return &ProductCreateBulk{config: this.config, builders: builders}
}

// Update returns an update builder for Product.
func (this *ProductClient) Update() *ProductUpdate {
	mutation := newProductMutation(this.config, OpUpdate)
	return &ProductUpdate{config: this.config, hooks: this.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (this *ProductClient) UpdateOne(_m *Product) *ProductUpdateOne {
	mutation := newProductMutation(this.config, OpUpdateOne, withProduct(_m))
	return &ProductUpdateOne{config: this.config, hooks: this.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (this *ProductClient) UpdateOneID(id int64) *ProductUpdateOne {
	mutation := newProductMutation(this.config, OpUpdateOne, withProductID(id))
	return &ProductUpdateOne{config: this.config, hooks: this.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Product.
func (this *ProductClient) Delete() *ProductDelete {
	mutation := newProductMutation(this.config, OpDelete)
	return &ProductDelete{config: this.config, hooks: this.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (this *ProductClient) DeleteOne(_m *Product) *ProductDeleteOne {
	return this.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (this *ProductClient) DeleteOneID(id int64) *ProductDeleteOne {
	builder := this.Delete().Where(product.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProductDeleteOne{builder}
}

// Query returns a query builder for Product.
func (this *ProductClient) Query() *ProductQuery {
	return &ProductQuery{
		config: this.config,
		ctx:    &QueryContext{Type: TypeProduct},
		inters: this.Interceptors(),
	}
}

// Get returns a Product entity by its id.
func (this *ProductClient) Get(ctx context.Context, id int64) (*Product, error) {
	return this.Query().Where(product.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (this *ProductClient) GetX(ctx context.Context, id int64) *Product {
	obj, err := this.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (this *ProductClient) Hooks() []Hook {
	return this.hooks.Product
}

// Interceptors returns the client interceptors.
func (this *ProductClient) Interceptors() []Interceptor {
	return this.inters.Product
}

func (this *ProductClient) mutate(ctx context.Context, m *ProductMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProductCreate{config: this.config, hooks: this.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProductUpdate{config: this.config, hooks: this.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProductUpdateOne{config: this.config, hooks: this.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProductDelete{config: this.config, hooks: this.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entmodel: unknown Product mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Product []ent.Hook
	}
	inters struct {
		Product []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (this *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := this.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (this *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := this.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
