// Code generated by ent, DO NOT EDIT.

package entmodel

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/_examples/entmodel/product"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetSku sets the "sku" field.
func (this *ProductCreate) SetSku(v string) *ProductCreate {
	this.mutation.SetSku(v)
	return this
}

// SetName sets the "name" field.
func (this *ProductCreate) SetName(v string) *ProductCreate {
	this.mutation.SetName(v)
	return this
}

// SetPrice sets the "price" field.
func (this *ProductCreate) SetPrice(v int) *ProductCreate {
	this.mutation.SetPrice(v)
	return this
}

// SetStock sets the "stock" field.
func (this *ProductCreate) SetStock(v int) *ProductCreate {
	this.mutation.SetStock(v)
	return this
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (this *ProductCreate) SetNillableStock(v *int) *ProductCreate {
	if v != nil {
		this.SetStock(*v)
	}
	return this
}

// SetActive sets the "active" field.
func (this *ProductCreate) SetActive(v bool) *ProductCreate {
	this.mutation.SetActive(v)
	return this
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (this *ProductCreate) SetNillableActive(v *bool) *ProductCreate {
	if v != nil {
		this.SetActive(*v)
	}
	return this
}

// SetCreatedAt sets the "created_at" field.
func (this *ProductCreate) SetCreatedAt(v time.Time) *ProductCreate {
	this.mutation.SetCreatedAt(v)
	return this
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (this *ProductCreate) SetNillableCreatedAt(v *time.Time) *ProductCreate {
	if v != nil {
		this.SetCreatedAt(*v)
	}
	return this
}

// SetID sets the "id" field.
func (this *ProductCreate) SetID(v int64) *ProductCreate {
	this.mutation.SetID(v)
	return this
}

// Mutation returns the ProductMutation object of the builder.
func (this *ProductCreate) Mutation() *ProductMutation {
	return this.mutation
}

// Save creates the Product in the database.
func (this *ProductCreate) Save(ctx context.Context) (*Product, error) {
	this.defaults()
	return withHooks(ctx, this.sqlSave, this.mutation, this.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (this *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (this *ProductCreate) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *ProductCreate) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (this *ProductCreate) defaults() {
	if _, ok := this.mutation.Active(); !ok {
		v := product.DefaultActive
		this.mutation.SetActive(v)
	}
	if _, ok := this.mutation.CreatedAt(); !ok {
		v := product.DefaultCreatedAt()
		this.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (this *ProductCreate) check() error {
	if _, ok := this.mutation.Sku(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`entmodel: missing required field "Product.sku"`)}
	}
	if _, ok := this.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`entmodel: missing required field "Product.name"`)}
	}
	if _, ok := this.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`entmodel: missing required field "Product.price"`)}
	}
	if _, ok := this.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`entmodel: missing required field "Product.active"`)}
	}
	if _, ok := this.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`entmodel: missing required field "Product.created_at"`)}
	}
	return nil
}

func (this *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := this.check(); err != nil {
		return nil, err
	}
	_node, _spec := this.createSpec()
	if err := sqlgraph.CreateNode(ctx, this.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{message: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	this.mutation.id = &_node.ID
	this.mutation.done = true
	return _node, nil
}

func (this *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: this.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64))
	)
	if id, ok := this.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := this.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := this.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := this.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if value, ok := this.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
		_node.Stock = &value
	}
	if value, ok := this.mutation.Active(); ok {
		_spec.SetField(product.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := this.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (this *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if this.err != nil {
		return nil, this.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(this.builders))
	nodes := make([]*Product, len(this.builders))
	mutators := make([]Mutator, len(this.builders))
	for i := range this.builders {
		func(i int, root context.Context) {
			builder := this.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, this.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, this.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{message: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, this.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (this *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (this *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}
