// Code generated by ent, DO NOT EDIT.

package entmodel

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/_examples/entmodel/predicate"
	"github.com/frostgrove/vv/_examples/entmodel/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (this *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	this.mutation.Where(ps...)
	return this
}

// SetSku sets the "sku" field.
func (this *ProductUpdate) SetSku(v string) *ProductUpdate {
	this.mutation.SetSku(v)
	return this
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (this *ProductUpdate) SetNillableSku(v *string) *ProductUpdate {
	if v != nil {
		this.SetSku(*v)
	}
	return this
}

// SetName sets the "name" field.
func (this *ProductUpdate) SetName(v string) *ProductUpdate {
	this.mutation.SetName(v)
	return this
}

// SetNillableName sets the "name" field if the given value is not nil.
func (this *ProductUpdate) SetNillableName(v *string) *ProductUpdate {
	if v != nil {
		this.SetName(*v)
	}
	return this
}

// SetPrice sets the "price" field.
func (this *ProductUpdate) SetPrice(v int) *ProductUpdate {
	this.mutation.ResetPrice()
	this.mutation.SetPrice(v)
	return this
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (this *ProductUpdate) SetNillablePrice(v *int) *ProductUpdate {
	if v != nil {
		this.SetPrice(*v)
	}
	return this
}

// AddPrice adds value to the "price" field.
func (this *ProductUpdate) AddPrice(v int) *ProductUpdate {
	this.mutation.AddPrice(v)
	return this
}

// SetStock sets the "stock" field.
func (this *ProductUpdate) SetStock(v int) *ProductUpdate {
	this.mutation.ResetStock()
	this.mutation.SetStock(v)
	return this
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (this *ProductUpdate) SetNillableStock(v *int) *ProductUpdate {
	if v != nil {
		this.SetStock(*v)
	}
	return this
}

// AddStock adds value to the "stock" field.
func (this *ProductUpdate) AddStock(v int) *ProductUpdate {
	this.mutation.AddStock(v)
	return this
}

// ClearStock clears the value of the "stock" field.
func (this *ProductUpdate) ClearStock() *ProductUpdate {
	this.mutation.ClearStock()
	return this
}

// SetActive sets the "active" field.
func (this *ProductUpdate) SetActive(v bool) *ProductUpdate {
	this.mutation.SetActive(v)
	return this
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (this *ProductUpdate) SetNillableActive(v *bool) *ProductUpdate {
	if v != nil {
		this.SetActive(*v)
	}
	return this
}

// SetCreatedAt sets the "created_at" field.
func (this *ProductUpdate) SetCreatedAt(v time.Time) *ProductUpdate {
	this.mutation.SetCreatedAt(v)
	return this
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (this *ProductUpdate) SetNillableCreatedAt(v *time.Time) *ProductUpdate {
	if v != nil {
		this.SetCreatedAt(*v)
	}
	return this
}

// Mutation returns the ProductMutation object of the builder.
func (this *ProductUpdate) Mutation() *ProductMutation {
	return this.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (this *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, this.sqlSave, this.mutation, this.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (this *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (this *ProductUpdate) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *ProductUpdate) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}

func (this *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64))
	if ps := this.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := this.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
	}
	if value, ok := this.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := this.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeInt, value)
	}
	if value, ok := this.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeInt, value)
	}
	if value, ok := this.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := this.mutation.AddedStock(); ok {
		_spec.AddField(product.FieldStock, field.TypeInt, value)
	}
	if this.mutation.StockCleared() {
		_spec.ClearField(product.FieldStock, field.TypeInt)
	}
	if value, ok := this.mutation.Active(); ok {
		_spec.SetField(product.FieldActive, field.TypeBool, value)
	}
	if value, ok := this.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, this.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{message: err.Error(), wrap: err}
		}
		return 0, err
	}
	this.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetSku sets the "sku" field.
func (this *ProductUpdateOne) SetSku(v string) *ProductUpdateOne {
	this.mutation.SetSku(v)
	return this
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (this *ProductUpdateOne) SetNillableSku(v *string) *ProductUpdateOne {
	if v != nil {
		this.SetSku(*v)
	}
	return this
}

// SetName sets the "name" field.
func (this *ProductUpdateOne) SetName(v string) *ProductUpdateOne {
	this.mutation.SetName(v)
	return this
}

// SetNillableName sets the "name" field if the given value is not nil.
func (this *ProductUpdateOne) SetNillableName(v *string) *ProductUpdateOne {
	if v != nil {
		this.SetName(*v)
	}
	return this
}

// SetPrice sets the "price" field.
func (this *ProductUpdateOne) SetPrice(v int) *ProductUpdateOne {
	this.mutation.ResetPrice()
	this.mutation.SetPrice(v)
	return this
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (this *ProductUpdateOne) SetNillablePrice(v *int) *ProductUpdateOne {
	if v != nil {
		this.SetPrice(*v)
	}
	return this
}

// AddPrice adds value to the "price" field.
func (this *ProductUpdateOne) AddPrice(v int) *ProductUpdateOne {
	this.mutation.AddPrice(v)
	return this
}

// SetStock sets the "stock" field.
func (this *ProductUpdateOne) SetStock(v int) *ProductUpdateOne {
	this.mutation.ResetStock()
	this.mutation.SetStock(v)
	return this
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (this *ProductUpdateOne) SetNillableStock(v *int) *ProductUpdateOne {
	if v != nil {
		this.SetStock(*v)
	}
	return this
}

// AddStock adds value to the "stock" field.
func (this *ProductUpdateOne) AddStock(v int) *ProductUpdateOne {
	this.mutation.AddStock(v)
	return this
}

// ClearStock clears the value of the "stock" field.
func (this *ProductUpdateOne) ClearStock() *ProductUpdateOne {
	this.mutation.ClearStock()
	return this
}

// SetActive sets the "active" field.
func (this *ProductUpdateOne) SetActive(v bool) *ProductUpdateOne {
	this.mutation.SetActive(v)
	return this
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (this *ProductUpdateOne) SetNillableActive(v *bool) *ProductUpdateOne {
	if v != nil {
		this.SetActive(*v)
	}
	return this
}

// SetCreatedAt sets the "created_at" field.
func (this *ProductUpdateOne) SetCreatedAt(v time.Time) *ProductUpdateOne {
	this.mutation.SetCreatedAt(v)
	return this
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (this *ProductUpdateOne) SetNillableCreatedAt(v *time.Time) *ProductUpdateOne {
	if v != nil {
		this.SetCreatedAt(*v)
	}
	return this
}

// Mutation returns the ProductMutation object of the builder.
func (this *ProductUpdateOne) Mutation() *ProductMutation {
	return this.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (this *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	this.mutation.Where(ps...)
	return this
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (this *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	this.fields = append([]string{field}, fields...)
	return this
}

// Save executes the query and returns the updated Product entity.
func (this *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, this.sqlSave, this.mutation, this.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (this *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (this *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}

func (this *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64))
	id, ok := this.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entmodel: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := this.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entmodel: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := this.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := this.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
	}
	if value, ok := this.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := this.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeInt, value)
	}
	if value, ok := this.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeInt, value)
	}
	if value, ok := this.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := this.mutation.AddedStock(); ok {
		_spec.AddField(product.FieldStock, field.TypeInt, value)
	}
	if this.mutation.StockCleared() {
		_spec.ClearField(product.FieldStock, field.TypeInt)
	}
	if value, ok := this.mutation.Active(); ok {
		_spec.SetField(product.FieldActive, field.TypeBool, value)
	}
	if value, ok := this.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Product{config: this.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, this.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{message: err.Error(), wrap: err}
		}
		return nil, err
	}
	this.mutation.done = true
	return _node, nil
}
