// Code generated by ent, DO NOT EDIT.

package entmodel

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/_examples/entmodel/predicate"
	"github.com/frostgrove/vv/_examples/entmodel/product"
)

// ProductDelete is the builder for deleting a Product entity.
type ProductDelete struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductDelete builder.
func (this *ProductDelete) Where(ps ...predicate.Product) *ProductDelete {
	this.mutation.Where(ps...)
	return this
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (this *ProductDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, this.sqlExec, this.mutation, this.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (this *ProductDelete) ExecX(ctx context.Context) int {
	n, err := this.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (this *ProductDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64))
	if ps := this.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, this.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{message: err.Error(), wrap: err}
	}
	this.mutation.done = true
	return affected, err
}

// ProductDeleteOne is the builder for deleting a single Product entity.
type ProductDeleteOne struct {
	_d *ProductDelete
}

// Where appends a list predicates to the ProductDelete builder.
func (this *ProductDeleteOne) Where(ps ...predicate.Product) *ProductDeleteOne {
	this._d.mutation.Where(ps...)
	return this
}

// Exec executes the deletion query.
func (this *ProductDeleteOne) Exec(ctx context.Context) error {
	n, err := this._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{product.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (this *ProductDeleteOne) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}
