// Code generated by ent, DO NOT EDIT.

package entmodel

import (
	"time"

	"github.com/shardit-io/vv/_examples/entmodel/product"
	"github.com/shardit-io/vv/_examples/entmodel/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescActive is the schema descriptor for active field.
	productDescActive := productFields[5].Descriptor()
	// product.DefaultActive holds the default value on creation for the active field.
	product.DefaultActive = productDescActive.Default.(bool)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[6].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
}
