// Code generated by ent, DO NOT EDIT.

package enttest

import (
	"context"

	"github.com/frostgrove/vv/_examples/entmodel"
	// required by schema hooks.
	_ "github.com/frostgrove/vv/_examples/entmodel/runtime"

	"entgo.io/ent/dialect/sql/schema"
	"github.com/frostgrove/vv/_examples/entmodel/migrate"
)

type (
	// TestingT is the interface that is shared between
	// testing.T and testing.B and used by enttest.
	TestingT interface {
		FailNow()
		Error(...any)
	}

	// Option configures client creation.
	Option func(*options)

	options struct {
		options     []entmodel.Option
		migrateOpts []schema.MigrateOption
	}
)

// WithOptions forwards options to client creation.
func WithOptions(options ...entmodel.Option) Option {
	return func(o *options) {
		o.options = append(o.options, options...)
	}
}

// WithMigrateOptions forwards options to auto migration.
func WithMigrateOptions(options ...schema.MigrateOption) Option {
	return func(o *options) {
		o.migrateOpts = append(o.migrateOpts, options...)
	}
}

func newOptions(options []Option) *options {
	o := &options{}
	for _, opt := range options {
		opt(o)
	}
	return o
}

// Open calls entmodel.Open and auto-run migration.
func Open(t TestingT, driverName, dataSourceName string, options ...Option) *entmodel.Client {
	o := newOptions(options)
	c, err := entmodel.Open(driverName, dataSourceName, o.options...)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	migrateSchema(t, c, o)
	return c
}

// NewClient calls entmodel.NewClient and auto-run migration.
func NewClient(t TestingT, options ...Option) *entmodel.Client {
	o := newOptions(options)
	c := entmodel.NewClient(o.options...)
	migrateSchema(t, c, o)
	return c
}
func migrateSchema(t TestingT, c *entmodel.Client, o *options) {
	tables, err := schema.CopyTables(migrate.Tables)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	if err := migrate.Create(context.Background(), c.Schema, tables, o.migrateOpts...); err != nil {
		t.Error(err)
		t.FailNow()
	}
}
