package i18n

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"go/token"
	"strconv"
	"strings"
)

type GoGeneratorSpec struct {
	Package        string
	MaxOutputBytes int
}

func GenerateGo(snapshot *Snapshot, spec GoGeneratorSpec) ([]byte, error) {
	return GenerateGoContext(context.Background(), snapshot, spec)
}

func GenerateGoContext(ctx context.Context, snapshot *Snapshot, spec GoGeneratorSpec) ([]byte, error) {
	return generateGoContext(ctx, snapshot, spec, format.Source)
}

func generateGoContext(ctx context.Context, snapshot *Snapshot, spec GoGeneratorSpec, formatSource func([]byte) ([]byte, error)) ([]byte, error) {
	if ctx == nil {
		return nil, fmt.Errorf("%w: generation context is nil", ErrInvalidCatalog)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if snapshot == nil {
		return nil, fmt.Errorf("%w: snapshot is nil", ErrInvalidCatalog)
	}
	maximum := spec.MaxOutputBytes
	if maximum == 0 || maximum > snapshot.limits.MaxCatalogBytes {
		maximum = snapshot.limits.MaxCatalogBytes
	}
	if maximum < 1 {
		return nil, fmt.Errorf("%w: generated Go output limit must be positive", ErrLimitExceeded)
	}
	if len(spec.Package) > snapshot.limits.MaxIdentifierBytes {
		return nil, fmt.Errorf("%w: Go package exceeds %d bytes", ErrLimitExceeded, snapshot.limits.MaxIdentifierBytes)
	}
	if !token.IsIdentifier(spec.Package) {
		return nil, fmt.Errorf("%w: invalid Go package %q", ErrInvalidCatalog, spec.Package)
	}
	if err := preflightGoGeneration(ctx, snapshot, maximum); err != nil {
		return nil, err
	}
	messages, needsBig, needsTime, needsMoney, err := generatedGoMessagesContext(ctx, snapshot)
	if err != nil {
		return nil, err
	}

	source := newContextBoundedTextBuilder(ctx, maximum)
	source.WriteString("// Code generated by github.com/frostgrove/vv/i18n.GenerateGo. DO NOT EDIT.\n\n")
	source.WriteString("package ")
	source.WriteString(spec.Package)
	source.WriteString("\n\nimport (\n")
	if needsBig {
		source.WriteString("\"math/big\"\n")
	}
	if needsTime {
		source.WriteString("\"time\"\n")
	}
	source.WriteString("vvi18n \"github.com/frostgrove/vv/i18n\"\n)\n\n")
	if needsMoney {
		source.WriteString("type Money struct {\nAmount string\nCurrency string\n}\n\n")
	}
	source.WriteString("type Catalog struct {\n")
	for _, message := range messages {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		fmt.Fprintf(source, "%s vvi18n.Definition[%s]\n", message.field, message.argsType)
	}
	source.WriteString("}\n\n")

	for _, message := range messages {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		for _, argument := range message.arguments {
			if argument.spec.Type != TypeEnum {
				continue
			}
			fmt.Fprintf(source, "type %s string\n\nconst (\n", argument.baseType)
			for valueIndex, value := range argument.spec.Values {
				fmt.Fprintf(source, "%s %s = %s\n", argument.enumConstants[valueIndex], argument.baseType, strconv.Quote(value))
			}
			source.WriteString(")\n\n")
		}
		fmt.Fprintf(source, "type %s struct {\n", message.argsType)
		for _, argument := range message.arguments {
			fmt.Fprintf(source, "%s %s\n", argument.field, argument.fieldType)
		}
		source.WriteString("}\n\n")
	}

	source.WriteString("func NewCatalog(snapshot *vvi18n.Snapshot) (Catalog, error) {\nvar catalog Catalog\n")
	if len(messages) != 0 {
		source.WriteString("var err error\n")
	}
	for _, message := range messages {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		fmt.Fprintf(source, "catalog.%s, err = vvi18n.Define(snapshot, vvi18n.DefinitionSpec[%s]{\n", message.field, message.argsType)
		fmt.Fprintf(source, "Contract: vvi18n.ContractRef{Key: vvi18n.Key(%s), Revision: %s, Digest: %s},\n", strconv.Quote(string(message.contract.Key)), strconv.Quote(message.contract.Revision), strconv.Quote(message.contract.Digest))
		fmt.Fprintf(source, "Encode: encode%s,\n})\n", message.name)
		source.WriteString("if err != nil {\nreturn Catalog{}, err\n}\n")
	}
	source.WriteString("return catalog, nil\n}\n\n")

	for _, message := range messages {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		fmt.Fprintf(source, "func encode%s(value %s) ([]vvi18n.Argument, error) {\n", message.name, message.argsType)
		if len(message.arguments) == 0 {
			source.WriteString("return nil, nil\n}\n\n")
			continue
		}
		fmt.Fprintf(source, "arguments := make([]vvi18n.Argument, 0, %d)\n", len(message.arguments))
		for _, argument := range message.arguments {
			access := "value." + argument.field
			if argument.spec.Required && !argument.spec.Nullable {
				fmt.Fprintf(source, "arguments = append(arguments, %s)\n", generatedArgumentExpression(argument.spec, access))
				continue
			}
			source.WriteString("if fieldValue, ok := ")
			source.WriteString(access)
			source.WriteString(".Get(); ok {\n")
			fmt.Fprintf(source, "arguments = append(arguments, %s)\n", generatedArgumentExpression(argument.spec, "fieldValue"))
			source.WriteString("} else if ")
			source.WriteString(access)
			source.WriteString(".IsNull() {\n")
			fmt.Fprintf(source, "arguments = append(arguments, vvi18n.Null(%s))\n}\n", strconv.Quote(argument.spec.Name))
		}
		source.WriteString("return arguments, nil\n}\n\n")
	}

	if err := source.Err(); err != nil {
		return nil, err
	}
	if source.Overflow() {
		return nil, fmt.Errorf("%w: generated Go source exceeds %d bytes", ErrLimitExceeded, maximum)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	formatted, err := formatSource([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("%w: generated Go source: %v", ErrInvalidCatalog, err)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if len(formatted) > maximum {
		return nil, fmt.Errorf("%w: generated Go source exceeds %d bytes", ErrLimitExceeded, maximum)
	}
	return formatted, nil
}

func preflightGoGeneration(ctx context.Context, snapshot *Snapshot, maximum int) error {
	remaining := maximum
	consume := func(size int) bool {
		if size < 0 || size > remaining {
			return false
		}
		remaining -= size
		return true
	}
	if !consume(64) {
		return fmt.Errorf("%w: generated Go source exceeds %d bytes", ErrLimitExceeded, maximum)
	}
	for key, record := range snapshot.records {
		if err := ctx.Err(); err != nil {
			return err
		}
		minimum := 128 + len(key) + len(record.descriptor.Revision) + len(record.contractHash)
		for _, argument := range record.descriptor.Arguments {
			minimum += 16 + len(argument.Name)
			for _, value := range argument.Values {
				minimum += len(value)
			}
		}
		if !consume(minimum) {
			return fmt.Errorf("%w: generated Go source exceeds %d bytes", ErrLimitExceeded, maximum)
		}
	}
	return nil
}

type generatedGoMessage struct {
	name      string
	field     string
	argsType  string
	contract  ContractRef
	arguments []generatedGoArgument
}

type generatedGoArgument struct {
	spec          ArgumentSpec
	field         string
	baseType      string
	fieldType     string
	enumConstants []string
}

type generatedEnumLocation struct {
	message  int
	argument int
}

type generatedConstantLocation struct {
	message  int
	argument int
	value    int
}

func generatedGoMessagesContext(ctx context.Context, snapshot *Snapshot) ([]generatedGoMessage, bool, bool, bool, error) {
	keys := snapshot.Keys()
	identifiers, err := uniqueGeneratedIdentifiers(keysToStrings(keys), "Message")
	if err != nil {
		return nil, false, false, false, err
	}
	fieldIdentifiers, err := uniqueGeneratedIdentifiers(keysToStrings(keys), "")
	if err != nil {
		return nil, false, false, false, err
	}
	messages := make([]generatedGoMessage, 0, len(keys))
	needsBig := false
	needsTime := false
	needsMoney := false
	for index, key := range keys {
		if err := ctx.Err(); err != nil {
			return nil, false, false, false, err
		}
		descriptor, ok := snapshot.Descriptor(key)
		contract, contractOK := snapshot.ContractRef(key)
		if !ok || !contractOK {
			return nil, false, false, false, fmt.Errorf("%w: message %q has no contract", ErrInvalidCatalog, key)
		}
		name := identifiers[index]
		message := generatedGoMessage{
			name:     name,
			field:    fieldIdentifiers[index],
			argsType: name + "Args",
			contract: contract,
		}
		argumentNames := make([]string, len(descriptor.Arguments))
		for argumentIndex, argument := range descriptor.Arguments {
			argumentNames[argumentIndex] = argument.Name
		}
		argumentFields, identifierErr := uniqueGeneratedIdentifiers(argumentNames, "Arg")
		if identifierErr != nil {
			return nil, false, false, false, fmt.Errorf("%w: arguments for %q: %v", ErrInvalidCatalog, key, identifierErr)
		}
		for argumentIndex, argument := range descriptor.Arguments {
			generated := generatedGoArgument{spec: argument, field: argumentFields[argumentIndex]}
			generated.baseType = generatedGoBaseType(name, generated.field, argument.Type)
			message.arguments = append(message.arguments, generated)
			needsBig = needsBig || argument.Type == TypeBigInteger
			needsTime = needsTime || argument.Type == TypeInstant
			needsMoney = needsMoney || argument.Type == TypeMoney
		}
		messages = append(messages, message)
	}
	if err := finalizeGeneratedGoNames(ctx, messages); err != nil {
		return nil, false, false, false, err
	}
	return messages, needsBig, needsTime, needsMoney, nil
}

func finalizeGeneratedGoNames(ctx context.Context, messages []generatedGoMessage) error {
	reserved := map[string]bool{"Catalog": true, "Money": true, "NewCatalog": true}
	for _, message := range messages {
		if err := ctx.Err(); err != nil {
			return err
		}
		reserved[message.argsType] = true
		reserved["encode"+message.name] = true
	}

	locations := make([]generatedEnumLocation, 0)
	identities := make([]string, 0)
	bases := make([]string, 0)
	for messageIndex := range messages {
		if err := ctx.Err(); err != nil {
			return err
		}
		for argumentIndex := range messages[messageIndex].arguments {
			argument := &messages[messageIndex].arguments[argumentIndex]
			if argument.spec.Type != TypeEnum {
				continue
			}
			locations = append(locations, generatedEnumLocation{message: messageIndex, argument: argumentIndex})
			identities = append(identities, string(messages[messageIndex].contract.Key)+"\x00"+argument.spec.Name)
			bases = append(bases, argument.baseType)
		}
	}
	enumNames, err := uniqueGeneratedIdentifiersAgainst(identities, bases, reserved)
	if err != nil {
		return fmt.Errorf("%w: generated enum type names: %v", ErrInvalidCatalog, err)
	}
	for index, name := range enumNames {
		location := locations[index]
		messages[location.message].arguments[location.argument].baseType = name
		reserved[name] = true
	}

	for messageIndex := range messages {
		if err := ctx.Err(); err != nil {
			return err
		}
		for argumentIndex := range messages[messageIndex].arguments {
			argument := &messages[messageIndex].arguments[argumentIndex]
			argument.fieldType = argument.baseType
			if !argument.spec.Required || argument.spec.Nullable {
				argument.fieldType = "vvi18n.Optional[" + argument.baseType + "]"
			}
		}
	}

	constantLocations := make([]generatedConstantLocation, 0)
	constantIdentities := make([]string, 0)
	constantBases := make([]string, 0)
	for messageIndex := range messages {
		if err := ctx.Err(); err != nil {
			return err
		}
		for argumentIndex := range messages[messageIndex].arguments {
			argument := &messages[messageIndex].arguments[argumentIndex]
			if argument.spec.Type != TypeEnum {
				continue
			}
			argument.enumConstants = make([]string, len(argument.spec.Values))
			for valueIndex, value := range argument.spec.Values {
				constantLocations = append(constantLocations, generatedConstantLocation{message: messageIndex, argument: argumentIndex, value: valueIndex})
				constantIdentities = append(constantIdentities, string(messages[messageIndex].contract.Key)+"\x00"+argument.spec.Name+"\x00"+value)
				constantBases = append(constantBases, argument.baseType+goExportedIdentifier(value, "Value"))
			}
		}
	}
	constantNames, err := uniqueGeneratedIdentifiersAgainst(constantIdentities, constantBases, reserved)
	if err != nil {
		return fmt.Errorf("%w: generated enum constant names: %v", ErrInvalidCatalog, err)
	}
	for index, name := range constantNames {
		location := constantLocations[index]
		messages[location.message].arguments[location.argument].enumConstants[location.value] = name
		reserved[name] = true
	}
	return nil
}

func generatedGoBaseType(messageName, argumentName string, argumentType ArgumentType) string {
	switch argumentType {
	case TypeText, TypeDecimal:
		return "string"
	case TypeBool:
		return "bool"
	case TypeInteger:
		return "int64"
	case TypeUnsignedInteger:
		return "uint64"
	case TypeBigInteger:
		return "*big.Int"
	case TypeMoney:
		return "Money"
	case TypeDate:
		return "vvi18n.DateValue"
	case TypeInstant:
		return "time.Time"
	case TypeEnum:
		return messageName + argumentName + "Enum"
	default:
		return "struct{}"
	}
}

func generatedArgumentExpression(argument ArgumentSpec, access string) string {
	name := strconv.Quote(argument.Name)
	switch argument.Type {
	case TypeText:
		return "vvi18n.Text(" + name + ", " + access + ")"
	case TypeBool:
		return "vvi18n.Bool(" + name + ", " + access + ")"
	case TypeInteger:
		return "vvi18n.Integer(" + name + ", " + access + ")"
	case TypeUnsignedInteger:
		return "vvi18n.UnsignedInteger(" + name + ", " + access + ")"
	case TypeBigInteger:
		return "vvi18n.BigInteger(" + name + ", " + access + ")"
	case TypeDecimal:
		return "vvi18n.Decimal(" + name + ", " + access + ")"
	case TypeMoney:
		return "vvi18n.Money(" + name + ", " + access + ".Amount, " + access + ".Currency)"
	case TypeDate:
		return "vvi18n.Date(" + name + ", " + access + ".Year, " + access + ".Month, " + access + ".Day)"
	case TypeInstant:
		return "vvi18n.Instant(" + name + ", " + access + ")"
	case TypeEnum:
		return "vvi18n.Enum(" + name + ", string(" + access + "))"
	default:
		return "vvi18n.Null(" + name + ")"
	}
}

func keysToStrings(keys []Key) []string {
	values := make([]string, len(keys))
	for index, key := range keys {
		values[index] = string(key)
	}
	return values
}

func uniqueGeneratedIdentifiers(values []string, fallback string) ([]string, error) {
	bases := make([]string, len(values))
	for index, value := range values {
		bases[index] = goExportedIdentifier(value, fallback)
	}
	return uniqueGeneratedIdentifiersFromBases(values, bases)
}

func uniqueGeneratedIdentifiersFromBases(values, bases []string) ([]string, error) {
	return uniqueGeneratedIdentifiersAgainst(values, bases, nil)
}

func uniqueGeneratedIdentifiersAgainst(values, bases []string, reserved map[string]bool) ([]string, error) {
	if len(values) != len(bases) {
		return nil, fmt.Errorf("identifier inputs have different lengths")
	}
	result := make([]string, len(bases))
	used := make(map[string]bool, len(bases)+len(reserved))
	for name := range reserved {
		used[name] = true
	}
	for index, base := range bases {
		if used[base] {
			return nil, fmt.Errorf("identifier %q for %q collides with another generated declaration", base, values[index])
		}
		used[base] = true
		result[index] = base
	}
	return result, nil
}

func goExportedIdentifier(value, fallback string) string {
	var out strings.Builder
	upper := true
	for _, r := range value {
		if r >= 'a' && r <= 'z' {
			if upper {
				r -= 'a' - 'A'
			}
			out.WriteRune(r)
			upper = false
			continue
		}
		if r >= 'A' && r <= 'Z' {
			out.WriteRune(r)
			upper = false
			continue
		}
		if r >= '0' && r <= '9' {
			if out.Len() == 0 {
				out.WriteByte('X')
			}
			out.WriteRune(r)
			upper = false
			continue
		}
		upper = true
	}
	if out.Len() == 0 {
		out.WriteString(fallback)
	}
	if out.Len() == 0 {
		out.WriteByte('X')
	}
	if !stableReadableIdentifierSource(value) {
		out.WriteByte('X')
		out.WriteString(generatedIdentifierHash(value))
	}
	return out.String()
}

func stableReadableIdentifierSource(value string) bool {
	if value == "" {
		return false
	}
	for _, segment := range strings.Split(value, ".") {
		if segment == "" || segment[0] < 'a' || segment[0] > 'z' {
			return false
		}
		for _, character := range segment[1:] {
			if character >= 'a' && character <= 'z' || character >= '0' && character <= '9' {
				continue
			}
			return false
		}
	}
	return true
}

func generatedIdentifierHash(value string) string {
	sum := sha256.Sum256([]byte(value))
	return hex.EncodeToString(sum[:8])
}
