services:
  collector:
    image: otel/opentelemetry-collector-contrib@sha256:799dc6cf12c96192af37b5bdba804da8c10b3bc563b43cb90c3f3c58d9572ad6
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./collector.dev.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:9464:9464"
      - "127.0.0.1:13133:13133"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
