// Code generated by rxcrud. DO NOT EDIT.

package blog

import (
	"time"

	"github.com/shardit-io/vv/crud"
	"github.com/shardit-io/vv/repo/decorators/specs"
)

// ArticleUpdate is the partial-update DTO for Article.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type ArticleUpdate struct {
	AuthorID    *int64              `json:"authorID,omitempty"`
	Title       *string             `json:"title,omitempty"`
	Body        *string             `json:"body,omitempty"`
	Views       *int                `json:"views,omitempty"`
	Rating      crud.Opt[float64]   `json:"rating,omitzero"`
	PublishedAt crud.Opt[time.Time] `json:"publishedAt,omitzero"`
}

// ArticleAuthorAttrs reaches Article through Author.
type ArticleAuthorAttrs struct {
	ID   specs.Ord[Article, int64]
	Name specs.Str[Article]
}

// ArticleCommentsAttrs reaches Article through Comments.
type ArticleCommentsAttrs struct {
	ID        specs.Ord[Article, int64]
	ArticleID specs.Ord[Article, int64]
	AuthorID  specs.Ord[Article, int64]
	Body      specs.Str[Article]
	Approved  specs.Attr[Article, bool]
}

// ArticleTagsAttrs reaches Article through Tags.
type ArticleTagsAttrs struct {
	ID   specs.Ord[Article, int64]
	Slug specs.Str[Article]
}

// ArticleAttrs is the generated metamodel shape for Article.
type ArticleAttrs struct {
	ID          specs.Ord[Article, int64]
	AuthorID    specs.Ord[Article, int64]
	Title       specs.Str[Article]
	Body        specs.Str[Article]
	Views       specs.Ord[Article, int]
	Rating      specs.Ord[Article, float64]
	PublishedAt specs.Cmp[Article, time.Time]
	TenantID    specs.Ord[Article, int64]
	CreatedAt   specs.Cmp[Article, time.Time]
	Author      ArticleAuthorAttrs
	Comments    ArticleCommentsAttrs
	Tags        ArticleTagsAttrs
}

// Article_ is the metamodel of Article: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Article_ = specs.Metamodel[Article, ArticleAttrs]()

// AuthorUpdate is the partial-update DTO for Author.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type AuthorUpdate struct {
	Name *string `json:"name,omitempty"`
}

// AuthorArticlesAttrs reaches Author through Articles.
type AuthorArticlesAttrs struct {
	ID          specs.Ord[Author, int64]
	AuthorID    specs.Ord[Author, int64]
	Title       specs.Str[Author]
	Body        specs.Str[Author]
	Views       specs.Ord[Author, int]
	Rating      specs.Ord[Author, float64]
	PublishedAt specs.Cmp[Author, time.Time]
	TenantID    specs.Ord[Author, int64]
	CreatedAt   specs.Cmp[Author, time.Time]
}

// AuthorAttrs is the generated metamodel shape for Author.
type AuthorAttrs struct {
	ID       specs.Ord[Author, int64]
	Name     specs.Str[Author]
	Articles AuthorArticlesAttrs
}

// Author_ is the metamodel of Author: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Author_ = specs.Metamodel[Author, AuthorAttrs]()

// CommentUpdate is the partial-update DTO for Comment.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type CommentUpdate struct {
	ArticleID *int64  `json:"articleID,omitempty"`
	AuthorID  *int64  `json:"authorID,omitempty"`
	Body      *string `json:"body,omitempty"`
	Approved  *bool   `json:"approved,omitempty"`
}

// CommentAuthorAttrs reaches Comment through Author.
type CommentAuthorAttrs struct {
	ID   specs.Ord[Comment, int64]
	Name specs.Str[Comment]
}

// CommentAttrs is the generated metamodel shape for Comment.
type CommentAttrs struct {
	ID        specs.Ord[Comment, int64]
	ArticleID specs.Ord[Comment, int64]
	AuthorID  specs.Ord[Comment, int64]
	Body      specs.Str[Comment]
	Approved  specs.Attr[Comment, bool]
	Author    CommentAuthorAttrs
}

// Comment_ is the metamodel of Comment: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Comment_ = specs.Metamodel[Comment, CommentAttrs]()

// TagUpdate is the partial-update DTO for Tag.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type TagUpdate struct {
	Slug *string `json:"slug,omitempty"`
}

// TagAttrs is the generated metamodel shape for Tag.
type TagAttrs struct {
	ID   specs.Ord[Tag, int64]
	Slug specs.Str[Tag]
}

// Tag_ is the metamodel of Tag: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Tag_ = specs.Metamodel[Tag, TagAttrs]()
