// Code generated by vv. DO NOT EDIT.

package blog

import (
	"context"
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/http/crudnet"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/errs"
	"github.com/frostgrove/vv/port"
	"github.com/frostgrove/vv/utils"
	"net/http"
	"time"
)

type ArticleUpdate struct {
	AuthorID    *int64               `json:"authorID,omitempty"`
	Title       *string              `json:"title,omitempty"`
	Body        *string              `json:"body,omitempty"`
	Views       *int                 `json:"views,omitempty"`
	Rating      utils.Opt[float64]   `json:"rating,omitzero"`
	PublishedAt utils.Opt[time.Time] `json:"publishedAt,omitzero"`
}

type ArticleAuthorAttrs struct {
	specs.Rel[Article, Author]
	ID   specs.Ord[Article, int64]
	Name specs.Str[Article]
}

type ArticleCommentsAttrs struct {
	specs.Rel[Article, Comment]
	ID        specs.Ord[Article, int64]
	ArticleID specs.Ord[Article, int64]
	AuthorID  specs.Ord[Article, int64]
	Body      specs.Str[Article]
	Approved  specs.Attr[Article, bool]
}

type ArticleTagsAttrs struct {
	specs.Rel[Article, Tag]
	ID   specs.Ord[Article, int64]
	Slug specs.Str[Article]
}

type ArticleAttrs struct {
	ID          specs.Ord[Article, int64]
	AuthorID    specs.Ord[Article, int64]
	Title       specs.Str[Article]
	Body        specs.Str[Article]
	Views       specs.Ord[Article, int]
	Rating      specs.Ord[Article, float64]
	PublishedAt specs.Cmp[Article, time.Time]
	TenantID    specs.Ord[Article, int64]
	CreatedAt   specs.Cmp[Article, time.Time]
	Author      ArticleAuthorAttrs
	Comments    ArticleCommentsAttrs
	Tags        ArticleTagsAttrs
}

var Article_ = specs.Metamodel[Article, ArticleAttrs]()

type ArticleRepo = crud.Repo[Article, int64, ArticleUpdate]

var ArticleRepository = sqlrepo.Define[Article, int64, ArticleUpdate]("")

func NewArticleRepository(src crud.Source) *ArticleRepo {
	return ArticleRepository.Bind(src)
}

type ArticleInput struct {
	AuthorID    int64               `json:"authorID"`
	Title       string              `json:"title"`
	Body        string              `json:"body"`
	Views       int                 `json:"views"`
	Rating      *float64            `json:"rating"`
	PublishedAt crud.Opt[time.Time] `json:"publishedAt"`
	TenantID    int64               `json:"tenantID"`
}

type ArticleMapper struct{}

func (ArticleMapper) Model(_ context.Context, in ArticleInput) (Article, error) {
	out := Article{}
	out.AuthorID = in.AuthorID
	out.Title = in.Title
	out.Body = in.Body
	out.Views = in.Views
	out.Rating = in.Rating
	out.PublishedAt = in.PublishedAt
	out.TenantID = in.TenantID
	return out, nil
}

func (ArticleMapper) Resolve(p errs.Path) (errs.Path, bool) { return ArticlePaths.Resolve(p) }

var ArticlePaths = port.MustPathMap[Article](port.PathMap{
	"AuthorID":    port.At("authorID"),
	"Title":       port.At("title"),
	"Body":        port.At("body"),
	"Views":       port.At("views"),
	"Rating":      port.At("rating"),
	"PublishedAt": port.At("publishedAt"),
	"TenantID":    port.At("tenantID"),
}, "ID")

type ArticleService struct {
	*port.DefaultService[Article, int64, ArticleUpdate]
}

var _ port.Service[Article, int64, ArticleUpdate] = (*ArticleService)(nil)

func NewArticleService(repo port.Repository[Article, int64, ArticleUpdate], opts ...port.ServiceOption) *ArticleService {
	return &ArticleService{DefaultService: port.NewService(repo, opts...)}
}

func MountArticle(mux *http.ServeMux, prefix string, svc port.Service[Article, int64, ArticleUpdate], opts ...crudnet.Option[Article, int64, ArticleUpdate]) {
	crudnet.ServingFor(svc, ArticleMapper{}, opts...).Mount(mux, prefix)
}

type AuthorUpdate struct {
	Name *string `json:"name,omitempty"`
}

type AuthorArticlesAttrs struct {
	specs.Rel[Author, Article]
	ID          specs.Ord[Author, int64]
	AuthorID    specs.Ord[Author, int64]
	Title       specs.Str[Author]
	Body        specs.Str[Author]
	Views       specs.Ord[Author, int]
	Rating      specs.Ord[Author, float64]
	PublishedAt specs.Cmp[Author, time.Time]
	TenantID    specs.Ord[Author, int64]
	CreatedAt   specs.Cmp[Author, time.Time]
}

type AuthorAttrs struct {
	ID       specs.Ord[Author, int64]
	Name     specs.Str[Author]
	Articles AuthorArticlesAttrs
}

var Author_ = specs.Metamodel[Author, AuthorAttrs]()

type AuthorRepo = crud.Repo[Author, int64, AuthorUpdate]

var AuthorRepository = sqlrepo.Define[Author, int64, AuthorUpdate]("")

func NewAuthorRepository(src crud.Source) *AuthorRepo {
	return AuthorRepository.Bind(src)
}

type AuthorInput struct {
	Name string `json:"name"`
}

type AuthorMapper struct{}

func (AuthorMapper) Model(_ context.Context, in AuthorInput) (Author, error) {
	out := Author{}
	out.Name = in.Name
	return out, nil
}

func (AuthorMapper) Resolve(p errs.Path) (errs.Path, bool) { return AuthorPaths.Resolve(p) }

var AuthorPaths = port.MustPathMap[Author](port.PathMap{
	"Name": port.At("name"),
}, "ID")

type AuthorService struct {
	*port.DefaultService[Author, int64, AuthorUpdate]
}

var _ port.Service[Author, int64, AuthorUpdate] = (*AuthorService)(nil)

func NewAuthorService(repo port.Repository[Author, int64, AuthorUpdate], opts ...port.ServiceOption) *AuthorService {
	return &AuthorService{DefaultService: port.NewService(repo, opts...)}
}

func MountAuthor(mux *http.ServeMux, prefix string, svc port.Service[Author, int64, AuthorUpdate], opts ...crudnet.Option[Author, int64, AuthorUpdate]) {
	crudnet.ServingFor(svc, AuthorMapper{}, opts...).Mount(mux, prefix)
}

type CommentUpdate struct {
	ArticleID *int64  `json:"articleID,omitempty"`
	AuthorID  *int64  `json:"authorID,omitempty"`
	Body      *string `json:"body,omitempty"`
	Approved  *bool   `json:"approved,omitempty"`
}

type CommentAuthorAttrs struct {
	specs.Rel[Comment, Author]
	ID   specs.Ord[Comment, int64]
	Name specs.Str[Comment]
}

type CommentAttrs struct {
	ID        specs.Ord[Comment, int64]
	ArticleID specs.Ord[Comment, int64]
	AuthorID  specs.Ord[Comment, int64]
	Body      specs.Str[Comment]
	Approved  specs.Attr[Comment, bool]
	Author    CommentAuthorAttrs
}

var Comment_ = specs.Metamodel[Comment, CommentAttrs]()

type CommentRepo = crud.Repo[Comment, int64, CommentUpdate]

var CommentRepository = sqlrepo.Define[Comment, int64, CommentUpdate]("")

func NewCommentRepository(src crud.Source) *CommentRepo {
	return CommentRepository.Bind(src)
}

type CommentInput struct {
	ArticleID int64  `json:"articleID"`
	AuthorID  int64  `json:"authorID"`
	Body      string `json:"body"`
	Approved  bool   `json:"approved"`
}

type CommentMapper struct{}

func (CommentMapper) Model(_ context.Context, in CommentInput) (Comment, error) {
	out := Comment{}
	out.ArticleID = in.ArticleID
	out.AuthorID = in.AuthorID
	out.Body = in.Body
	out.Approved = in.Approved
	return out, nil
}

func (CommentMapper) Resolve(p errs.Path) (errs.Path, bool) { return CommentPaths.Resolve(p) }

var CommentPaths = port.MustPathMap[Comment](port.PathMap{
	"ArticleID": port.At("articleID"),
	"AuthorID":  port.At("authorID"),
	"Body":      port.At("body"),
	"Approved":  port.At("approved"),
}, "ID")

type CommentService struct {
	*port.DefaultService[Comment, int64, CommentUpdate]
}

var _ port.Service[Comment, int64, CommentUpdate] = (*CommentService)(nil)

func NewCommentService(repo port.Repository[Comment, int64, CommentUpdate], opts ...port.ServiceOption) *CommentService {
	return &CommentService{DefaultService: port.NewService(repo, opts...)}
}

func MountComment(mux *http.ServeMux, prefix string, svc port.Service[Comment, int64, CommentUpdate], opts ...crudnet.Option[Comment, int64, CommentUpdate]) {
	crudnet.ServingFor(svc, CommentMapper{}, opts...).Mount(mux, prefix)
}

type TagUpdate struct {
	Slug *string `json:"slug,omitempty"`
}

type TagAttrs struct {
	ID   specs.Ord[Tag, int64]
	Slug specs.Str[Tag]
}

var Tag_ = specs.Metamodel[Tag, TagAttrs]()

type TagRepo = crud.Repo[Tag, int64, TagUpdate]

var TagRepository = sqlrepo.Define[Tag, int64, TagUpdate]("")

func NewTagRepository(src crud.Source) *TagRepo {
	return TagRepository.Bind(src)
}

type TagInput struct {
	Slug string `json:"slug"`
}

type TagMapper struct{}

func (TagMapper) Model(_ context.Context, in TagInput) (Tag, error) {
	out := Tag{}
	out.Slug = in.Slug
	return out, nil
}

func (TagMapper) Resolve(p errs.Path) (errs.Path, bool) { return TagPaths.Resolve(p) }

var TagPaths = port.MustPathMap[Tag](port.PathMap{
	"Slug": port.At("slug"),
}, "ID")

type TagService struct {
	*port.DefaultService[Tag, int64, TagUpdate]
}

var _ port.Service[Tag, int64, TagUpdate] = (*TagService)(nil)

func NewTagService(repo port.Repository[Tag, int64, TagUpdate], opts ...port.ServiceOption) *TagService {
	return &TagService{DefaultService: port.NewService(repo, opts...)}
}

func MountTag(mux *http.ServeMux, prefix string, svc port.Service[Tag, int64, TagUpdate], opts ...crudnet.Option[Tag, int64, TagUpdate]) {
	crudnet.ServingFor(svc, TagMapper{}, opts...).Mount(mux, prefix)
}

func init() {
	port.MustCoverUpdate[Article, ArticleUpdate]()
	port.MustCoverUpdate[Author, AuthorUpdate]()
	port.MustCoverUpdate[Comment, CommentUpdate]()
	port.MustCoverUpdate[Tag, TagUpdate]()
}
