package vvgoose

import (
	"bytes"
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/frostgrove/vv/utils/vvdb"
	"github.com/frostgrove/vv/utils/vvgoose/internal/modelscan"
)

func TestMigrationCommandCreatesAnEditableFileWithoutOpeningTheDatabase(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	migrations := filepath.Join(root, "migrations")
	cfg := vvdb.Config{
		// This is deliberately not a usable SQLite connection. Generation only
		// needs the dialect and must not validate/open the database.
		Engine: vvdb.SQLite,
		Migration: vvdb.Migration{
			Path:   migrations,
			Models: []string{filepath.Join(root, "does-not-exist")},
		},
	}
	var out bytes.Buffer
	err := execute(context.Background(), []string{"migration", "init_permissions"}, cfg, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	})
	if err != nil {
		t.Fatal(err)
	}
	files := migrationFiles(t, migrations)
	if len(files) != 1 || !strings.HasSuffix(files[0], "_init_permissions.sql") {
		t.Fatalf("migration files = %v, want one init_permissions migration", files)
	}
	contents := readFile(t, files[0])
	if strings.Contains(contents, "CREATE TABLE") || !strings.Contains(contents, "-- +goose Up") {
		t.Fatalf("migration should be an editable, valid Goose skeleton:\n%s", contents)
	}
	if !strings.Contains(out.String(), "created ") {
		t.Fatalf("output = %q, want created path", out.String())
	}
}

func TestTableMigrationInfersColumnsFromTheOnlyMatchingModel(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), `package account

import "time"

type User struct {
	ID        int64      @db:"id,pk,auto"@
	Email     string     @db:"email"@
	Nickname  *string    @db:"nickname"@
	CreatedAt time.Time  @db:"created_at,generated"@
	Manager   *User      @rel:"belongs_to"@
}
`)
	cfg := vvdb.Config{
		Engine: vvdb.Postgres,
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{models},
		},
	}
	path, err := createTableMigration(context.Background(), cfg, createOptions{
		Name: "users",
		Now:  func() time.Time { return time.Date(2026, 8, 27, 12, 34, 56, 0, time.UTC) },
	})
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(path) != "20260827123456_create_users_table.sql" {
		t.Fatalf("path = %s", path)
	}
	contents := readFile(t, path)
	for _, want := range []string{
		`CREATE TABLE IF NOT EXISTS "users"`,
		`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
		`"email" TEXT NOT NULL`,
		`"nickname" TEXT`,
		`"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`,
		`DROP TABLE IF EXISTS "users"`,
	} {
		if !strings.Contains(contents, want) {
			t.Errorf("generated migration does not contain %q:\n%s", want, contents)
		}
	}
	if strings.Contains(contents, "manager") {
		t.Fatalf("relation became a SQL column:\n%s", contents)
	}
}

func TestGeneratedSQLiteMigrationRunsThroughGoose(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), `package account
type User struct {
	ID    int64   @db:"id,pk,auto"@
	Email string  @db:"email"@
	Alias *string @db:"alias"@
}
`)
	cfg := vvdb.Config{
		Engine: vvdb.SQLite,
		Path:   filepath.Join(root, "app.sqlite"),
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{models},
		},
	}
	if _, err := createTableMigration(context.Background(), cfg, createOptions{Name: "users"}); err != nil {
		t.Fatal(err)
	}
	if _, err := runMigrate(context.Background(), cfg); err != nil {
		t.Fatalf("apply generated migration: %v", err)
	}
	db, err := vvdb.Open(&cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	rows, err := db.Query(`PRAGMA table_info("users")`)
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
	columns := map[string]bool{}
	for rows.Next() {
		var cid, notNull, pk int
		var name, typ string
		var defaultValue any
		if err := rows.Scan(&cid, &name, &typ, &notNull, &defaultValue, &pk); err != nil {
			t.Fatal(err)
		}
		columns[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"id", "email", "alias"} {
		if !columns[name] {
			t.Fatalf("generated table columns = %v, missing %s", columns, name)
		}
	}
}

func TestAmbiguousModelIsEmptyOutsideInteractiveMode(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for _, pkg := range []string{"billing", "identity"} {
		writeTestSource(t, filepath.Join(root, pkg, "user.model.go"), "package "+pkg+"\ntype User struct { ID int64 }\n")
	}
	cfg := vvdb.Config{
		Engine: vvdb.MySQL,
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{root},
		},
	}
	path, err := createTableMigration(context.Background(), cfg, createOptions{Name: "users"})
	if err != nil {
		t.Fatal(err)
	}
	if contents := readFile(t, path); strings.Contains(contents, "CREATE TABLE") {
		t.Fatalf("ambiguous non-interactive generation must be empty:\n%s", contents)
	}
}

func TestInteractiveAmbiguityLetsTheAuthorChooseAModel(t *testing.T) {
	// Huh's accessible renderer is deterministic over a pipe while exercising
	// the same selection value as its searchable terminal renderer.
	t.Setenv("TERM", "dumb")
	models := []modelscan.Model{
		{Package: "billing", Name: "User", Table: "users"},
		{Package: "identity", Name: "User", Table: "users"},
	}
	var out bytes.Buffer
	selected, err := selectModel(context.Background(), models, strings.NewReader("2\n"), &out)
	if err != nil {
		t.Fatal(err)
	}
	if selected == nil || selected.Package != "identity" {
		t.Fatalf("selected = %+v, want the second model", selected)
	}
}

func TestCreateMigrationNeverOverwritesTheSameTimestamp(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	now := func() time.Time { return time.Date(2026, 8, 27, 12, 0, 0, 0, time.UTC) }
	cfg := vvdb.Config{Engine: vvdb.SQLite, Migration: vvdb.Migration{Path: root, Models: []string{"."}}}
	options := createOptions{Name: "users", Empty: true, Now: now}
	first, err := createTableMigration(context.Background(), cfg, options)
	if err != nil {
		t.Fatal(err)
	}
	second, err := createTableMigration(context.Background(), cfg, options)
	if err != nil {
		t.Fatal(err)
	}
	if first == second || filepath.Base(second) != "20260827120001_create_users_table.sql" {
		t.Fatalf("first = %s, second = %s; want next second without overwrite", first, second)
	}
	third, err := createTableMigration(context.Background(), cfg, createOptions{Name: "teams", Empty: true, Now: now})
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(third) != "20260827120002_create_teams_table.sql" {
		t.Fatalf("third = %s; a different slug must still get a unique Goose version", third)
	}
}

func TestTableNamesWithUnderscoresStillCreateTableMigrations(t *testing.T) {
	t.Parallel()
	file, table, err := migrationNames("audit_logs")
	if err != nil {
		t.Fatal(err)
	}
	if file != "create_audit_logs_table" || table != "audit_logs" {
		t.Fatalf("migrationNames(audit_logs) = %q, %q", file, table)
	}
	file, table, err = migrationNames("add_email_to_users")
	if err != nil || file != "add_email_to_users" || table != "users" {
		t.Fatalf("migrationNames(add_email_to_users) = %q, %q, %v", file, table, err)
	}
}

func TestMigrationNameDoesNotInferATableWithoutExplicitTables(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), "package account\ntype User struct { ID int64; Email string }\n")
	cfg := vvdb.Config{
		Engine: vvdb.Postgres,
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{models},
		},
	}
	path, err := createMigration(context.Background(), cfg, migrationOptions{Name: "add_email_to_users"})
	if err != nil {
		t.Fatal(err)
	}
	if contents := readFile(t, path); strings.Contains(contents, "CREATE TABLE") {
		t.Fatalf("an ALTER-style name generated a duplicate table:\n%s", contents)
	}
}

func TestTableCommandCreatesOneMigrationForEachCommaSeparatedTable(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), "package app\ntype User struct { ID int64; Email string }\n")
	writeTestSource(t, filepath.Join(models, "product.model.go"), "package app\ntype Product struct { ID int64; SKU string }\n")
	cfg := vvdb.Config{Engine: vvdb.SQLite, Migration: vvdb.Migration{
		Path: filepath.Join(root, "migrations"), Models: []string{models},
	}}
	var out bytes.Buffer
	if err := execute(context.Background(), []string{"table", "users,products"}, cfg, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	}); err != nil {
		t.Fatal(err)
	}
	files := migrationFiles(t, cfg.Migration.Path)
	if len(files) != 2 || !strings.HasSuffix(files[0], "_create_users_table.sql") || !strings.HasSuffix(files[1], "_create_products_table.sql") {
		t.Fatalf("table migrations = %v", files)
	}
	for _, file := range files {
		if !strings.Contains(readFile(t, file), "CREATE TABLE") {
			t.Fatalf("table migration %s is empty", file)
		}
	}
}

func TestMigrationCommandGeneratesExplicitTablesInOneNamedFile(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "permission.model.go"), "package app\ntype Permission struct { ID int64; Name string }\n")
	writeTestSource(t, filepath.Join(models, "role.model.go"), "package app\ntype Role struct { ID int64; Name string }\n")
	cfg := vvdb.Config{Engine: vvdb.Postgres, Migration: vvdb.Migration{
		Path: filepath.Join(root, "migrations"), Models: []string{models},
	}}
	var out bytes.Buffer
	if err := execute(context.Background(), []string{"migration", "init_permission_tables", "-t", "permissions,roles"}, cfg, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	}); err != nil {
		t.Fatal(err)
	}
	files := migrationFiles(t, cfg.Migration.Path)
	if len(files) != 1 || !strings.HasSuffix(files[0], "_init_permission_tables.sql") {
		t.Fatalf("migration files = %v", files)
	}
	contents := readFile(t, files[0])
	for _, table := range []string{`CREATE TABLE IF NOT EXISTS "permissions"`, `CREATE TABLE IF NOT EXISTS "roles"`, `DROP TABLE IF EXISTS "roles"`, `DROP TABLE IF EXISTS "permissions"`} {
		if !strings.Contains(contents, table) {
			t.Fatalf("named migration missing %q:\n%s", table, contents)
		}
	}
}

func TestMigrationCommandAcceptsTablesAsItsSecondPositionalArgument(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "permission.model.go"), "package app\ntype Permission struct { ID int64; Name string }\n")
	cfg := vvdb.Config{Engine: vvdb.SQLite, Migration: vvdb.Migration{
		Path: filepath.Join(root, "migrations"), Models: []string{models},
	}}
	if err := execute(context.Background(), []string{"migration", "init_permissions", "permissions"}, cfg, commandIO{
		in: strings.NewReader(""), out: &bytes.Buffer{}, err: &bytes.Buffer{},
	}); err != nil {
		t.Fatal(err)
	}
	files := migrationFiles(t, cfg.Migration.Path)
	if len(files) != 1 || !strings.Contains(readFile(t, files[0]), `CREATE TABLE IF NOT EXISTS "permissions"`) {
		t.Fatalf("positional tables migration = %v", files)
	}
}

func TestInitMigrationIncludesAllModelsAndOverwritesItsOwnFile(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	permission := filepath.Join(models, "permission.model.go")
	role := filepath.Join(models, "role.model.go")
	writeTestSource(t, permission, "package app\ntype Permission struct { ID int64; Name string }\n")
	writeTestSource(t, role, "package app\ntype Role struct { ID int64; Title string }\n")
	writeTestSource(t, filepath.Join(models, "stub.model.go"), "package app\ntype Stub struct{}\n")
	cfg := vvdb.Config{Engine: vvdb.Postgres, Migration: vvdb.Migration{
		Path: filepath.Join(root, "migrations"), Models: []string{models},
	}}
	now := func() time.Time { return time.Date(2026, 8, 27, 13, 0, 0, 0, time.UTC) }
	first, err := createInitMigration(cfg, now)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasSuffix(first, "_init.sql") {
		t.Fatalf("init path = %s", first)
	}
	firstSQL := readFile(t, first)
	if strings.Count(firstSQL, "CREATE TABLE") != 2 || strings.Contains(firstSQL, `"stubs"`) {
		t.Fatalf("initial SQL =\n%s", firstSQL)
	}
	writeTestSource(t, permission, "package app\ntype Permission struct { ID int64; Code string }\n")
	second, err := createInitMigration(cfg, now)
	if err != nil {
		t.Fatal(err)
	}
	if second != first {
		t.Fatalf("init path changed from %s to %s", first, second)
	}
	secondSQL := readFile(t, second)
	if strings.Contains(secondSQL, `"name"`) || !strings.Contains(secondSQL, `"code"`) {
		t.Fatalf("init SQL was not replaced:\n%s", secondSQL)
	}
	files := migrationFiles(t, cfg.Migration.Path)
	if len(files) != 1 || files[0] != first {
		t.Fatalf("init files = %v, want exactly %s", files, first)
	}
}

func TestGeneratedInitMigrationRunsThroughGoose(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), "package app\ntype User struct { ID int64; Email string }\n")
	writeTestSource(t, filepath.Join(models, "product.model.go"), "package app\ntype Product struct { ID int64; SKU string }\n")
	cfg := vvdb.Config{
		Engine: vvdb.SQLite,
		Path:   filepath.Join(root, "app.sqlite"),
		Migration: vvdb.Migration{
			Path: filepath.Join(root, "migrations"), Models: []string{models},
		},
	}
	if _, err := createInitMigration(cfg, nil); err != nil {
		t.Fatal(err)
	}
	if _, err := runMigrate(context.Background(), cfg); err != nil {
		t.Fatalf("apply generated init migration: %v", err)
	}
	db, err := vvdb.Open(&cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	for _, table := range []string{"users", "products"} {
		var count int
		if err := db.QueryRow(`SELECT count(*) FROM sqlite_master WHERE type = 'table' AND name = ?`, table).Scan(&count); err != nil {
			t.Fatal(err)
		}
		if count != 1 {
			t.Fatalf("table %q was not created by init", table)
		}
	}
}

func TestNoArgumentsPrintsTheAvailableCommands(t *testing.T) {
	t.Parallel()
	var out bytes.Buffer
	err := execute(context.Background(), nil, vvdb.Config{}, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, command := range []string{"migration", "table", "init", "migrate", "fresh", "flush", "status", "rollback"} {
		if !strings.Contains(out.String(), command) {
			t.Errorf("help does not list %q:\n%s", command, out.String())
		}
	}
}

func TestConfigPathFlagCanRemainAfterVVCfgConsumesIt(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	cfg := vvdb.Config{Engine: vvdb.SQLite, Migration: vvdb.Migration{Path: root}}
	err := execute(context.Background(), []string{"--config-path", "config/app.yml", "table", "audit", "--empty"}, cfg, commandIO{
		in: strings.NewReader(""), out: &bytes.Buffer{}, err: &bytes.Buffer{},
	})
	if err != nil {
		t.Fatalf("the vvcfg flag should be accepted by vvgoose too: %v", err)
	}
}

func TestACharacterDeviceIsNotNecessarilyAnInteractiveTerminal(t *testing.T) {
	t.Parallel()
	f, err := os.Open(os.DevNull)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	if terminalFile(f) {
		t.Fatal("the null device was treated as an interactive terminal")
	}
}

func TestBufferedOutputIsNotAnInteractiveTerminal(t *testing.T) {
	t.Parallel()
	if terminalFile(&bytes.Buffer{}) {
		t.Fatal("buffered output was treated as an interactive terminal")
	}
}

func TestInteractiveMenuCreatesAnEmptyMigrationWithoutCLIArguments(t *testing.T) {
	t.Setenv("TERM", "dumb")
	root := t.TempDir()
	cfg := vvdb.Config{
		Engine: vvdb.SQLite,
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{filepath.Join(root, "not-needed-for-empty")},
		},
	}
	var out bytes.Buffer
	err := runInteractive(context.Background(), cfg, commandIO{
		// 1 = migration, then its name, then an empty optional tables field.
		in: &byteAtATimeReader{Reader: strings.NewReader("1\ninit_users\n\n")}, out: &out, err: &out,
	})
	if err != nil {
		t.Fatal(err)
	}
	files := migrationFiles(t, cfg.Migration.Path)
	if len(files) != 1 || !strings.HasSuffix(files[0], "_init_users.sql") {
		t.Fatalf("interactive migration files = %v", files)
	}
	if !strings.Contains(out.String(), "What do you want to do?") || !strings.Contains(out.String(), "created ") {
		t.Fatalf("interactive output = %q", out.String())
	}
}

// Huh's accessible fields each create their own buffered reader. A terminal
// delivers input over time, while a strings.Reader can let the first field
// buffer every later answer; limiting reads models the terminal accurately.
type byteAtATimeReader struct{ io.Reader }

func (r *byteAtATimeReader) Read(p []byte) (int, error) {
	if len(p) > 1 {
		p = p[:1]
	}
	return r.Reader.Read(p)
}

func TestInteractiveMenuCanExitWithoutOpeningTheDatabase(t *testing.T) {
	t.Setenv("TERM", "dumb")
	var out bytes.Buffer
	if err := runInteractive(context.Background(), vvdb.Config{}, commandIO{
		in: strings.NewReader("8\n"), out: &out, err: &out,
	}); err != nil {
		t.Fatal(err)
	}
}

func TestInteractiveMenuDefaultsToExitOnEOF(t *testing.T) {
	t.Setenv("TERM", "dumb")
	if err := runInteractive(context.Background(), vvdb.Config{}, commandIO{
		in: strings.NewReader(""), out: &bytes.Buffer{}, err: &bytes.Buffer{},
	}); err != nil {
		t.Fatal(err)
	}
}

func TestInteractiveRollbackRequiresConfirmation(t *testing.T) {
	t.Setenv("TERM", "dumb")
	var out bytes.Buffer
	if err := runInteractiveRollback(context.Background(), vvdb.Config{}, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "cancelled") {
		t.Fatalf("output = %q, want a safe cancellation", out.String())
	}
}

func TestInteractiveAmbiguityDefaultsToAnEmptyMigrationOnEOF(t *testing.T) {
	t.Setenv("TERM", "dumb")
	models := []modelscan.Model{
		{Package: "billing", Name: "User", Table: "users"},
		{Package: "identity", Name: "User", Table: "users"},
	}
	selected, err := selectModel(context.Background(), models, strings.NewReader(""), &bytes.Buffer{})
	if err != nil {
		t.Fatal(err)
	}
	if selected != nil {
		t.Fatalf("EOF selected %+v; want an empty migration", selected)
	}
}

func writeTestSource(t *testing.T, path, source string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	source = strings.ReplaceAll(source, "@", "`")
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
}

func migrationFiles(t *testing.T, dir string) []string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			files = append(files, filepath.Join(dir, entry.Name()))
		}
	}
	return files
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(contents)
}
