package vvgoose

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/frostgrove/vv/utils/vvdb"
	"github.com/frostgrove/vv/utils/vvgoose/internal/modelscan"
)

func TestMigrationCommandAcceptsFlagsAfterTheNameAndDoesNotOpenTheDatabase(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	migrations := filepath.Join(root, "migrations")
	cfg := vvdb.Config{
		// This is deliberately not a usable SQLite connection. Generation only
		// needs the dialect and must not validate/open the database.
		Engine: vvdb.SQLite,
		Migration: vvdb.Migration{
			Path:   migrations,
			Models: []string{filepath.Join(root, "does-not-exist")},
		},
	}
	var out bytes.Buffer
	err := execute(context.Background(), []string{"migration", "users", "--empty"}, cfg, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	})
	if err != nil {
		t.Fatal(err)
	}
	files := migrationFiles(t, migrations)
	if len(files) != 1 || !strings.HasSuffix(files[0], "_create_users_table.sql") {
		t.Fatalf("migration files = %v, want one create_users_table migration", files)
	}
	contents := readFile(t, files[0])
	if strings.Contains(contents, "CREATE TABLE") || !strings.Contains(contents, "-- +goose Up") {
		t.Fatalf("--empty migration should be an editable, valid Goose skeleton:\n%s", contents)
	}
	if !strings.Contains(out.String(), "created ") {
		t.Fatalf("output = %q, want created path", out.String())
	}
}

func TestCreateMigrationInfersColumnsFromTheOnlyMatchingModel(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), `package account

import "time"

type User struct {
	ID        int64      @db:"id,pk,auto"@
	Email     string     @db:"email"@
	Nickname  *string    @db:"nickname"@
	CreatedAt time.Time  @db:"created_at,generated"@
	Manager   *User      @rel:"belongs_to"@
}
`)
	cfg := vvdb.Config{
		Engine: vvdb.Postgres,
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{models},
		},
	}
	path, err := createMigration(context.Background(), cfg, createOptions{
		Name: "users",
		Now:  func() time.Time { return time.Date(2026, 8, 27, 12, 34, 56, 0, time.UTC) },
	})
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(path) != "20260827123456_create_users_table.sql" {
		t.Fatalf("path = %s", path)
	}
	contents := readFile(t, path)
	for _, want := range []string{
		`CREATE TABLE "users"`,
		`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
		`"email" TEXT NOT NULL`,
		`"nickname" TEXT`,
		`"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`,
		`DROP TABLE IF EXISTS "users"`,
	} {
		if !strings.Contains(contents, want) {
			t.Errorf("generated migration does not contain %q:\n%s", want, contents)
		}
	}
	if strings.Contains(contents, "manager") {
		t.Fatalf("relation became a SQL column:\n%s", contents)
	}
}

func TestGeneratedSQLiteMigrationRunsThroughGoose(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	models := filepath.Join(root, "src")
	writeTestSource(t, filepath.Join(models, "user.model.go"), `package account
type User struct {
	ID    int64   @db:"id,pk,auto"@
	Email string  @db:"email"@
	Alias *string @db:"alias"@
}
`)
	cfg := vvdb.Config{
		Engine: vvdb.SQLite,
		Path:   filepath.Join(root, "app.sqlite"),
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{models},
		},
	}
	if _, err := createMigration(context.Background(), cfg, createOptions{Name: "users"}); err != nil {
		t.Fatal(err)
	}
	if _, err := runMigrate(context.Background(), cfg); err != nil {
		t.Fatalf("apply generated migration: %v", err)
	}
	db, err := vvdb.Open(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	rows, err := db.Query(`PRAGMA table_info("users")`)
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
	columns := map[string]bool{}
	for rows.Next() {
		var cid, notNull, pk int
		var name, typ string
		var defaultValue any
		if err := rows.Scan(&cid, &name, &typ, &notNull, &defaultValue, &pk); err != nil {
			t.Fatal(err)
		}
		columns[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"id", "email", "alias"} {
		if !columns[name] {
			t.Fatalf("generated table columns = %v, missing %s", columns, name)
		}
	}
}

func TestAmbiguousModelIsEmptyOutsideInteractiveMode(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for _, pkg := range []string{"billing", "identity"} {
		writeTestSource(t, filepath.Join(root, pkg, "user.model.go"), "package "+pkg+"\ntype User struct { ID int64 }\n")
	}
	cfg := vvdb.Config{
		Engine: vvdb.MySQL,
		Migration: vvdb.Migration{
			Path:   filepath.Join(root, "migrations"),
			Models: []string{root},
		},
	}
	path, err := createMigration(context.Background(), cfg, createOptions{Name: "users"})
	if err != nil {
		t.Fatal(err)
	}
	if contents := readFile(t, path); strings.Contains(contents, "CREATE TABLE") {
		t.Fatalf("ambiguous non-interactive generation must be empty:\n%s", contents)
	}
}

func TestInteractiveAmbiguityLetsTheAuthorChooseAModel(t *testing.T) {
	// Huh's accessible renderer is deterministic over a pipe while exercising
	// the same selection value as its searchable terminal renderer.
	t.Setenv("TERM", "dumb")
	models := []modelscan.Model{
		{Package: "billing", Name: "User", Table: "users"},
		{Package: "identity", Name: "User", Table: "users"},
	}
	var out bytes.Buffer
	selected, err := selectModel(context.Background(), models, strings.NewReader("2\n"), &out)
	if err != nil {
		t.Fatal(err)
	}
	if selected == nil || selected.Package != "identity" {
		t.Fatalf("selected = %+v, want the second model", selected)
	}
}

func TestCreateMigrationNeverOverwritesTheSameTimestamp(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	now := func() time.Time { return time.Date(2026, 8, 27, 12, 0, 0, 0, time.UTC) }
	cfg := vvdb.Config{Engine: vvdb.SQLite, Migration: vvdb.Migration{Path: root, Models: []string{"."}}}
	options := createOptions{Name: "users", Empty: true, Now: now}
	first, err := createMigration(context.Background(), cfg, options)
	if err != nil {
		t.Fatal(err)
	}
	second, err := createMigration(context.Background(), cfg, options)
	if err != nil {
		t.Fatal(err)
	}
	if first == second || filepath.Base(second) != "20260827120001_create_users_table.sql" {
		t.Fatalf("first = %s, second = %s; want next second without overwrite", first, second)
	}
}

func TestTableNamesWithUnderscoresStillCreateTableMigrations(t *testing.T) {
	t.Parallel()
	file, table, err := migrationNames("audit_logs")
	if err != nil {
		t.Fatal(err)
	}
	if file != "create_audit_logs_table" || table != "audit_logs" {
		t.Fatalf("migrationNames(audit_logs) = %q, %q", file, table)
	}
	file, table, err = migrationNames("add_email_to_users")
	if err != nil || file != "add_email_to_users" || table != "users" {
		t.Fatalf("migrationNames(add_email_to_users) = %q, %q, %v", file, table, err)
	}
}

func TestNoArgumentsPrintsTheAvailableCommands(t *testing.T) {
	t.Parallel()
	var out bytes.Buffer
	err := execute(context.Background(), nil, vvdb.Config{}, commandIO{
		in: strings.NewReader(""), out: &out, err: &out,
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, command := range []string{"migration", "migrate", "fresh", "status", "rollback"} {
		if !strings.Contains(out.String(), command) {
			t.Errorf("help does not list %q:\n%s", command, out.String())
		}
	}
}

func TestConfigPathFlagCanRemainAfterVVCfgConsumesIt(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	cfg := vvdb.Config{Engine: vvdb.SQLite, Migration: vvdb.Migration{Path: root}}
	err := execute(context.Background(), []string{"--config-path", "config/app.yml", "migration", "audit", "--empty"}, cfg, commandIO{
		in: strings.NewReader(""), out: &bytes.Buffer{}, err: &bytes.Buffer{},
	})
	if err != nil {
		t.Fatalf("the vvcfg flag should be accepted by vvgoose too: %v", err)
	}
}

func writeTestSource(t *testing.T, path, source string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	source = strings.ReplaceAll(source, "@", "`")
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
}

func migrationFiles(t *testing.T, dir string) []string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			files = append(files, filepath.Join(dir, entry.Name()))
		}
	}
	return files
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(contents)
}
