package vvgoose

import (
	"strings"
	"testing"

	"github.com/frostgrove/vv/utils/vvdb"
	"github.com/frostgrove/vv/utils/vvgoose/internal/modelscan"
)

func TestRenderMigrationUsesEachEngineDialect(t *testing.T) {
	t.Parallel()
	model := &modelscan.Model{Name: "User", Fields: []modelscan.Field{
		{Name: "ID", Column: "id", GoType: "int64", PrimaryKey: true, Auto: true},
		{Name: "Payload", Column: "payload", GoType: "json.RawMessage"},
	}}
	for _, test := range []struct {
		engine vvdb.Engine
		id     string
		json   string
	}{
		{vvdb.Postgres, `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`, `"payload" JSONB NOT NULL`},
		{vvdb.MySQL, "`id` BIGINT AUTO_INCREMENT PRIMARY KEY", "`payload` JSON NOT NULL"},
		{vvdb.MariaDB, "`id` BIGINT AUTO_INCREMENT PRIMARY KEY", "`payload` JSON NOT NULL"},
		{vvdb.SQLite, `"id" INTEGER PRIMARY KEY`, `"payload" TEXT NOT NULL`},
	} {
		test := test
		t.Run(string(test.engine), func(t *testing.T) {
			t.Parallel()
			migration, err := renderMigration(test.engine, "users", model)
			if err != nil {
				t.Fatal(err)
			}
			if got := string(migration); !strings.Contains(got, test.id) || !strings.Contains(got, test.json) {
				t.Fatalf("migration =\n%s\nwant %q and %q", got, test.id, test.json)
			}
		})
	}
}

func TestRenderMigrationRejectsDuplicateOrUnsafeColumns(t *testing.T) {
	t.Parallel()
	for _, fields := range [][]modelscan.Field{
		{{Name: "One", Column: "email", GoType: "string"}, {Name: "Two", Column: "EMAIL", GoType: "string"}},
		{{Name: "Bad", Column: "email;drop", GoType: "string"}},
	} {
		if _, err := renderMigration(vvdb.Postgres, "users", &modelscan.Model{Name: "User", Fields: fields}); err == nil {
			t.Fatalf("unsafe model fields %#v were accepted", fields)
		}
	}
}

func TestBaseGoTypeUnwrapsPointersAndOptionalGenerics(t *testing.T) {
	t.Parallel()
	for raw, want := range map[string]string{
		"*string":              "string",
		"crud.Opt[time.Time]":  "time.Time",
		"*crud.Opt[uuid.UUID]": "uuid.UUID",
		"[]uint8":              "[]byte",
		"[]string":             "slice",
		"map[string]any":       "map",
	} {
		if got := baseGoType(raw); got != want {
			t.Errorf("baseGoType(%q) = %q, want %q", raw, got, want)
		}
	}
}
