package vvgoose

import (
	"strings"
	"testing"

	"github.com/frostgrove/vv/utils/vvdb"
	"github.com/frostgrove/vv/utils/vvgoose/internal/modelscan"
)

func TestRenderMigrationUsesEachEngineDialect(t *testing.T) {
	t.Parallel()
	model := &modelscan.Model{Name: "User", Fields: []modelscan.Field{
		{Name: "ID", Column: "id", GoType: "int64", PrimaryKey: true, Auto: true},
		{Name: "Payload", Column: "payload", GoType: "json.RawMessage"},
	}}
	for _, test := range []struct {
		engine vvdb.Engine
		id     string
		json   string
	}{
		{vvdb.Postgres, `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`, `"payload" JSONB NOT NULL`},
		{vvdb.MySQL, "`id` BIGINT AUTO_INCREMENT PRIMARY KEY", "`payload` JSON NOT NULL"},
		{vvdb.MariaDB, "`id` BIGINT AUTO_INCREMENT PRIMARY KEY", "`payload` JSON NOT NULL"},
		{vvdb.SQLite, `"id" INTEGER PRIMARY KEY`, `"payload" TEXT NOT NULL`},
	} {
		test := test
		t.Run(string(test.engine), func(t *testing.T) {
			t.Parallel()
			migration, err := renderMigration(test.engine, "users", model)
			if err != nil {
				t.Fatal(err)
			}
			if got := string(migration); !strings.Contains(got, test.id) || !strings.Contains(got, test.json) {
				t.Fatalf("migration =\n%s\nwant %q and %q", got, test.id, test.json)
			}
		})
	}
}

func TestRenderMigrationRejectsDuplicateOrUnsafeColumns(t *testing.T) {
	t.Parallel()
	for _, fields := range [][]modelscan.Field{
		{{Name: "One", Column: "email", GoType: "string"}, {Name: "Two", Column: "EMAIL", GoType: "string"}},
		{{Name: "Bad", Column: "email;drop", GoType: "string"}},
	} {
		if _, err := renderMigration(vvdb.Postgres, "users", &modelscan.Model{Name: "User", Fields: fields}); err == nil {
			t.Fatalf("unsafe model fields %#v were accepted", fields)
		}
	}
}

func TestBaseGoTypeUnwrapsPointersAndOptionalGenerics(t *testing.T) {
	t.Parallel()
	for raw, want := range map[string]string{
		"*string":              "string",
		"crud.Opt[time.Time]":  "time.Time",
		"*crud.Opt[uuid.UUID]": "uuid.UUID",
		"[]uint8":              "[]byte",
		"[]string":             "slice",
		"map[string]any":       "map",
	} {
		if got := baseGoType(raw); got != want {
			t.Errorf("baseGoType(%q) = %q, want %q", raw, got, want)
		}
	}
}

func TestCompositePrimaryKeyUsesOneTableConstraint(t *testing.T) {
	t.Parallel()
	model := &modelscan.Model{Name: "Membership", Fields: []modelscan.Field{
		{Name: "ID", Column: "id", GoType: "int64", PrimaryKey: true, Auto: true},
		{Name: "Tenant", Column: "tenant", GoType: "string", PrimaryKey: true},
	}}
	migration, err := renderMigration(vvdb.Postgres, "memberships", model)
	if err != nil {
		t.Fatal(err)
	}
	got := string(migration)
	if strings.Count(got, "PRIMARY KEY") != 1 || !strings.Contains(got, `PRIMARY KEY ("id", "tenant")`) ||
		!strings.Contains(got, `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`) {
		t.Fatalf("composite migration =\n%s", got)
	}
	if _, err := renderMigration(vvdb.SQLite, "memberships", model); err == nil {
		t.Fatal("SQLite accepted auto inside a composite primary key")
	}
}

func TestMySQLCompositePrimaryKeyPutsAutoColumnFirstWithoutMovingColumns(t *testing.T) {
	t.Parallel()
	model := &modelscan.Model{Name: "Membership", Fields: []modelscan.Field{
		{Name: "TenantID", Column: "tenant_id", GoType: "string", PrimaryKey: true},
		{Name: "ID", Column: "id", GoType: "int64", PrimaryKey: true, Auto: true},
	}}
	for _, engine := range []vvdb.Engine{vvdb.MySQL, vvdb.MariaDB} {
		migration, err := renderMigration(engine, "memberships", model)
		if err != nil {
			t.Fatalf("%s: %v", engine, err)
		}
		got := string(migration)
		columns := "    `tenant_id` VARCHAR(255) NOT NULL,\n    `id` BIGINT AUTO_INCREMENT NOT NULL,"
		if !strings.Contains(got, columns) || !strings.Contains(got, "PRIMARY KEY (`id`, `tenant_id`)") {
			t.Fatalf("%s composite migration =\n%s", engine, got)
		}
	}
}

func TestSemanticNamedScalarsWinOverLocalStorageType(t *testing.T) {
	t.Parallel()
	model := &modelscan.Model{Name: "Record", Fields: []modelscan.Field{
		{Name: "ID", Column: "id", GoType: "UUID", CanonicalType: "UUID", UnderlyingType: "[16]byte", PrimaryKey: true},
		{Name: "Amount", Column: "amount", GoType: "Decimal", CanonicalType: "Decimal", UnderlyingType: "string"},
	}}
	migration, err := renderMigration(vvdb.Postgres, "records", model)
	if err != nil {
		t.Fatal(err)
	}
	got := string(migration)
	if !strings.Contains(got, `"id" UUID PRIMARY KEY`) || !strings.Contains(got, `"amount" NUMERIC NOT NULL`) {
		t.Fatalf("semantic scalar migration =\n%s", got)
	}
}

func TestRenderMigrationRefusesDDLItCannotInferSafely(t *testing.T) {
	t.Parallel()
	for name, fields := range map[string][]modelscan.Field{
		"multiple auto keys": {
			{Name: "One", Column: "one", GoType: "int64", PrimaryKey: true, Auto: true},
			{Name: "Two", Column: "two", GoType: "int64", PrimaryKey: true, Auto: true},
		},
		"generated expression": {
			{Name: "ID", Column: "id", GoType: "int64", PrimaryKey: true, Auto: true},
			{Name: "Code", Column: "code", GoType: "string", Generated: true},
		},
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := renderMigration(vvdb.Postgres, "records", &modelscan.Model{Name: "Record", Fields: fields}); err == nil {
				t.Fatal("unsafe inferred DDL was accepted")
			}
		})
	}
}

func TestSQLiteTimeUsesADateAwareDeclaredType(t *testing.T) {
	t.Parallel()
	migration, err := renderMigration(vvdb.SQLite, "events", &modelscan.Model{Name: "Event", Fields: []modelscan.Field{
		{Name: "ID", Column: "id", GoType: "int64", PrimaryKey: true, Auto: true},
		{Name: "At", Column: "at", GoType: "time.Time"},
	}})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(migration), `"at" DATETIME NOT NULL`) {
		t.Fatalf("SQLite migration =\n%s", migration)
	}
}
