#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"
cd "$REPO_ROOT"

run_workspace() {
	local -a args=("$@")
	local module
	while IFS= read -r module; do
		echo "==> $module"
		(cd "$module" && "$GO" "${args[@]}")
	done < <(workspace_modules)
}

unit() {
	run_workspace test -race ./...
	echo '==> ./_examples'
	(cd _examples && GOWORK=off "$GO" test -race ./...)
}

vet() {
	run_workspace vet ./...
	echo '==> ./_examples'
	(cd _examples && GOWORK=off "$GO" vet ./...)
"$GO" vet -tags=integration ./test/...
}

examples() {
	(cd _examples && GOWORK=off "$GO" build ./... && GOWORK=off "$GO" vet ./... && GOWORK=off "$GO" test ./...)
}

tidy() {
	local -a modules added
	local module other dependency status
	mapfile -t modules < <(all_modules)
	for module in "${modules[@]}"; do
		echo "==> $module"
		(
			cd "$module"
			added=()
			status=0
			for other in "${modules[@]}"; do
				[[ $other == "$module" ]] && continue
				dependency=$(module_path "$other")
				grep -q "^replace $dependency " go.mod && continue
				added+=("$dependency")
				GOWORK=off "$GO" mod edit -replace "$dependency=$REPO_ROOT/${other#./}" || status=1
			done
			(( status == 0 )) && GOWORK=off "$GO" mod tidy || status=1
			for dependency in "${added[@]}"; do
				GOWORK=off "$GO" mod edit -dropreplace "$dependency" || status=1
			done
			exit "$status"
		)
	done
}

generate() {
"$GO" generate ./...
	(cd test/entstore && "$GO" generate ./...)
	(cd test/gormstore && "$GO" generate ./...)
	(cd test/versionstore && "$GO" generate ./...)
	(cd _examples && GOWORK=off "$GO" generate ./...)
}

api() {
	mkdir -p docs/api
	{
		echo '# Exported surface at the first tag'
		echo
		echo 'Generated by `make api`. It is a baseline, not a description: after v0.1.0 a'
		echo 'line that disappears from this file is a breaking change, and a line that'
		echo 'changes shape is one too. Regenerate and read the diff before every release.'
		echo
		local module package output
		while IFS= read -r module; do
			while IFS= read -r package; do
				output=$("$GO" doc -short "$package" 2>/dev/null | grep -v '^$' || true)
				[[ -n $output ]] || continue
				echo "## $package"
				echo '```go'
				echo "$output"
				echo '```'
				echo
			done < <(cd "$module" && "$GO" list ./... 2>/dev/null | grep -v '/internal/' || true)
		done < <({ printf '.\n'; satellites; })
	} > docs/api/surface.md
	echo 'api: docs/api/surface.md regenerated — read the diff'
}

vuln() {
	local module environment output failed=0
	while IFS= read -r module; do
		printf '%-26s ' "$module"
		environment=()
		[[ $module == ./_examples ]] && environment=(GOWORK=off)
		output=$(cd "$module" && env "${environment[@]}" "$GO" run golang.org/x/vuln/cmd/govulncheck@latest ./... 2>&1) || true
		if grep -q 'No vulnerabilities found' <<<"$output"; then
			echo ok
		else
			echo AFFECTED
			grep -E 'Vulnerability #|Module:|Found in:|Fixed in:|errors with' <<<"$output" | sed 's/^/    /' || true
			failed=1
		fi
	done < <({ printf '.\n'; satellites; printf './test\n./_examples\n'; })
	(( failed == 0 )) || exit 1
	echo 'vuln: ok'
}

version() {
	[[ -n ${V:-} ]] || { echo 'usage: make version V=v0.1.0' >&2; exit 1; }
	local module
	while IFS= read -r module; do
		(cd "$module" && "$GO" mod edit -require="$VV_MODULE@$V")
		echo "$module -> $V"
	done < <(satellites)
	"${BASH_SOURCE[0]}" tidy
}

case ${1:-} in
	unit) unit ;;
	vet) vet ;;
	examples) examples ;;
	tidy) tidy ;;
	main-deps) exec "$SCRIPT_DIR/update-root-module.sh" main ;;
	generate) generate ;;
	ent) (cd test && GOWORK=off "$GO" run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/execquery ./ent/schema) ;;
	api) api ;;
	vuln) vuln ;;
	version) version ;;
	*) echo "unknown module task: ${1:-}" >&2; exit 2 ;;
esac
