#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"
cd "$REPO_ROOT"

run_workspace() {
	local -a args=("$@")
	local module
	while IFS= read -r module; do
		echo "==> $module"
		(cd "$module" && "$GO" "${args[@]}")
	done < <(workspace_modules)
}

# The workspace selects the highest pgx version required by any member. That is
# useful for ordinary integration, but it cannot prove that dbpgx still works
# with the lower version its own go.mod promises to consumers. Test that module
# once more outside go.work while resolving the unreleased root from this tree.
unit_dbpgx_declared_version() {
	(
		cd "$REPO_ROOT/utils/vvdb/dbpgx"
		local root selected
		root=$(realpath --relative-to=. "$REPO_ROOT")
		cleanup() { GOWORK=off "$GO" mod edit -dropreplace "$VV_MODULE"; }
		trap cleanup EXIT
		GOWORK=off "$GO" mod edit -replace "$VV_MODULE=$root"
		selected=$(GOWORK=off "$GO" list -m -f '{{.Version}}' github.com/jackc/pgx/v5)
		[[ $selected == v5.7.6 ]] || {
			echo "dbpgx compatibility gate selected pgx $selected, want v5.7.6" >&2
			return 1
		}
		echo "==> ./utils/vvdb/dbpgx (GOWORK=off, pgx $selected)"
		GOWORK=off "$GO" test -race ./...
	)
}

unit() {
	run_workspace test -race ./...
	unit_dbpgx_declared_version
	echo '==> ./_examples'
	(cd _examples && GOWORK=off "$GO" test -race ./...)
}

vet() {
	run_workspace vet ./...
	echo '==> ./_examples'
	(cd _examples && GOWORK=off "$GO" vet ./...)
	"$GO" vet -tags=integration ./test/...
}

examples() {
	(cd _examples && GOWORK=off "$GO" build ./... && GOWORK=off "$GO" vet ./... && GOWORK=off "$GO" test ./...)
}

# settle leaves one module in the state check-tidy reads it in.
#
# The pass in [tidy] resolves every sibling through a temporary replace, and a
# replaced module is read from a directory — so `go mod tidy` needs no hash for
# one and removes any it finds. Dropping those replaces afterwards leaves a
# go.mod that requires its siblings by version and a go.sum that cannot verify
# them: `make tidy` made the repository untidy, and `make check` then failed on
# the module it had just finished tidying.
#
# That is the shape a build script must not have. The two commands disagreeing
# reads as a stale module cache, which is where somebody looks first and where
# the answer is not.
#
# So the module is tidied once more the way check-tidy will read it: the root
# replaced locally — that is the one replace check-tidy adds itself — and every
# other sibling resolved by version, which is what a released module does.
#
# A failure here is an answer rather than noise. It means this module imports a
# package no published sibling carries yet, and the repository's answer to that
# is a permanent `replace` in the module's own go.mod, of the kind
# auth/access/http/accessfiber carries for the untagged access module.
settle() {
	local root status=0
	root=$(realpath --relative-to=. "$REPO_ROOT")
	GOWORK=off "$GO" mod edit -replace "$VV_MODULE=$root" || return 1
	GOWORK=off "$GO" mod tidy || status=1
	GOWORK=off "$GO" mod edit -dropreplace "$VV_MODULE" || status=1
	return "$status"
}

tidy() {
	local -a modules added
	local module other dependency status
	mapfile -t modules < <(all_modules)
	for module in "${modules[@]}"; do
		echo "==> $module"
		(
			cd "$module"
			added=()
			status=0
			for other in "${modules[@]}"; do
				[[ $other == "$module" ]] && continue
				dependency=$(module_path "$other")
				grep -q "^replace $dependency " go.mod && continue
				added+=("$dependency")
				GOWORK=off "$GO" mod edit -replace "$dependency=$REPO_ROOT/${other#./}" || status=1
			done
			# First pass: every sibling read from the working tree, so a module
			# whose sibling's go.mod changed this morning tidies against that one
			# rather than against whatever was last published.
			(( status == 0 )) && GOWORK=off "$GO" mod tidy || status=1
			for dependency in "${added[@]}"; do
				GOWORK=off "$GO" mod edit -dropreplace "$dependency" || status=1
			done
			# Second pass: the state check-tidy verifies. The three modules that
			# are not satellites are tidied plainly, because that is how
			# check-tidy reads them — the root cannot replace itself, and `test`
			# and `_examples` carry their replaces permanently.
			if (( status == 0 )); then
				case $module in
					. | ./test | ./_examples) GOWORK=off "$GO" mod tidy || status=1 ;;
					*) settle || status=1 ;;
				esac
			fi
			exit "$status"
		)
	done
}

generate() {
	"$GO" generate ./...
	(cd test/entstore && "$GO" generate ./...)
	(cd test/gormstore && "$GO" generate ./...)
	(cd test/versionstore && "$GO" generate ./...)
	(cd _examples && GOWORK=off "$GO" generate ./...)
}

api() {
	mkdir -p docs/api
	{
		echo '# Exported surface at the first tag'
		echo
		echo 'Generated by `make api`. It is a baseline, not a description: after v0.1.0 a'
		echo 'line that disappears from this file is a breaking change, and a line that'
		echo 'changes shape is one too. Regenerate and read the diff before every release.'
		echo
		local module package output
		while IFS= read -r module; do
			while IFS= read -r package; do
				output=$("$GO" doc -short "$package" 2>/dev/null | grep -v '^$' || true)
				[[ -n $output ]] || continue
				echo "## $package"
				echo '```go'
				echo "$output"
				echo '```'
				echo
			done < <(cd "$module" && "$GO" list ./... 2>/dev/null | grep -v '/internal/' || true)
		done < <({ printf '.\n'; satellites; })
	} > docs/api/surface.md
	echo 'api: docs/api/surface.md regenerated — read the diff'
}

vuln() {
	local module environment output failed=0
	while IFS= read -r module; do
		printf '%-26s ' "$module"
		environment=()
		[[ $module == ./_examples ]] && environment=(GOWORK=off)
		output=$(cd "$module" && env "${environment[@]}" "$GO" run golang.org/x/vuln/cmd/govulncheck@latest ./... 2>&1) || true
		if grep -q 'No vulnerabilities found' <<<"$output"; then
			echo ok
		else
			echo AFFECTED
			grep -E 'Vulnerability #|Module:|Found in:|Fixed in:|errors with' <<<"$output" | sed 's/^/    /' || true
			failed=1
		fi
	done < <({ printf '.\n'; satellites; printf './test\n./_examples\n'; })
	(( failed == 0 )) || exit 1
	echo 'vuln: ok'
}

version() {
	[[ -n ${V:-} ]] || { echo 'usage: make version V=v0.1.0' >&2; exit 1; }
	local module
	while IFS= read -r module; do
		(cd "$module" && "$GO" mod edit -require="$VV_MODULE@$V")
		echo "$module -> $V"
	done < <(satellites)
	(cd "$REPO_ROOT" && "$GO" run ./cmd/vv-otel-gen -write-scope-version "$V" -registry internal/otelreg/registry.json -out otel/schema_gen.go)
	"${BASH_SOURCE[0]}" tidy
}

case ${1:-} in
	unit) unit ;;
	vet) vet ;;
	examples) examples ;;
	tidy) tidy ;;
	main-deps) exec "$SCRIPT_DIR/update-root-module.sh" main ;;
	generate) generate ;;
	ent) (cd test && GOWORK=off "$GO" run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/execquery ./ent/schema) ;;
	api) api ;;
	vuln) vuln ;;
	version) version ;;
	*) echo "unknown module task: ${1:-}" >&2; exit 2 ;;
esac
