// Command ent-pgx-gin is vv with ent, pgx's database/sql driver and the
// Gin binding.
//
// The data layer is identical to the other ent-over-Postgres example: the
// same generated entity, the same Products declaration, the same
// query.Config. What changes is only the mount and the engine — this file
// exists to make that diff visible. The one behavioural difference a caller
// can see is that Gin decodes request bodies as JSON only; the Fiber binding
// also accepts XML and form encodings because Fiber's binder dispatches on
// Content-Type.
//
//	go get github.com/frostgrove/vv
//	go get github.com/frostgrove/vv/crud/adapter/crudsql
//	go get github.com/frostgrove/vv/crud/http/crudgin
//	go get entgo.io/ent
//	go get github.com/jackc/pgx/v5
//
// Run it with the repository's own databases up (`make up` at the root):
//
//	go run ./ent-pgx-gin
//	curl 'localhost:8080/products?f=price:gte:100&sort=-price'
package main

import (
	"context"
	"database/sql"
	"flag"
	"log"
	"time"

	entsql "entgo.io/ent/dialect/sql"
	"github.com/gin-gonic/gin"
	_ "github.com/jackc/pgx/v5/stdlib"

	"github.com/frostgrove/vv/_examples/entmodel"
	"github.com/frostgrove/vv/_examples/entstore"
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/adapter/crudsql"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/http/crudgin"
	"github.com/frostgrove/vv/crud/query"
	"github.com/frostgrove/vv/crud/sqlrepo"
)

// The model is entmodel.Product — generated by ent from
// entmodel/schema/product.go, unmodified. entstore.ProductUpdate and
// entstore.Product_ are generated from that entity by cmd/vv; see
// entstore/doc.go for the command that produced them.

// Products is validated when this package initialises: a mistyped tag, a DTO
// field the model lacks or a wrong ID type fails here rather than at request
// time.
var Products = sqlrepo.Define[entmodel.Product, int64, entstore.ProductUpdate]("products",
	sqlrepo.DefaultLimit(20),
	sqlrepo.MaxLimit(100),
	sqlrepo.DefaultSort(crud.Desc("CreatedAt")),
)

const dsn = "postgres://vv:vv@localhost:55432/vv?sslmode=disable"

func main() {
	addr := flag.String("addr", ":8080", "listen address")
	flag.Parse()

	db, err := sql.Open("pgx", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	if err := bootstrap(ctx, db); err != nil {
		log.Fatal(err)
	}

	// The same *sql.DB backs both halves: ent's client does the bootstrap and
	// the seed, crudsql.Postgres does everything the repository runs
	// afterwards. Neither owns the connection; vv never dials one itself.
	repo := specs.Executor(Products.Bind(crudsql.Postgres(db)))

	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	crudgin.New(repo,
		crudgin.WithQuery[entmodel.Product, int64, entstore.ProductUpdate](&query.Config{
			Filterable: []string{"Sku", "Name", "Price", "Stock", "Active", "CreatedAt"},
			Sortable:   []string{"Price", "Name", "CreatedAt"},
			Searchable: []string{"Sku", "Name"},
		}),
		// ent's Go-side defaults never run on an vv write, and ent's
		// generated struct carries no `db` tags, so there is nowhere to mark
		// created_at as the server's to fill. vv maps it like any other
		// column and writes what the struct holds — the zero time on a create,
		// and the column's DEFAULT never fires because the INSERT names it.
		// This is the second of the three ways out that
		// docs/usage-guides/ent.md §16 lists, and the only one available when
		// the model is generated code you must not edit.
		crudgin.BeforeSave[entmodel.Product, int64, entstore.ProductUpdate](
			func(_ *gin.Context, p *entmodel.Product) error {
				if p.CreatedAt.IsZero() {
					p.CreatedAt = time.Now()
				}
				return nil
			}),
	).Mount(r, "/products")

	log.Printf("ent + crudsql + gin on %s — try /products?f=price:gte:100&sort=-price", *addr)
	log.Fatal(r.Run(*addr))
}

// bootstrap creates the table through ent's own migration and reseeds it, so
// the example runs against a known set of rows every time. A real application
// would use its own migrations instead of Schema.Create.
func bootstrap(ctx context.Context, db *sql.DB) error {
	// Closing the ent client closes the driver it wraps, and entsql.OpenDB
	// wraps this *sql.DB directly rather than a connection of its own — so the
	// client is never closed here. main owns db and closes it on the way out.
	client := entmodel.NewClient(entmodel.Driver(entsql.OpenDB("postgres", db)))

	if err := client.Schema.Create(ctx); err != nil {
		return err
	}
	if _, err := client.Product.Delete().Exec(ctx); err != nil {
		return err
	}

	stock := 40
	if _, err := client.Product.Create().SetSku("BOLT-1").SetName("hex bolt").SetPrice(250).SetStock(stock).Save(ctx); err != nil {
		return err
	}
	if _, err := client.Product.Create().SetSku("NUT-1").SetName("hex nut").SetPrice(120).Save(ctx); err != nil {
		return err
	}
	stock = 900
	if _, err := client.Product.Create().SetSku("WSH-1").SetName("washer").SetPrice(35).SetStock(stock).Save(ctx); err != nil {
		return err
	}
	return nil
}
