// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/frostgrove/vv/test/ent/predicate"
	"github.com/frostgrove/vv/test/ent/user"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUser = "User"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	tenant_id     *int64
	addtenant_id  *int64
	email         *string
	name          *string
	age           *int
	addage        *int
	active        *bool
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*User, error)
	predicates    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, options ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range options {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int64) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (this UserMutation) Client() *Client {
	client := &Client{config: this.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (this UserMutation) Tx() (*Tx, error) {
	if _, ok := this.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: this.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (this *UserMutation) SetID(id int64) {
	this.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (this *UserMutation) ID() (id int64, exists bool) {
	if this.id == nil {
		return
	}
	return *this.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (this *UserMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case this.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := this.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case this.op.Is(OpUpdate | OpDelete):
		return this.Client().User.Query().Where(this.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", this.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (this *UserMutation) SetTenantID(i int64) {
	this.tenant_id = &i
	this.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (this *UserMutation) TenantID() (r int64, exists bool) {
	v := this.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (this *UserMutation) OldTenantID(ctx context.Context) (v int64, err error) {
	if !this.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if this.id == nil || this.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := this.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (this *UserMutation) AddTenantID(i int64) {
	if this.addtenant_id != nil {
		*this.addtenant_id += i
	} else {
		this.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (this *UserMutation) AddedTenantID() (r int64, exists bool) {
	v := this.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (this *UserMutation) ResetTenantID() {
	this.tenant_id = nil
	this.addtenant_id = nil
}

// SetEmail sets the "email" field.
func (this *UserMutation) SetEmail(s string) {
	this.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (this *UserMutation) Email() (r string, exists bool) {
	v := this.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (this *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !this.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if this.id == nil || this.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := this.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (this *UserMutation) ResetEmail() {
	this.email = nil
}

// SetName sets the "name" field.
func (this *UserMutation) SetName(s string) {
	this.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (this *UserMutation) Name() (r string, exists bool) {
	v := this.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (this *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !this.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if this.id == nil || this.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := this.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (this *UserMutation) ResetName() {
	this.name = nil
}

// SetAge sets the "age" field.
func (this *UserMutation) SetAge(i int) {
	this.age = &i
	this.addage = nil
}

// Age returns the value of the "age" field in the mutation.
func (this *UserMutation) Age() (r int, exists bool) {
	v := this.age
	if v == nil {
		return
	}
	return *v, true
}

// OldAge returns the old "age" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (this *UserMutation) OldAge(ctx context.Context) (v *int, err error) {
	if !this.op.Is(OpUpdateOne) {
		return v, errors.New("OldAge is only allowed on UpdateOne operations")
	}
	if this.id == nil || this.oldValue == nil {
		return v, errors.New("OldAge requires an ID field in the mutation")
	}
	oldValue, err := this.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAge: %w", err)
	}
	return oldValue.Age, nil
}

// AddAge adds i to the "age" field.
func (this *UserMutation) AddAge(i int) {
	if this.addage != nil {
		*this.addage += i
	} else {
		this.addage = &i
	}
}

// AddedAge returns the value that was added to the "age" field in this mutation.
func (this *UserMutation) AddedAge() (r int, exists bool) {
	v := this.addage
	if v == nil {
		return
	}
	return *v, true
}

// ClearAge clears the value of the "age" field.
func (this *UserMutation) ClearAge() {
	this.age = nil
	this.addage = nil
	this.clearedFields[user.FieldAge] = struct{}{}
}

// AgeCleared returns if the "age" field was cleared in this mutation.
func (this *UserMutation) AgeCleared() bool {
	_, ok := this.clearedFields[user.FieldAge]
	return ok
}

// ResetAge resets all changes to the "age" field.
func (this *UserMutation) ResetAge() {
	this.age = nil
	this.addage = nil
	delete(this.clearedFields, user.FieldAge)
}

// SetActive sets the "active" field.
func (this *UserMutation) SetActive(b bool) {
	this.active = &b
}

// Active returns the value of the "active" field in the mutation.
func (this *UserMutation) Active() (r bool, exists bool) {
	v := this.active
	if v == nil {
		return
	}
	return *v, true
}

// OldActive returns the old "active" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (this *UserMutation) OldActive(ctx context.Context) (v bool, err error) {
	if !this.op.Is(OpUpdateOne) {
		return v, errors.New("OldActive is only allowed on UpdateOne operations")
	}
	if this.id == nil || this.oldValue == nil {
		return v, errors.New("OldActive requires an ID field in the mutation")
	}
	oldValue, err := this.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActive: %w", err)
	}
	return oldValue.Active, nil
}

// ResetActive resets all changes to the "active" field.
func (this *UserMutation) ResetActive() {
	this.active = nil
}

// SetCreatedAt sets the "created_at" field.
func (this *UserMutation) SetCreatedAt(t time.Time) {
	this.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (this *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := this.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (this *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !this.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if this.id == nil || this.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := this.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (this *UserMutation) ResetCreatedAt() {
	this.created_at = nil
}

// Where appends a list predicates to the UserMutation builder.
func (this *UserMutation) Where(ps ...predicate.User) {
	this.predicates = append(this.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (this *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	this.Where(p...)
}

// Op returns the operation name.
func (this *UserMutation) Op() Op {
	return this.op
}

// SetOp allows setting the mutation operation.
func (this *UserMutation) SetOp(op Op) {
	this.op = op
}

// Type returns the node type of this mutation (User).
func (this *UserMutation) Type() string {
	return this.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (this *UserMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if this.tenant_id != nil {
		fields = append(fields, user.FieldTenantID)
	}
	if this.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if this.name != nil {
		fields = append(fields, user.FieldName)
	}
	if this.age != nil {
		fields = append(fields, user.FieldAge)
	}
	if this.active != nil {
		fields = append(fields, user.FieldActive)
	}
	if this.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (this *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldTenantID:
		return this.TenantID()
	case user.FieldEmail:
		return this.Email()
	case user.FieldName:
		return this.Name()
	case user.FieldAge:
		return this.Age()
	case user.FieldActive:
		return this.Active()
	case user.FieldCreatedAt:
		return this.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (this *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldTenantID:
		return this.OldTenantID(ctx)
	case user.FieldEmail:
		return this.OldEmail(ctx)
	case user.FieldName:
		return this.OldName(ctx)
	case user.FieldAge:
		return this.OldAge(ctx)
	case user.FieldActive:
		return this.OldActive(ctx)
	case user.FieldCreatedAt:
		return this.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (this *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.SetTenantID(v)
		return nil
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.SetEmail(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.SetName(v)
		return nil
	case user.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.SetAge(v)
		return nil
	case user.FieldActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.SetActive(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (this *UserMutation) AddedFields() []string {
	var fields []string
	if this.addtenant_id != nil {
		fields = append(fields, user.FieldTenantID)
	}
	if this.addage != nil {
		fields = append(fields, user.FieldAge)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (this *UserMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case user.FieldTenantID:
		return this.AddedTenantID()
	case user.FieldAge:
		return this.AddedAge()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (this *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	case user.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.AddTenantID(v)
		return nil
	case user.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		this.AddAge(v)
		return nil
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (this *UserMutation) ClearedFields() []string {
	var fields []string
	if this.FieldCleared(user.FieldAge) {
		fields = append(fields, user.FieldAge)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (this *UserMutation) FieldCleared(name string) bool {
	_, ok := this.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (this *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldAge:
		this.ClearAge()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (this *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldTenantID:
		this.ResetTenantID()
		return nil
	case user.FieldEmail:
		this.ResetEmail()
		return nil
	case user.FieldName:
		this.ResetName()
		return nil
	case user.FieldAge:
		this.ResetAge()
		return nil
	case user.FieldActive:
		this.ResetActive()
		return nil
	case user.FieldCreatedAt:
		this.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (this *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (this *UserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (this *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (this *UserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (this *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (this *UserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (this *UserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (this *UserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown User edge %s", name)
}
