// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/test/ent/predicate"
	"github.com/frostgrove/vv/test/ent/user"
)

// UserQuery is the builder for querying User entities.
type UserQuery struct {
	config
	ctx        *QueryContext
	order      []user.OrderOption
	inters     []Interceptor
	predicates []predicate.User
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserQuery builder.
func (this *UserQuery) Where(ps ...predicate.User) *UserQuery {
	this.predicates = append(this.predicates, ps...)
	return this
}

// Limit the number of records to be returned by this query.
func (this *UserQuery) Limit(limit int) *UserQuery {
	this.ctx.Limit = &limit
	return this
}

// Offset to start from.
func (this *UserQuery) Offset(offset int) *UserQuery {
	this.ctx.Offset = &offset
	return this
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (this *UserQuery) Unique(unique bool) *UserQuery {
	this.ctx.Unique = &unique
	return this
}

// Order specifies how the records should be ordered.
func (this *UserQuery) Order(o ...user.OrderOption) *UserQuery {
	this.order = append(this.order, o...)
	return this
}

// First returns the first User entity from the query.
// Returns a *NotFoundError when no User was found.
func (this *UserQuery) First(ctx context.Context) (*User, error) {
	nodes, err := this.Limit(1).All(setContextOp(ctx, this.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{user.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (this *UserQuery) FirstX(ctx context.Context) *User {
	node, err := this.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first User ID from the query.
// Returns a *NotFoundError when no User ID was found.
func (this *UserQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = this.Limit(1).IDs(setContextOp(ctx, this.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{user.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (this *UserQuery) FirstIDX(ctx context.Context) int64 {
	id, err := this.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single User entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one User entity is found.
// Returns a *NotFoundError when no User entities are found.
func (this *UserQuery) Only(ctx context.Context) (*User, error) {
	nodes, err := this.Limit(2).All(setContextOp(ctx, this.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{user.Label}
	default:
		return nil, &NotSingularError{user.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (this *UserQuery) OnlyX(ctx context.Context) *User {
	node, err := this.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only User ID in the query.
// Returns a *NotSingularError when more than one User ID is found.
// Returns a *NotFoundError when no entities are found.
func (this *UserQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = this.Limit(2).IDs(setContextOp(ctx, this.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{user.Label}
	default:
		err = &NotSingularError{user.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (this *UserQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := this.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Users.
func (this *UserQuery) All(ctx context.Context) ([]*User, error) {
	ctx = setContextOp(ctx, this.ctx, ent.OpQueryAll)
	if err := this.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*User, *UserQuery]()
	return withInterceptors[[]*User](ctx, this, qr, this.inters)
}

// AllX is like All, but panics if an error occurs.
func (this *UserQuery) AllX(ctx context.Context) []*User {
	nodes, err := this.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of User IDs.
func (this *UserQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if this.ctx.Unique == nil && this.path != nil {
		this.Unique(true)
	}
	ctx = setContextOp(ctx, this.ctx, ent.OpQueryIDs)
	if err = this.Select(user.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (this *UserQuery) IDsX(ctx context.Context) []int64 {
	ids, err := this.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (this *UserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, this.ctx, ent.OpQueryCount)
	if err := this.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, this, querierCount[*UserQuery](), this.inters)
}

// CountX is like Count, but panics if an error occurs.
func (this *UserQuery) CountX(ctx context.Context) int {
	count, err := this.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (this *UserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, this.ctx, ent.OpQueryExist)
	switch _, err := this.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (this *UserQuery) ExistX(ctx context.Context) bool {
	exist, err := this.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (this *UserQuery) Clone() *UserQuery {
	if this == nil {
		return nil
	}
	return &UserQuery{
		config:     this.config,
		ctx:        this.ctx.Clone(),
		order:      append([]user.OrderOption{}, this.order...),
		inters:     append([]Interceptor{}, this.inters...),
		predicates: append([]predicate.User{}, this.predicates...),
		// clone intermediate query.
		sql:  this.sql.Clone(),
		path: this.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int64 `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.User.Query().
//		GroupBy(user.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (this *UserQuery) GroupBy(field string, fields ...string) *UserGroupBy {
	this.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserGroupBy{build: this}
	grbuild.flds = &this.ctx.Fields
	grbuild.label = user.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int64 `json:"tenant_id,omitempty"`
//	}
//
//	client.User.Query().
//		Select(user.FieldTenantID).
//		Scan(ctx, &v)
func (this *UserQuery) Select(fields ...string) *UserSelect {
	this.ctx.Fields = append(this.ctx.Fields, fields...)
	sbuild := &UserSelect{UserQuery: this}
	sbuild.label = user.Label
	sbuild.flds, sbuild.scan = &this.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserSelect configured with the given aggregations.
func (this *UserQuery) Aggregate(fns ...AggregateFunc) *UserSelect {
	return this.Select().Aggregate(fns...)
}

func (this *UserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range this.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, this); err != nil {
				return err
			}
		}
	}
	for _, f := range this.ctx.Fields {
		if !user.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if this.path != nil {
		prev, err := this.path(ctx)
		if err != nil {
			return err
		}
		this.sql = prev
	}
	return nil
}

func (this *UserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*User, error) {
	var (
		nodes = []*User{}
		_spec = this.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*User).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &User{config: this.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, this.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (this *UserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := this.querySpec()
	_spec.Node.Columns = this.ctx.Fields
	if len(this.ctx.Fields) > 0 {
		_spec.Unique = this.ctx.Unique != nil && *this.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, this.driver, _spec)
}

func (this *UserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	_spec.From = this.sql
	if unique := this.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if this.path != nil {
		_spec.Unique = true
	}
	if fields := this.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for i := range fields {
			if fields[i] != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := this.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := this.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := this.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := this.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (this *UserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(this.driver.Dialect())
	t1 := builder.Table(user.Table)
	columns := this.ctx.Fields
	if len(columns) == 0 {
		columns = user.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if this.sql != nil {
		selector = this.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if this.ctx.Unique != nil && *this.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range this.predicates {
		p(selector)
	}
	for _, p := range this.order {
		p(selector)
	}
	if offset := this.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := this.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserGroupBy is the group-by builder for User entities.
type UserGroupBy struct {
	selector
	build *UserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (this *UserGroupBy) Aggregate(fns ...AggregateFunc) *UserGroupBy {
	this.fns = append(this.fns, fns...)
	return this
}

// Scan applies the selector query and scans the result into the given value.
func (this *UserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, this.build.ctx, ent.OpQueryGroupBy)
	if err := this.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserQuery, *UserGroupBy](ctx, this.build, this, this.build.inters, v)
}

func (this *UserGroupBy) sqlScan(ctx context.Context, root *UserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(this.fns))
	for _, fn := range this.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*this.flds)+len(this.fns))
		for _, f := range *this.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*this.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := this.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserSelect is the builder for selecting fields of User entities.
type UserSelect struct {
	*UserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (this *UserSelect) Aggregate(fns ...AggregateFunc) *UserSelect {
	this.fns = append(this.fns, fns...)
	return this
}

// Scan applies the selector query and scans the result into the given value.
func (this *UserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, this.ctx, ent.OpQuerySelect)
	if err := this.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserQuery, *UserSelect](ctx, this.UserQuery, this, this.inters, v)
}

func (this *UserSelect) sqlScan(ctx context.Context, root *UserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(this.fns))
	for _, fn := range this.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*this.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := this.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
