// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/test/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (this *UserCreate) SetTenantID(v int64) *UserCreate {
	this.mutation.SetTenantID(v)
	return this
}

// SetEmail sets the "email" field.
func (this *UserCreate) SetEmail(v string) *UserCreate {
	this.mutation.SetEmail(v)
	return this
}

// SetName sets the "name" field.
func (this *UserCreate) SetName(v string) *UserCreate {
	this.mutation.SetName(v)
	return this
}

// SetAge sets the "age" field.
func (this *UserCreate) SetAge(v int) *UserCreate {
	this.mutation.SetAge(v)
	return this
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (this *UserCreate) SetNillableAge(v *int) *UserCreate {
	if v != nil {
		this.SetAge(*v)
	}
	return this
}

// SetActive sets the "active" field.
func (this *UserCreate) SetActive(v bool) *UserCreate {
	this.mutation.SetActive(v)
	return this
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (this *UserCreate) SetNillableActive(v *bool) *UserCreate {
	if v != nil {
		this.SetActive(*v)
	}
	return this
}

// SetCreatedAt sets the "created_at" field.
func (this *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	this.mutation.SetCreatedAt(v)
	return this
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (this *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		this.SetCreatedAt(*v)
	}
	return this
}

// SetID sets the "id" field.
func (this *UserCreate) SetID(v int64) *UserCreate {
	this.mutation.SetID(v)
	return this
}

// Mutation returns the UserMutation object of the builder.
func (this *UserCreate) Mutation() *UserMutation {
	return this.mutation
}

// Save creates the User in the database.
func (this *UserCreate) Save(ctx context.Context) (*User, error) {
	this.defaults()
	return withHooks(ctx, this.sqlSave, this.mutation, this.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (this *UserCreate) SaveX(ctx context.Context) *User {
	v, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (this *UserCreate) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *UserCreate) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (this *UserCreate) defaults() {
	if _, ok := this.mutation.Active(); !ok {
		v := user.DefaultActive
		this.mutation.SetActive(v)
	}
	if _, ok := this.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		this.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (this *UserCreate) check() error {
	if _, ok := this.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "User.tenant_id"`)}
	}
	if _, ok := this.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if _, ok := this.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if _, ok := this.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "User.active"`)}
	}
	if _, ok := this.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	return nil
}

func (this *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := this.check(); err != nil {
		return nil, err
	}
	_node, _spec := this.createSpec()
	if err := sqlgraph.CreateNode(ctx, this.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{message: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	this.mutation.id = &_node.ID
	this.mutation.done = true
	return _node, nil
}

func (this *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: this.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	)
	if id, ok := this.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := this.mutation.TenantID(); ok {
		_spec.SetField(user.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := this.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := this.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := this.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
		_node.Age = &value
	}
	if value, ok := this.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := this.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (this *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if this.err != nil {
		return nil, this.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(this.builders))
	nodes := make([]*User, len(this.builders))
	mutators := make([]Mutator, len(this.builders))
	for i := range this.builders {
		func(i int, root context.Context) {
			builder := this.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, this.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, this.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{message: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, this.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (this *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (this *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *UserCreateBulk) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}
