// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/test/ent/predicate"
	"github.com/frostgrove/vv/test/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (this *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	this.mutation.Where(ps...)
	return this
}

// SetTenantID sets the "tenant_id" field.
func (this *UserUpdate) SetTenantID(v int64) *UserUpdate {
	this.mutation.ResetTenantID()
	this.mutation.SetTenantID(v)
	return this
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (this *UserUpdate) SetNillableTenantID(v *int64) *UserUpdate {
	if v != nil {
		this.SetTenantID(*v)
	}
	return this
}

// AddTenantID adds value to the "tenant_id" field.
func (this *UserUpdate) AddTenantID(v int64) *UserUpdate {
	this.mutation.AddTenantID(v)
	return this
}

// SetEmail sets the "email" field.
func (this *UserUpdate) SetEmail(v string) *UserUpdate {
	this.mutation.SetEmail(v)
	return this
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (this *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		this.SetEmail(*v)
	}
	return this
}

// SetName sets the "name" field.
func (this *UserUpdate) SetName(v string) *UserUpdate {
	this.mutation.SetName(v)
	return this
}

// SetNillableName sets the "name" field if the given value is not nil.
func (this *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		this.SetName(*v)
	}
	return this
}

// SetAge sets the "age" field.
func (this *UserUpdate) SetAge(v int) *UserUpdate {
	this.mutation.ResetAge()
	this.mutation.SetAge(v)
	return this
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (this *UserUpdate) SetNillableAge(v *int) *UserUpdate {
	if v != nil {
		this.SetAge(*v)
	}
	return this
}

// AddAge adds value to the "age" field.
func (this *UserUpdate) AddAge(v int) *UserUpdate {
	this.mutation.AddAge(v)
	return this
}

// ClearAge clears the value of the "age" field.
func (this *UserUpdate) ClearAge() *UserUpdate {
	this.mutation.ClearAge()
	return this
}

// SetActive sets the "active" field.
func (this *UserUpdate) SetActive(v bool) *UserUpdate {
	this.mutation.SetActive(v)
	return this
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (this *UserUpdate) SetNillableActive(v *bool) *UserUpdate {
	if v != nil {
		this.SetActive(*v)
	}
	return this
}

// SetCreatedAt sets the "created_at" field.
func (this *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	this.mutation.SetCreatedAt(v)
	return this
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (this *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		this.SetCreatedAt(*v)
	}
	return this
}

// Mutation returns the UserMutation object of the builder.
func (this *UserUpdate) Mutation() *UserMutation {
	return this.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (this *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, this.sqlSave, this.mutation, this.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (this *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (this *UserUpdate) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *UserUpdate) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}

func (this *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := this.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := this.mutation.TenantID(); ok {
		_spec.SetField(user.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := this.mutation.AddedTenantID(); ok {
		_spec.AddField(user.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := this.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := this.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := this.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := this.mutation.AddedAge(); ok {
		_spec.AddField(user.FieldAge, field.TypeInt, value)
	}
	if this.mutation.AgeCleared() {
		_spec.ClearField(user.FieldAge, field.TypeInt)
	}
	if value, ok := this.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if value, ok := this.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, this.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{message: err.Error(), wrap: err}
		}
		return 0, err
	}
	this.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetTenantID sets the "tenant_id" field.
func (this *UserUpdateOne) SetTenantID(v int64) *UserUpdateOne {
	this.mutation.ResetTenantID()
	this.mutation.SetTenantID(v)
	return this
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (this *UserUpdateOne) SetNillableTenantID(v *int64) *UserUpdateOne {
	if v != nil {
		this.SetTenantID(*v)
	}
	return this
}

// AddTenantID adds value to the "tenant_id" field.
func (this *UserUpdateOne) AddTenantID(v int64) *UserUpdateOne {
	this.mutation.AddTenantID(v)
	return this
}

// SetEmail sets the "email" field.
func (this *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	this.mutation.SetEmail(v)
	return this
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (this *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		this.SetEmail(*v)
	}
	return this
}

// SetName sets the "name" field.
func (this *UserUpdateOne) SetName(v string) *UserUpdateOne {
	this.mutation.SetName(v)
	return this
}

// SetNillableName sets the "name" field if the given value is not nil.
func (this *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		this.SetName(*v)
	}
	return this
}

// SetAge sets the "age" field.
func (this *UserUpdateOne) SetAge(v int) *UserUpdateOne {
	this.mutation.ResetAge()
	this.mutation.SetAge(v)
	return this
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (this *UserUpdateOne) SetNillableAge(v *int) *UserUpdateOne {
	if v != nil {
		this.SetAge(*v)
	}
	return this
}

// AddAge adds value to the "age" field.
func (this *UserUpdateOne) AddAge(v int) *UserUpdateOne {
	this.mutation.AddAge(v)
	return this
}

// ClearAge clears the value of the "age" field.
func (this *UserUpdateOne) ClearAge() *UserUpdateOne {
	this.mutation.ClearAge()
	return this
}

// SetActive sets the "active" field.
func (this *UserUpdateOne) SetActive(v bool) *UserUpdateOne {
	this.mutation.SetActive(v)
	return this
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (this *UserUpdateOne) SetNillableActive(v *bool) *UserUpdateOne {
	if v != nil {
		this.SetActive(*v)
	}
	return this
}

// SetCreatedAt sets the "created_at" field.
func (this *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	this.mutation.SetCreatedAt(v)
	return this
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (this *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		this.SetCreatedAt(*v)
	}
	return this
}

// Mutation returns the UserMutation object of the builder.
func (this *UserUpdateOne) Mutation() *UserMutation {
	return this.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (this *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	this.mutation.Where(ps...)
	return this
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (this *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	this.fields = append([]string{field}, fields...)
	return this
}

// Save executes the query and returns the updated User entity.
func (this *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, this.sqlSave, this.mutation, this.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (this *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := this.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (this *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := this.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (this *UserUpdateOne) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}

func (this *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	id, ok := this.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := this.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := this.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := this.mutation.TenantID(); ok {
		_spec.SetField(user.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := this.mutation.AddedTenantID(); ok {
		_spec.AddField(user.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := this.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := this.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := this.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := this.mutation.AddedAge(); ok {
		_spec.AddField(user.FieldAge, field.TypeInt, value)
	}
	if this.mutation.AgeCleared() {
		_spec.ClearField(user.FieldAge, field.TypeInt)
	}
	if value, ok := this.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if value, ok := this.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &User{config: this.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, this.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{message: err.Error(), wrap: err}
		}
		return nil, err
	}
	this.mutation.done = true
	return _node, nil
}
