// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/frostgrove/vv/test/ent/predicate"
	"github.com/frostgrove/vv/test/ent/user"
)

// UserDelete is the builder for deleting a User entity.
type UserDelete struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserDelete builder.
func (this *UserDelete) Where(ps ...predicate.User) *UserDelete {
	this.mutation.Where(ps...)
	return this
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (this *UserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, this.sqlExec, this.mutation, this.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (this *UserDelete) ExecX(ctx context.Context) int {
	n, err := this.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (this *UserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := this.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, this.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{message: err.Error(), wrap: err}
	}
	this.mutation.done = true
	return affected, err
}

// UserDeleteOne is the builder for deleting a single User entity.
type UserDeleteOne struct {
	_d *UserDelete
}

// Where appends a list predicates to the UserDelete builder.
func (this *UserDeleteOne) Where(ps ...predicate.User) *UserDeleteOne {
	this._d.mutation.Where(ps...)
	return this
}

// Exec executes the deletion query.
func (this *UserDeleteOne) Exec(ctx context.Context) error {
	n, err := this._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{user.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (this *UserDeleteOne) ExecX(ctx context.Context) {
	if err := this.Exec(ctx); err != nil {
		panic(err)
	}
}
