package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

func (g *generator) render() ([]byte, error) {
	var body bytes.Buffer
	needCrud, needSpecs, needTime := false, false, false

	for _, name := range g.order {
		m := g.models[name]
		if g.withDTO {
			s, used := g.renderDTO(m)
			body.WriteString(s)
			needCrud = needCrud || used.crud
			needTime = needTime || used.time
		}
		if g.withMeta {
			s, used := g.renderMetamodel(m)
			body.WriteString(s)
			needSpecs = needSpecs || used.specs
			needTime = needTime || used.time
		}
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by rxcrud. DO NOT EDIT.\n\npackage %s\n\n", g.pkg)

	var imports []string
	if needTime {
		imports = append(imports, `"time"`)
	}
	if needCrud {
		imports = append(imports, fmt.Sprintf("%q", g.crudPkg))
	}
	if needSpecs {
		imports = append(imports, fmt.Sprintf("%q", g.specsPkg))
	}
	if g.modelImport != "" {
		imports = append(imports, fmt.Sprintf("%q", g.modelImport))
	}
	// Anything else the model types reference has to come along too.
	for alias, path := range g.extraImports() {
		if alias == "time" {
			continue
		}
		imports = append(imports, fmt.Sprintf("%q", path))
	}
	if len(imports) > 0 {
		sort.Strings(imports)
		out.WriteString("import (\n")
		for _, imp := range imports {
			fmt.Fprintf(&out, "\t%s\n", imp)
		}
		out.WriteString(")\n\n")
	}
	out.Write(body.Bytes())

	src, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated code does not parse: %w\n%s", err, out.String())
	}
	return src, nil
}

type used struct{ crud, specs, time bool }

// extraImports finds the packages the generated types still need — a uuid or
// decimal column type would otherwise dangle.
func (g *generator) extraImports() map[string]string {
	need := map[string]string{}
	for _, name := range g.order {
		for _, f := range g.models[name].Fields {
			if f.Skip || f.isRelation() {
				continue
			}
			e, _ := elem(f.Type)
			if pkg, _, ok := strings.Cut(e, "."); ok {
				if path, known := g.imports[pkg]; known {
					need[pkg] = path
				}
			}
		}
	}
	return need
}

// ---------------------------------------------------------------------------
// update DTO

func (g *generator) renderDTO(m *model) (string, used) {
	var b strings.Builder
	var u used

	fmt.Fprintf(&b, "// %sUpdate is the partial-update DTO for %s.\n", m.Name, g.qual(m.Name))
	fmt.Fprintf(&b, "// A pointer field is optional; a crud.Opt field is optional and nullable,\n")
	fmt.Fprintf(&b, "// so an absent key, an explicit null and a value stay three different things.\n")
	fmt.Fprintf(&b, "type %sUpdate struct {\n", m.Name)

	for _, f := range m.Fields {
		// The version column is left out for the same reason the primary key is:
		// the repository owns it. A DTO that names it is refused at Define time,
		// so emitting it would hand the caller a package that panics at start-up.
		if f.Skip || f.isRelation() || f.PK || f.Generated || f.Immutable || f.Version {
			continue
		}
		typ := dtoType(f.Type)
		json := lowerFirst(f.Name)
		omit := "omitempty"
		if strings.HasPrefix(typ, "crud.Opt[") {
			omit = "omitzero"
			u.crud = true
		}
		if strings.Contains(typ, "time.Time") {
			u.time = true
		}
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", f.Name, typ, json+","+omit)
	}
	b.WriteString("}\n\n")
	return b.String(), u
}

// ---------------------------------------------------------------------------
// metamodel

func (g *generator) renderMetamodel(m *model) (string, used) {
	var b strings.Builder
	var u used
	u.specs = true

	emitted := map[string]bool{}
	g.renderAttrs(&b, m, m, "", 0, []string{m.Name}, emitted, &u)

	fmt.Fprintf(&b, "// %s_ is the metamodel of %s: typed, path-aware field references.\n", m.Name, m.Name)
	fmt.Fprintf(&b, "// It is validated against the model at package initialisation.\n")
	fmt.Fprintf(&b, "var %s_ = specs.Metamodel[%s, %sAttrs]()\n\n", m.Name, g.qual(m.Name), m.Name)
	return b.String(), u
}

// renderAttrs writes the attribute struct for `on`, expressed as attributes of
// the root model, and recurses into relations up to the configured depth.
func (g *generator) renderAttrs(b *strings.Builder, root, on *model, suffix string, level int, path []string, emitted map[string]bool, u *used) {
	typeName := root.Name + suffix + "Attrs"
	if emitted[typeName] {
		return
	}
	emitted[typeName] = true

	var nested []struct {
		field  field
		target *model
		suffix string
	}

	var body strings.Builder
	for _, f := range on.Fields {
		if f.Skip {
			continue
		}
		if f.isRelation() {
			if level+1 >= g.depth {
				continue
			}
			target, slice := relElem(f.Type)
			_ = slice
			tm, ok := g.models[target]
			if !ok {
				continue // the related model lives in another package
			}
			// Do not walk back into a model already on this path: Article ->
			// Author -> Articles -> … has no end.
			cycle := false
			for _, seen := range path {
				if seen == target {
					cycle = true
					break
				}
			}
			if cycle {
				continue
			}
			sub := suffix + f.Name
			fmt.Fprintf(&body, "\t%s %s%sAttrs\n", f.Name, root.Name, sub)
			nested = append(nested, struct {
				field  field
				target *model
				suffix string
			}{f, tm, sub})
			continue
		}
		if strings.Contains(f.Type, "time.Time") {
			u.time = true
		}
		fmt.Fprintf(&body, "\t%s %s\n", f.Name, attrType("specs", g.qual(root.Name), f.Type))
	}

	// Emit the nested structs first so the file reads top-down.
	for _, n := range nested {
		g.renderAttrs(b, root, n.target, n.suffix, level+1, append(path, n.target.Name), emitted, u)
	}

	if suffix == "" {
		fmt.Fprintf(b, "// %sAttrs is the generated metamodel shape for %s.\n", root.Name, root.Name)
	} else {
		fmt.Fprintf(b, "// %s reaches %s through %s.\n", typeName, root.Name,
			strings.Join(splitCamelPath(suffix), "."))
	}
	fmt.Fprintf(b, "type %s struct {\n%s}\n\n", typeName, body.String())
}

// splitCamelPath turns the concatenated suffix back into a readable path for
// the doc comment: "CommentsAuthor" -> ["Comments", "Author"].
func splitCamelPath(s string) []string {
	var out []string
	start := 0
	for i := 1; i < len(s); i++ {
		if s[i] >= 'A' && s[i] <= 'Z' {
			out = append(out, s[start:i])
			start = i
		}
	}
	return append(out, s[start:])
}
