// Code generated by vv. DO NOT EDIT.

package auditserving

import (
	vvmodule "github.com/frostgrove/vv/app/module"
)

var VVModule = vvmodule.MustDefine(vvmodule.Spec{
	Name:  "audit",
	Order: 400,
	Provide: []any{
		NewAttempts,
		NewHistory,
		NewRecorder,
	},
	Checks: []any{
		NewHealth,
	},
})
