// Code generated by rxcrud. DO NOT EDIT.

package main

import (
	"time"

	"github.com/shardit-io/rx/crud"
	"github.com/shardit-io/rx/repo/decorators/specs"
)

// ProductUpdate is the partial-update DTO for Product.
// A pointer field is optional; a crud.Opt field is optional and nullable,
// so an absent key, an explicit null and a value stay three different things.
type ProductUpdate struct {
	Sku    *string       `json:"sku,omitempty"`
	Name   *string       `json:"name,omitempty"`
	Price  *int          `json:"price,omitempty"`
	Stock  crud.Opt[int] `json:"stock,omitzero"`
	Active *bool         `json:"active,omitempty"`
}

// ProductAttrs is the generated metamodel shape for Product.
type ProductAttrs struct {
	ID        specs.Ord[Product, int64]
	Sku       specs.Str[Product]
	Name      specs.Str[Product]
	Price     specs.Ord[Product, int]
	Stock     specs.Ord[Product, int]
	Active    specs.Attr[Product, bool]
	CreatedAt specs.Cmp[Product, time.Time]
}

// Product_ is the metamodel of Product: typed, path-aware field references.
// It is validated against the model at package initialisation.
var Product_ = specs.Metamodel[Product, ProductAttrs]()
