// Code generated by vv. DO NOT EDIT.

package entstore

import (
	"github.com/frostgrove/vv/crud"
	"github.com/frostgrove/vv/crud/decorators/specs"
	"github.com/frostgrove/vv/crud/sqlrepo"
	"github.com/frostgrove/vv/port"
	ent "github.com/frostgrove/vv/test/ent"
	"github.com/frostgrove/vv/utils"
	"time"
)

type UserUpdate struct {
	TenantID *int64         `json:"tenantID,omitempty"`
	Email    *string        `json:"email,omitempty"`
	Name     *string        `json:"name,omitempty"`
	Age      utils.Opt[int] `json:"age,omitzero"`
	Active   *bool          `json:"active,omitempty"`
}

type UserAttrs struct {
	ID        specs.Ord[ent.User, int64]
	TenantID  specs.Ord[ent.User, int64]
	Email     specs.Str[ent.User]
	Name      specs.Str[ent.User]
	Age       specs.Ord[ent.User, int]
	Active    specs.Attr[ent.User, bool]
	CreatedAt specs.Cmp[ent.User, time.Time]
}

var User_ = specs.Metamodel[ent.User, UserAttrs]()

type UserRepo = crud.Repo[ent.User, int64, UserUpdate]

var UserRepository = sqlrepo.Define[ent.User, int64, UserUpdate]("")

func NewUserRepository(src crud.Source) *UserRepo {
	return UserRepository.Bind(src)
}

func init() {
	port.MustCoverUpdate[ent.User, UserUpdate]("CreatedAt")
}
